// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	dbHealth: () => typedError<DbHealth, string>(__TAURI_INVOKE("db_health")),
	settingsSet: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("settings_set", { key, value })),
	settingsGet: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("settings_get", { key })),
	settingsGetAll: () => typedError<([string, string])[], string>(__TAURI_INVOKE("settings_get_all")),
	settingsSetMany: (entries: ([string, string])[]) => typedError<null, string>(__TAURI_INVOKE("settings_set_many", { entries })),
	appInfo: () => typedError<AppInfo, string>(__TAURI_INVOKE("app_info")),
	clearAllData: () => typedError<null, string>(__TAURI_INVOKE("clear_all_data")),
	secretSet: (name: string, value: string) => typedError<null, string>(__TAURI_INVOKE("secret_set", { name, value })),
	secretHas: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("secret_has", { name })),
	secretDelete: (name: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete", { name })),
	/**
	 *  Verify the cached presence flag against the real keychain. Used when the
	 *  user explicitly asks ("the key isn't working" / "did I really save it?").
	 *  This DOES unlock the keychain.
	 */
	secretVerify: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("secret_verify", { name })),
	chat: (provider: string, messages: Message[], options: ChatOptions, fallbacks: ProviderModel[]) => typedError<ChatResponse, string>(__TAURI_INVOKE("chat", { provider, messages, options, fallbacks })),
	chatStream: (provider: string, messages: Message[], options: ChatOptions, fallbacks: ProviderModel[], onEvent: Channel<ChatEvent>) => typedError<null, string>(__TAURI_INVOKE("chat_stream", { provider, messages, options, fallbacks, onEvent })),
	selectProjectFolder: () => typedError<string | null, string>(__TAURI_INVOKE("select_project_folder")),
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (name: string, rootPath: string) => typedError<number, string>(__TAURI_INVOKE("create_project", { name, rootPath })),
	deleteProject: (projectId: number, deleteOculpm: boolean, deleteAgentsMd: boolean) => typedError<null, string>(__TAURI_INVOKE("delete_project", { projectId, deleteOculpm, deleteAgentsMd })),
	renameProject: (projectId: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_project", { projectId, name })),
	projectStats: (projectId: number) => typedError<ProjectStats, string>(__TAURI_INVOKE("project_stats", { projectId })),
	indexProject: (projectId: number, onProgress: Channel<IndexProgress>) => typedError<IndexResult, string>(__TAURI_INVOKE("index_project", { projectId, onProgress })),
	searchChunks: (projectId: number, query: string, limit: number, includeDocs: boolean) => typedError<ChunkSearchResult[], string>(__TAURI_INVOKE("search_chunks", { projectId, query, limit, includeDocs })),
	searchText: (projectId: number, query: string, limit: number) => typedError<ChunkSearchResult[], string>(__TAURI_INVOKE("search_text", { projectId, query, limit })),
	searchSymbols: (projectId: number, query: string, limit: number) => typedError<SymbolSearchResult[], string>(__TAURI_INVOKE("search_symbols", { projectId, query, limit })),
	getFileSymbols: (fileId: number) => typedError<SymbolDef[], string>(__TAURI_INVOKE("get_file_symbols", { fileId })),
	getCodeGraph: (projectId: number, opts: GraphOpts) => typedError<CodeGraph, string>(__TAURI_INVOKE("get_code_graph", { projectId, opts })),
	getChangeImpact: (projectId: number, changedPaths: string[]) => typedError<ImpactReport, string>(__TAURI_INVOKE("get_change_impact", { projectId, changedPaths })),
	getFileCalls: (fileId: number) => typedError<SymbolCall[], string>(__TAURI_INVOKE("get_file_calls", { fileId })),
	clearProjectIndex: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("clear_project_index", { projectId })),
	goalCreate: (projectId: number | null, title: string, description: string | null, priority: number, dueDate: number | null) => typedError<Goal, string>(__TAURI_INVOKE("goal_create", { projectId, title, description, priority, dueDate })),
	goalList: (projectId: number | null, statusFilter: string | null) => typedError<Goal[], string>(__TAURI_INVOKE("goal_list", { projectId, statusFilter })),
	goalUpdate: (goalId: number, title: string | null, description: string | null, status: string | null, priority: number | null, dueDate: number | null, progress: number | null) => typedError<Goal, string>(__TAURI_INVOKE("goal_update", { goalId, title, description, status, priority, dueDate, progress })),
	goalDelete: (goalId: number) => typedError<null, string>(__TAURI_INVOKE("goal_delete", { goalId })),
	subtaskCreate: (goalId: number, title: string) => typedError<Subtask, string>(__TAURI_INVOKE("subtask_create", { goalId, title })),
	subtaskList: (goalId: number) => typedError<Subtask[], string>(__TAURI_INVOKE("subtask_list", { goalId })),
	subtaskToggle: (subtaskId: number) => typedError<Subtask, string>(__TAURI_INVOKE("subtask_toggle", { subtaskId })),
	subtaskDelete: (subtaskId: number) => typedError<null, string>(__TAURI_INVOKE("subtask_delete", { subtaskId })),
	/**  List the project's plans (summary + progress + done counts). */
	planList: (projectId: number) => typedError<PlanSummary[], string>(__TAURI_INVOKE("plan_list", { projectId })),
	/**
	 *  One plan's detail: items (with per-item last attribution), decisions, and
	 *  non-fatal parse warnings. `None` when the plan_id isn't found.
	 */
	planGet: (projectId: number, planId: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_get", { projectId, planId })),
	/**
	 *  Append-only attribution history for one item (who changed it, when,
	 *  from→to, linked journal).
	 */
	planItemHistory: (projectId: number, planId: string, itemId: string) => typedError<PlanItemUpdateDto[], string>(__TAURI_INVOKE("plan_item_history", { projectId, planId, itemId })),
	/**  Create a new empty plan (`.oculpm/planner/<slug>.md`) and return its summary. */
	planCreate: (projectId: number, title: string) => typedError<PlanSummary, string>(__TAURI_INVOKE("plan_create", { projectId, title })),
	/**
	 *  Apply an edit to a plan's `.md` SSOT: mutate the body (glyph / new item) and
	 *  append an attribution row to the plan-log, stamped with `agent_id`
	 *  (defaults to `user`). Returns the refreshed plan detail.
	 */
	planApplyEdit: (projectId: number, planId: string, op: PlanEditOp, agentId: string | null) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_apply_edit", { projectId, planId, op, agentId })),
	/**
	 *  Ask the configured in-app LLM to update item statuses from recent journal
	 *  activity. The model proposes `{item_id, status}` edits; we apply the valid,
	 *  changed ones via the same plan-log path, stamped `agent_id = inapp:<provider>`.
	 */
	planAiRefresh: (projectId: number, planId: string, provider: string, model: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_ai_refresh", { projectId, planId, provider, model })),
	/**  One-time import of legacy `goals`/`subtasks` into `_imported.md`. */
	planMigrateGoals: (projectId: number) => typedError<PlanSummary, string>(__TAURI_INVOKE("plan_migrate_goals", { projectId })),
	/**  Recent plan activity across all plans — Today's "계획 업데이트" block. */
	planRecentUpdates: (projectId: number, limit: number) => typedError<PlanActivityDto[], string>(__TAURI_INVOKE("plan_recent_updates", { projectId, limit })),
	/**
	 *  Set a plan's lifecycle status (`active` / `done` / `archived`). `done` and
	 *  `archived` LOCK the plan: `plan_apply_edit` / `plan_ai_refresh` refuse to
	 *  touch it and AGENTS.md tells external agents the same — so finished plans
	 *  stay frozen and work moves to a new plan (Planner #1). Returns refreshed
	 *  detail.
	 */
	planSetStatus: (projectId: number, planId: string, status: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_set_status", { projectId, planId, status })),
	/**
	 *  Rename a plan (frontmatter `title:`). The plan `id` / filename stay the same
	 *  so item attribution + references keep working. Returns refreshed detail.
	 */
	planRename: (projectId: number, planId: string, title: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_rename", { projectId, planId, title })),
	/**
	 *  Delete a plan: remove its `.oculpm/planner/<id>.md` file and drop the cache
	 *  rows (a full reproject from disk is the only cache writer, so listing after
	 *  the unlink cleans up). Works regardless of lock state.
	 */
	planDelete: (projectId: number, planId: string) => typedError<null, string>(__TAURI_INVOKE("plan_delete", { projectId, planId })),
	conversationCreate: (title: string, provider: string | null, model: string | null, projectId: number | null) => typedError<Conversation, string>(__TAURI_INVOKE("conversation_create", { title, provider, model, projectId })),
	conversationList: (projectId: number | null) => typedError<Conversation[], string>(__TAURI_INVOKE("conversation_list", { projectId })),
	conversationRename: (conversationId: number, title: string) => typedError<null, string>(__TAURI_INVOKE("conversation_rename", { conversationId, title })),
	conversationSetContext: (conversationId: number, provider: string | null, model: string | null, projectId: number | null) => typedError<null, string>(__TAURI_INVOKE("conversation_set_context", { conversationId, provider, model, projectId })),
	conversationDelete: (conversationId: number) => typedError<null, string>(__TAURI_INVOKE("conversation_delete", { conversationId })),
	chatMessageAppend: (conversationId: number, role: string, content: string, provider: string | null, model: string | null) => typedError<ChatMessage, string>(__TAURI_INVOKE("chat_message_append", { conversationId, role, content, provider, model })),
	chatMessageList: (conversationId: number) => typedError<ChatMessage[], string>(__TAURI_INVOKE("chat_message_list", { conversationId })),
	/**
	 *  Persist that the user applied the ActionProposalCard at `message_index`
	 *  inside `conversation_id`. Idempotent — re-recording just refreshes
	 *  `applied_at`. Replaces the old `localStorage[action_{conv}_{i}]="applied"`
	 *  pattern in `ChatPanel`.
	 */
	recordConversationAction: (conversationId: number, messageIndex: number, status: string | null) => typedError<ConversationAction, string>(__TAURI_INVOKE("record_conversation_action", { conversationId, messageIndex, status })),
	listConversationActions: (conversationId: number) => typedError<ConversationAction[], string>(__TAURI_INVOKE("list_conversation_actions", { conversationId })),
	openDevtools: () => typedError<null, string>(__TAURI_INVOKE("open_devtools")),
	openTerminalWindow: () => typedError<null, string>(__TAURI_INVOKE("open_terminal_window")),
	readProjectFile: (projectId: number, relPath: string) => typedError<string, string>(__TAURI_INVOKE("read_project_file", { projectId, relPath })),
	/**
	 *  Read an inclusive, 1-indexed line range from a project file. Backs the
	 *  symbol-search "펼쳐서 코드 보기" toggle — symbol hits carry only a line
	 *  range, so the UI lazily fetches the body on expand instead of bloating
	 *  every result with content. Out-of-range bounds clamp to the file.
	 */
	readFileRange: (projectId: number, relPath: string, startLine: number, endLine: number) => typedError<string, string>(__TAURI_INVOKE("read_file_range", { projectId, relPath, startLine, endLine })),
	/**  프로젝트 `docs/` 폴더를 마크다운 트리로 반환한다. 폴더가 없으면 `exists=false`. */
	docsTree: (projectId: number) => typedError<DocsTree, string>(__TAURI_INVOKE("docs_tree", { projectId })),
	/**  단일 문서의 마크다운 본문을 읽는다. `rel_path` 는 프로젝트 루트 기준 (`docs/...`). */
	docsRead: (projectId: number, relPath: string) => typedError<string, string>(__TAURI_INVOKE("docs_read", { projectId, relPath })),
	/**  문서가 참조하는 이미지를 base64 로 읽는다. `rel_path` 는 프로젝트 루트 기준. */
	docsAsset: (projectId: number, relPath: string) => typedError<DocsAsset, string>(__TAURI_INVOKE("docs_asset", { projectId, relPath })),
	/**
	 *  Evaluate how ambiguous the user's request is. Returns 1~3 clarifying
	 *  questions plus an `auto_proceed` flag — the frontend skips the dialog when
	 *  `auto_proceed` is true or when no questions are produced.
	 * 
	 *  We deliberately do NOT embed code context here — the goal is a cheap
	 *  ambiguity check (≤500 input / ≤300 output tokens per §4.3), so the LLM
	 *  only sees the user's prompt and a short list of file paths from the
	 *  project to ground its questions.
	 */
	clarifyEditIntent: (projectId: number, userRequest: string, provider: string, model: string) => typedError<ClarifyResult, string>(__TAURI_INVOKE("clarify_edit_intent", { projectId, userRequest, provider, model })),
	generateEditPromptWithAnswers: (projectId: number, userRequest: string, answers: ClarifyAnswer[], provider: string, model: string) => typedError<EditPromptResult, string>(__TAURI_INVOKE("generate_edit_prompt_with_answers", { projectId, userRequest, answers, provider, model })),
	startPtySession: (sessionId: string, cwd: string, rows: number, cols: number) => typedError<null, string>(__TAURI_INVOKE("start_pty_session", { sessionId, cwd, rows, cols })),
	writeToPty: (sessionId: string, data: string) => typedError<null, string>(__TAURI_INVOKE("write_to_pty", { sessionId, data })),
	resizePty: (sessionId: string, rows: number, cols: number) => typedError<null, string>(__TAURI_INVOKE("resize_pty", { sessionId, rows, cols })),
	killPtySession: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("kill_pty_session", { sessionId })),
	gitLog: (projectId: number, limit: number) => typedError<GitCommit[], string>(__TAURI_INVOKE("git_log", { projectId, limit })),
	gitGraph: (projectId: number, limit: number) => typedError<GitGraphCommit[], string>(__TAURI_INVOKE("git_graph", { projectId, limit })),
	gitStatus: (projectId: number) => typedError<GitRepoStatus, string>(__TAURI_INVOKE("git_status", { projectId })),
	/**  Lite-W6 PR5 — slim head + dirty-count wrapper for the Today mini git chip. */
	gitHeadStatusBrief: (projectId: number) => typedError<GitHeadStatusBrief, string>(__TAURI_INVOKE("git_head_status_brief", { projectId })),
	githubVerify: () => typedError<GithubVerifyResult, string>(__TAURI_INVOKE("github_verify")),
	/**
	 *  Re-run the indexing pipeline for `paths` (relative to the project root).
	 *  Mirrors the per-file branch of `commands::project::index_project` so that
	 *  LocalDiffView can refresh a small set without re-scanning the whole tree.
	 */
	reindexPaths: (projectId: number, paths: string[]) => typedError<LocalDiffReindexReport, string>(__TAURI_INVOKE("reindex_paths", { projectId, paths })),
	/**
	 *  Hybrid diff: tries git first, falls back to the captured snapshot when git
	 *  can't help. Returns `SnapshotsUnavailable` only when neither baseline exists
	 *  — never bubbles `fatal: bad revision 'HEAD'` to the UI.
	 */
	computeDiff: (projectId: number, path: string, maxBytes: number, baseline: string | null) => typedError<DiffResult, string>(__TAURI_INVOKE("compute_diff", { projectId, path, maxBytes, baseline })),
	/**
	 *  PR6.6 — re-capture snapshots for the supplied paths from disk content.
	 *  Powers the LocalDiffView "비우기" action: after the user acknowledges a
	 *  batch of changes, the diff baselines are advanced so subsequent edits
	 *  show against the just-cleared state instead of the original index.
	 */
	resnapshotPaths: (projectId: number, paths: string[]) => typedError<number, string>(__TAURI_INVOKE("resnapshot_paths", { projectId, paths })),
	/**
	 *  Persistent uncommitted-change list for the 변경 diff 화면. Backed by
	 *  `git status` so it survives app restarts and project switches (the live
	 *  file-watcher buffer does neither). Non-git projects return an empty Vec and
	 *  the UI keeps using the watcher buffer + snapshot baselines.
	 */
	gitUncommittedChanges: (projectId: number) => typedError<GitChange[], string>(__TAURI_INVOKE("git_uncommitted_changes", { projectId })),
	/**
	 *  Files changed by the most recent commit, with its sha/subject. The 변경 diff
	 *  화면 shows these when the working tree is clean (e.g. the agent committed its
	 *  work) so the screen isn't empty. `None` for non-git / no-commit repos.
	 */
	gitLastCommitChanges: (projectId: number) => typedError<{
	sha: string,
	short_sha: string,
	subject: string,
	changes: GitChange[],
} | null, string>(__TAURI_INVOKE("git_last_commit_changes", { projectId })),
	openInEditor: (projectRoot: string, relPath: string, editorCmd: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { projectRoot, relPath, editorCmd })),
	/**
	 *  Open an http(s) URL in the user's default browser. Used by the Today commit
	 *  graph to jump to a commit on GitHub. We shell out to the OS opener
	 *  (`open` / `xdg-open` / `cmd start`) rather than the opener plugin so no
	 *  path/url scope config is needed (mirrors `oculpm_open_entry_in_editor`).
	 *  Only http/https is allowed — never a local path or arbitrary scheme.
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	getProjectOverview: (projectId: number) => typedError<{
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
} | null, string>(__TAURI_INVOKE("get_project_overview", { projectId })),
	generateProjectOverview: (projectId: number, provider: string, model: string) => typedError<ProjectOverview, string>(__TAURI_INVOKE("generate_project_overview", { projectId, provider, model })),
	/**
	 *  Returns `Some(new)` when the LLM was invoked, `None` when the cached
	 *  overview was still fresh enough to skip work.
	 */
	refreshProjectOverviewIfStale: (projectId: number, provider: string, model: string) => typedError<{
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
} | null, string>(__TAURI_INVOKE("refresh_project_overview_if_stale", { projectId, provider, model })),
	/**
	 *  Save a user-edited overview body. Setting `source_signature = None` is
	 *  load-bearing: the indexing hook checks for it and refuses to auto-regen
	 *  over manual edits (MASTER-GUIDE §4.2 "수동 편집 보호"). Identity and
	 *  stack_json are passed through unchanged from the caller — the frontend
	 *  editor lets users tweak the markdown body for now; richer per-section
	 *  edits land later.
	 */
	updateProjectOverview: (projectId: number, identity: string | null, stackJson: string | null, overviewMd: string) => typedError<ProjectOverview, string>(__TAURI_INVOKE("update_project_overview", { projectId, identity, stackJson, overviewMd })),
	dailyBrief: (projectId: number, dateUnix: number | null) => typedError<DailyBrief, string>(__TAURI_INVOKE("daily_brief", { projectId, dateUnix })),
	saveBlueprint: (id: number | null, name: string, ideaText: string | null, targetUsers: string | null, stackChoice: string | null, folderName: string | null, folderPath: string | null, seedGoalsJson: string | null, wizardStep: number) => typedError<ProjectBlueprint, string>(__TAURI_INVOKE("save_blueprint", { id, name, ideaText, targetUsers, stackChoice, folderName, folderPath, seedGoalsJson, wizardStep })),
	getBlueprint: (blueprintId: number) => typedError<ProjectBlueprint, string>(__TAURI_INVOKE("get_blueprint", { blueprintId })),
	listBlueprints: () => typedError<ProjectBlueprint[], string>(__TAURI_INVOKE("list_blueprints")),
	deleteBlueprint: (blueprintId: number) => typedError<null, string>(__TAURI_INVOKE("delete_blueprint", { blueprintId })),
	/**
	 *  Check if a CLI tool is available on the system PATH (or common install
	 *  locations). Returns availability, resolved path, and version string.
	 * 
	 *  The check uses `which`(Unix) / `where`(Windows) followed by a
	 *  `--version` probe. On failure, we scan well-known install directories
	 *  as a fallback (e.g. `~/.cargo/bin` for `cargo`).
	 */
	checkCliAvailable: (cliName: string) => typedError<CliCheckResult, string>(__TAURI_INVOKE("check_cli_available", { cliName })),
	/**
	 *  Create a new project from the Greenfield wizard.
	 * 
	 *  1. Creates the folder (if it doesn't exist)
	 *  2. Optionally runs a scaffold CLI (e.g. `pnpm create vite`)
	 *  3. Registers the project in the database via `create_project`
	 *  3b. (W3-PR10) Optionally initialises `.oculpm/` for the new project so
	 *      the user does not see the onboarding modal on first Today open.
	 *      Failure is **non-fatal**: the project row is already committed and
	 *      EmptyToday V1 provides a "활성화" recovery path.
	 *  4. Cleans up the blueprint (if any)
	 *  5. Returns the new project ID
	 */
	createGreenfieldProject: (name: string, rootPath: string, scaffoldCmd: string | null, scaffoldArgs: string[] | null, blueprintId: number | null, initOculpm: boolean) => typedError<GreenfieldResult, string>(__TAURI_INVOKE("create_greenfield_project", { name, rootPath, scaffoldCmd, scaffoldArgs, blueprintId, initOculpm })),
	/**
	 *  Ask the LLM to generate 3~5 initial goals for a newly created project
	 *  based on the user's idea and chosen tech stack. The goals are persisted
	 *  via `goal_create` and returned to the frontend for display in the wizard.
	 */
	generateSeedGoals: (projectId: number, ideaText: string, stackChoice: string, provider: string, model: string) => typedError<Goal[], string>(__TAURI_INVOKE("generate_seed_goals", { projectId, ideaText, stackChoice, provider, model })),
	/**
	 *  Idempotent project initialisation — creates `.oculpm/`, writes default
	 *  config, acquires the lock, and patches `.gitignore`. Returns a report of
	 *  what changed so the UI can surface "added 5 lines to .gitignore" etc.
	 */
	oculpmInit: (projectId: number) => typedError<OculpmInitReport, string>(__TAURI_INVOKE("oculpm_init", { projectId })),
	/**
	 *  Current `.oculpm/` status (initialised, lock, current workday, watcher).
	 *  Safe to call before init — returns a default uninitialised view.
	 */
	oculpmGetStatus: (projectId: number) => typedError<OculpmStatus, string>(__TAURI_INVOKE("oculpm_get_status", { projectId })),
	/**
	 *  Read the validated in-memory `OculpmConfig`. Errors if `oculpm_init` has
	 *  not been called for this project.
	 */
	oculpmGetConfig: (projectId: number) => typedError<OculpmConfig, string>(__TAURI_INVOKE("oculpm_get_config", { projectId })),
	/**
	 *  Validate + persist a new `OculpmConfig` (atomic write) and refresh the
	 *  in-memory `WorkdayResolver`. Rejects invalid tz / HH:MM without touching
	 *  disk.
	 */
	oculpmSetConfig: (projectId: number, newConfig: OculpmConfig) => typedError<null, string>(__TAURI_INVOKE("oculpm_set_config", { projectId, newConfig })),
	/**  Manually start a session. Idempotent — returns existing if already active. */
	oculpmStartSessionManual: (projectId: number) => typedError<{
	/**  `YYYYMMDD-NNN`. */
	id: string,
	started_at: string,
	ended_at: string | null,
	ended_reason: EndedReason | null,
	/**
	 *  u32 — caps at ~49 days of continuous active time. A single session
	 *  will never approach this.
	 */
	active_window_ms: number,
	file_event_count: number,
	files_unique: number,
	git_head_at_start: string | null,
	git_head_at_end: string | null,
	agent_label_guess: string | null,
	/**  Paths relative to `.oculpm/journal/<workday>/`. */
	linked_journal_entries: string[],
} | null, string>(__TAURI_INVOKE("oculpm_start_session_manual", { projectId })),
	/**  Manually end a session. `session_id` must match the active session. */
	oculpmEndSessionManual: (projectId: number, sessionId: string) => typedError<null, string>(__TAURI_INVOKE("oculpm_end_session_manual", { projectId, sessionId })),
	/**  List sessions for a workday. `workday = None` → today. */
	oculpmListSessions: (projectId: number, workday: string | null) => typedError<Session[], string>(__TAURI_INVOKE("oculpm_list_sessions", { projectId, workday })),
	/**  Get file change events for a workday, optionally filtered by session_id. */
	oculpmGetFileChanges: (projectId: number, workday: string, sessionId: string | null) => typedError<FileChangeEvent[], string>(__TAURI_INVOKE("oculpm_get_file_changes", { projectId, workday, sessionId })),
	/**  Start the filesystem watcher. Idempotent. Requires lock ownership. */
	oculpmWatcherStart: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("oculpm_watcher_start", { projectId })),
	/**  Stop the filesystem watcher. Idempotent. */
	oculpmWatcherStop: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("oculpm_watcher_stop", { projectId })),
	/**
	 *  List cached journal entries for a workday (or today if None) with filters.
	 *  Returns `[]` for uninitialised projects so the UI can render EmptyToday
	 *  without a special-case error path.
	 */
	oculpmListJournalEntries: (projectId: number, workday: string | null, filters: {
	types: EntryType[],
	verified_only: boolean,
	/**
	 *  Reserved for W4 (LayerComparison). PR2 wires the column path but
	 *  `mismatch_only=true` returns no rows because no entry has been
	 *  flagged yet.
	 */
	mismatch_only: boolean,
	/**  `checkbox == Some(false)` OR `status != "done"`. */
	unfinished_only: boolean,
	search: string | null,
	/**  W5-PR6 — agent_id filter. Empty = no constraint (all agents). */
	agents?: string[],
	/**
	 *  W5-PR6 — difficulty filter. Empty = no constraint. Note the cache
	 *  column is nullable ("미지정"); difficulty filter therefore *cannot*
	 *  match the null bucket — that's a separate W6 toggle.
	 */
	difficulties?: Difficulty[],
} | null) => typedError<JournalEntrySummary[], string>(__TAURI_INVOKE("oculpm_list_journal_entries", { projectId, workday, filters })),
	/**
	 *  Get a single journal entry by relative path. Falls back to on-demand
	 *  disk read + cache upsert if the row is missing. Returns `None` only
	 *  when the file does not exist on disk either.
	 */
	oculpmGetJournalEntry: (projectId: number, relativePath: string) => typedError<{
	/**  `<workday>/<Category>/<file>.md` — relative to `.oculpm/journal/`. */
	relative_path: string,
	frontmatter: JournalFrontmatter,
	/**  First non-blank line after frontmatter, with the `[ ]`/`[x]` prefix stripped. */
	title: string,
	/**  `None` when first line lacks a checkbox; `Some(true)` for `[x]`, `Some(false)` for `[ ]`. */
	checkbox: boolean | null,
	body_markdown: string,
	/**
	 *  u32 (not u64) for specta BigInt-export compatibility — see
	 *  docs/2026521/Errors/2026-05-21-specta-bigint-export.md. Caps at 4 GB
	 *  which no realistic journal entry will hit.
	 */
	byte_size: number,
	mtime: string,
	/**
	 *  False when the YAML frontmatter failed to parse (the row is still cached
	 *  as a synthesized chore). Drives a ⚠ reliability badge (F7a).
	 */
	parse_ok: boolean,
	/**  Non-fatal parse warnings (missing tz offset, agent-as-string, bad op, …). */
	parse_warnings: string[],
} | null, string>(__TAURI_INVOKE("oculpm_get_journal_entry", { projectId, relativePath })),
	/**
	 *  Read the per-file diffs recorded for a journal entry at the moment it was
	 *  first indexed (see `oculpm::entry_diffs`). Returns `[]` when nothing was
	 *  captured — the entry predates the feature, the project isn't a git repo, or
	 *  it was written after committing — and the UI renders "기록된 변경 없음".
	 */
	oculpmGetEntryDiffs: (projectId: number, relativePath: string) => typedError<EntryFileDiff[], string>(__TAURI_INVOKE("oculpm_get_entry_diffs", { projectId, relativePath })),
	/**
	 *  Group the watcher's changed file paths by the journal entry that recorded
	 *  each, with the plan items linked to that entry (Dogfooding #3). Files no
	 *  entry recorded land in a trailing `entry_path: None` bucket.
	 */
	oculpmGroupChanges: (projectId: number, paths: string[]) => typedError<ChangeGroup[], string>(__TAURI_INVOKE("oculpm_group_changes", { projectId, paths })),
	/**
	 *  Toggle `verified_by_user` on a journal entry's frontmatter. Atomic
	 *  write-through: file is rewritten first, then the cache is upserted in
	 *  the same call so the UI sees the change immediately.
	 */
	oculpmSetJournalVerified: (projectId: number, relativePath: string, verified: boolean) => typedError<null, string>(__TAURI_INVOKE("oculpm_set_journal_verified", { projectId, relativePath, verified })),
	/**
	 *  Rebuild the journal cache from disk. Drops every cached row for the
	 *  project and re-walks `.oculpm/journal/`. Use after manual sqlite
	 *  tampering or schema migration.
	 */
	oculpmReindexCache: (projectId: number) => typedError<ReindexReport, string>(__TAURI_INVOKE("oculpm_reindex_cache", { projectId })),
	/**
	 *  Write a manual journal entry from the user-authored draft. Validates
	 *  the slug (kebab-case ASCII, 1..=60 chars), resolves the session_id
	 *  (active session / draft override / sentinel), writes the file with
	 *  the spec's `<HHMM>_<type>_<slug>.md` naming, and returns the hydrated
	 *  `JournalEntry`. On filename collision the writer suffixes `__2`/`__3`.
	 */
	oculpmCreateManualEntry: (projectId: number, draft: ManualEntryDraft) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_create_manual_entry", { projectId, draft })),
	/**
	 *  Inline-edit one or both of `difficulty` / `status` on an existing entry.
	 *  Same write-through semantics as `oculpm_set_journal_verified` — atomic
	 *  file write then cache upsert — and returns the hydrated entry so the
	 *  frontend's optimistic UI can resync to truth without a second fetch.
	 * 
	 *  Argument shape: send `null` for a field to leave it unchanged. To clear
	 *  `difficulty`, send `Some(None)` (encoded over the wire as the JSON
	 *  `null` *inside* a present object key); the frontend wrapper handles
	 *  this distinction.
	 */
	oculpmUpdateEntryMeta: (projectId: number, relativePath: string, difficultyChange: {
	value: Difficulty | null,
} | null, status: "planned" | "in_progress" | "done" | "abandoned" | null) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_update_entry_meta", { projectId, relativePath, difficultyChange, status })),
	/**
	 *  Re-render every adapter according to `config.agents.active`. Idempotent —
	 *  when nothing's changed since the last sync, every result is `unchanged`
	 *  and disk mtimes don't move. Called by:
	 *    - the Greenfield wizard right after init (W3-PR10)
	 *    - the OculpmSettings save (W4-PR7)
	 *    - the watcher's `.oculpm/agents/**` handler (master template edits)
	 */
	oculpmAgentsSyncActive: (projectId: number) => typedError<AgentSyncReport, string>(__TAURI_INVOKE("oculpm_agents_sync_active", { projectId })),
	/**
	 *  Read-only adapter heuristic. Used by Settings "감지" button + Greenfield
	 *  default active set.
	 */
	oculpmAgentsDetect: (projectId: number) => typedError<AgentDetection[], string>(__TAURI_INVOKE("oculpm_agents_detect", { projectId })),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — return the project's master template
	 *  text so the UI's "프롬프트 복사" action can paste it into a chat. Read-only;
	 *  does not touch any adapter files. Separates the *file sync* concern (which
	 *  `oculpm_agents_sync_active` already handles) from the *one-shot prompt
	 *  delivery* concern that the user actually wants when clicking "복사".
	 */
	oculpmAgentsGetMasterTemplate: (projectId: number) => typedError<string, string>(__TAURI_INVOKE("oculpm_agents_get_master_template", { projectId })),
	/**
	 *  Is a newer agent-rules master template available than the one on disk?
	 *  `None` = up-to-date. Surfaced as an "update" prompt on project open.
	 */
	oculpmAgentsCheckMasterUpgrade: (projectId: number) => typedError<{
	from_version: number,
	to_version: number,
} | null, string>(__TAURI_INVOKE("oculpm_agents_check_master_upgrade", { projectId })),
	/**
	 *  Upgrade the on-disk master to the embedded one + re-sync adapters (AGENTS.md
	 *  etc.). The previous master is backed up to `_template.md.bak`.
	 */
	oculpmAgentsApplyMasterUpgrade: (projectId: number) => typedError<AgentSyncReport, string>(__TAURI_INVOKE("oculpm_agents_apply_master_upgrade", { projectId })),
	/**
	 *  W4-PR5 — compare a session's index ndjson against the union of journal
	 *  `files_touched` paths. Returns matched / missing / hallucinated sets +
	 *  jaccard severity. (Lite-W6 PR3 retired the DiffVsNarrative UI; the
	 *  command is kept for backend introspection + potential future surfaces.)
	 */
	oculpmCompareLayers: (projectId: number, sessionId: string) => typedError<LayerComparison, string>(__TAURI_INVOKE("oculpm_compare_layers", { projectId, sessionId })),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — return the absolute path to the
	 *  directory holding the daily-rotated `oculpm.log.YYYY-MM-DD` files. Settings
	 *  uses this for the "로그 폴더 열기" button (delegates to opener plugin).
	 *  Returns `None` if the process started with file logging disabled (test
	 *  runs / unsupported platform).
	 */
	oculpmGetLogDir: () => typedError<string | null, string>(__TAURI_INVOKE("oculpm_get_log_dir")),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — bridge `console.*` calls from the
	 *  webview into the backend's `tracing` layers so the user only has to grab
	 *  **one** file when something breaks. The frontend wraps console.log/warn/
	 *  error in `setupOculpmLogBridge()` (App.tsx) and forwards every call here.
	 * 
	 *  We intentionally don't echo back to the webview; the webview already
	 *  printed the original line in DevTools. We just want it in `oculpm.log`.
	 */
	oculpmLog: (level: string, target: string, message: string) => __TAURI_INVOKE<void>("oculpm_log", { level, target, message }),
	/**
	 *  W4 dogfooding (2026-05-27) — overwrite the body markdown of an existing
	 *  journal entry. Frontmatter is preserved verbatim. Returns the hydrated
	 *  entry so the UI can resync without a second fetch.
	 */
	oculpmUpdateEntryBody: (projectId: number, relativePath: string, bodyMarkdown: string) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_update_entry_body", { projectId, relativePath, bodyMarkdown })),
	/**
	 *  W4 dogfooding (2026-05-27) — open a journal entry's `.md` file with the
	 *  OS default app. The opener plugin's path-glob scope keeps rejecting
	 *  project-local paths (3 dogfooding regressions); this command resolves the
	 *  absolute path inside the backend and invokes `open` / `xdg-open` /
	 *  `cmd /c start` directly, sidestepping the scope check entirely.
	 */
	oculpmOpenEntryInEditor: (projectId: number, relativePath: string) => typedError<null, string>(__TAURI_INVOKE("oculpm_open_entry_in_editor", { projectId, relativePath })),
	/**
	 *  Single-shot fetch of every Overview widget. `window_days` clamps to
	 *  1..=365 inside the manager — the modal-facing default is 90 (heatmap).
	 */
	oculpmOverviewStats: (projectId: number, windowDays: number) => typedError<OculpmOverviewStats, string>(__TAURI_INVOKE("oculpm_overview_stats", { projectId, windowDays })),
	/**
	 *  Synthesise one journal entry per recent git commit (cold-start backfill).
	 *  Idempotent: re-running only adds commits not seen before. `max_commits`
	 *  caps the scan (clamped 1..=2000 in the manager).
	 */
	oculpmBackfillFromGit: (projectId: number, maxCommits: number) => typedError<BackfillReport, string>(__TAURI_INVOKE("oculpm_backfill_from_git", { projectId, maxCommits })),
};

/** Events */
export const events = {
	oculpmAgentDrift: makeEvent<OculpmAgentDrift>("oculpm-agent-drift"),
	oculpmAgentsTemplateChanged: makeEvent<OculpmAgentsTemplateChanged>("oculpm-agents-template-changed"),
	oculpmFileChanged: makeEvent<OculpmFileChanged>("oculpm-file-changed"),
	oculpmIntegrityWarning: makeEvent<OculpmIntegrityWarning>("oculpm-integrity-warning"),
	oculpmJournalAdded: makeEvent<OculpmJournalAdded>("oculpm-journal-added"),
	oculpmJournalPathChanged: makeEvent<OculpmJournalPathChanged>("oculpm-journal-path-changed"),
	oculpmJournalUpdated: makeEvent<OculpmJournalUpdated>("oculpm-journal-updated"),
	oculpmSessionEnded: makeEvent<OculpmSessionEnded>("oculpm-session-ended"),
	oculpmSessionStarted: makeEvent<OculpmSessionStarted>("oculpm-session-started"),
};

/* Types */
export type AgentCount = {
	agent_id: string,
	entry_count: number,
	/**  `entry_count / total_entries`. `0.0` when no entries. */
	share: number | null,
};

export type AgentDetection = {
	agent_id: string,
	confidence: DetectConfidence,
	adapter_path_exists: boolean,
	adjacent_marker_exists: boolean,
};

export type AgentRef = {
	/**
	 *  One of `claude-code`, `cursor`, `antigravity`, `gemini-cli`, `pi`,
	 *  `manual`.
	 */
	id: string,
	/**  The model the agent ran on, e.g. `"Opus 4.8"` / `"Gemini 3 Pro"`. */
	version: string | null,
};

export type AgentSyncReport = {
	results: AgentSyncResult[],
};

export type AgentSyncResult = {
	id: string,
	/**  One of `inserted`, `updated`, `unchanged`, `removed`, `error`. */
	action: string,
	error: string | null,
	/**
	 *  blake3 hex of the bytes we own on disk after this sync. For
	 *  `Overwrite` adapters it's the file hash; for `ManagedBlock` adapters
	 *  it's the hash of the inner block content (between the markers). Used
	 *  by W4-PR4 to seed the drift comparator. `None` when the adapter was
	 *  removed / errored / left untouched without a file present.
	 */
	last_hash: string | null,
};

export type AgentsConfig = {
	/**  Subset of `["claude-code", "cursor", "antigravity", "gemini-cli"]`. */
	active: string[],
	auto_detect_on_open: boolean,
	auto_sync_adapters: boolean,
};

export type AppInfo = {
	db_path: string,
	app_data_dir: string,
	secrets_store: string,
	version: string,
};

/**
 *  Result of a git-history backfill (F5): one synthesised journal entry per
 *  commit. `skipped` counts commits already backfilled (idempotent re-runs).
 */
export type BackfillReport = {
	project_id: number,
	scanned: number,
	created: number,
	skipped: number,
};

/**
 *  A group of changed files attributed to one journal entry (Dogfooding #3).
 *  `entry_path == None` is the trailing "미기록 변경" bucket for files no
 *  journal entry recorded.
 */
export type ChangeGroup = {
	entry_path: string | null,
	entry_title: string | null,
	entry_type: string | null,
	created_at: string | null,
	plan_refs: ChangePlanRef[],
	files: string[],
};

/**
 *  One plan item linked (via the plan-log `journal_ref`) to a changed-file
 *  group's journal entry. Dogfooding #3 — surfaces "어떤 plan 에서" in the diff.
 */
export type ChangePlanRef = {
	plan_id: string,
	plan_title: string,
	item_title: string,
};

export type ChatEvent = { kind: "delta"; text: string } | { kind: "done" } | { kind: "error"; message: string };

export type ChatMessage = {
	id: number,
	conversation_id: number,
	role: string,
	content: string,
	provider: string | null,
	model: string | null,
	created_at: number,
};

export type ChatOptions = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
};

export type ChatResponse = {
	content: string,
	model: string,
	provider: string,
};

export type ChunkSearchResult = {
	chunk_id: number,
	file_path: string,
	start_line: number,
	end_line: number,
	content: string,
	distance: number | null,
};

export type ClarifyAnswer = {
	id: string,
	answer: string,
};

/**
 *  A single clarifying question shown to the user before we let the LLM
 *  produce the final English prompt. `kind` is either `"choice"` (radio
 *  buttons with `options`) or `"text"` (free-form input, `options` empty).
 */
export type ClarifyQuestion = {
	id: string,
	kind: string,
	text: string,
	options?: string[],
};

/**
 *  Backend response for the ambiguity-check pass. When `auto_proceed` is true
 *  the caller may skip the clarify dialog entirely and go straight to
 *  `generate_edit_prompt_with_answers` with no answers.
 */
export type ClarifyResult = {
	ambiguity_score: number | null,
	questions: ClarifyQuestion[],
	auto_proceed: boolean,
};

export type CliCheckResult = {
	available: boolean,
	cli_name: string,
	path: string | null,
	version: string | null,
};

export type CodeGraph = {
	nodes: GraphNodeDto[],
	edges: GraphEdgeDto[],
};

export type Conversation = {
	id: number,
	title: string,
	provider: string | null,
	model: string | null,
	project_id: number | null,
	created_at: number,
	updated_at: number,
	last_message_at: number | null,
};

export type ConversationAction = {
	id: number,
	conversation_id: number,
	message_index: number,
	status: string,
	applied_at: number,
};

/**
 *  Structured payload backing the Today screen. The frontend formats the
 *  numbers; we just join the underlying tables in a single round trip.
 * 
 *  `date_unix` is the local-day start (00:00) for which the brief was built.
 *  Callers can request any day, defaulting to "today" by passing `None`.
 * 
 *  Lite-W6 PR4: the changelog-derived fields were retired. The DTO shape
 *  is kept (with empty/zero placeholders) until the legacy DailyBrief
 *  view in TodayScreen is removed in a later PR; today's authoritative
 *  activity source is the journal entries rendered by TimelineView.
 */
export type DailyBrief = {
	date_unix: number,
	/**  Top 3 active goals — already ordered by priority then due_date. */
	focus_goals: Goal[],
	/**
	 *  Goals whose `updated_at` falls inside the requested day AND that are
	 *  marked completed. The "what did I finish" column.
	 */
	completed_today: Goal[],
};

export type DbHealth = {
	sqlite_version: string,
	vec_version: string,
	schema_version: number,
	path: string,
};

export type DetectConfidence = 
/**
 *  The adapter path itself exists — either we wrote it before, or a user
 *  (or another tool) is already aware of the adapter.
 */
"present" | 
/**
 *  An adjacent marker (`.cursor/`, `.claude/`, `.agent/`, `.gemini/`)
 *  exists but the adapter path doesn't — the user clearly uses this LLM
 *  even if our adapter isn't installed yet.
 */
"likely" | 
/**  No signal at all. */
"unknown";

export type DiffResult = {
	path: string,
	source: DiffSource,
};

export type DiffSource = 
/**  `git diff HEAD -- <path>` output. Empty `patch` = no diff. */
{ source: "git"; patch: string } | 
/**
 *  PR6.6 — snapshot vs disk unified-diff. Used when the git path can't
 *  serve a baseline: fresh repo (HEAD-less), non-git project, or git
 *  returned an empty patch but the file changed on disk after indexing.
 */
{ source: "snapshot"; patch: string } | 
/**
 *  The file has neither a git baseline nor a captured snapshot. UI prompts
 *  the user to run a partial reindex first.
 */
{ source: "snapshots_unavailable" };

export type Difficulty = "superhigh" | "high" | "medium" | "low" | "verylow";

/**
 *  Wire wrapper so the frontend can express "set difficulty to None" vs
 *  "leave difficulty alone". Two-step Option unfolds to:
 *    - omitted / null → `None` (leave alone)
 *    - `{ value: null }` → `Some(None)` (clear)
 *    - `{ value: "high" }` → `Some(Some(High))` (set)
 */
export type DifficultyChange = {
	value: Difficulty | null,
};

export type DifficultyMix = {
	verylow: number,
	low: number,
	medium: number,
	high: number,
	superhigh: number,
	/**  Entries that didn't specify a difficulty in frontmatter. */
	null_count: number,
};

/**  `docs_asset` 응답 — 이미지 바이트를 base64 + MIME 으로. 프런트는 `data:` URI 로 조립한다. */
export type DocsAsset = {
	mime: string,
	base64: string,
};

/**  `docs_tree` 응답. `exists=false` 면 프로젝트에 `docs/` 폴더가 없다 (빈 상태 UI). */
export type DocsTree = {
	exists: boolean,
	nodes: DocsTreeNode[],
};

/**
 *  docs 트리 한 노드. `relative_path` 는 **프로젝트 루트 기준** 슬래시 경로
 *  (예: `docs/graph-upgrade/00-master-plan.md`) — 그대로 `docs_read`/`docs_asset` 인자로 쓴다.
 */
export type DocsTreeNode = {
	name: string,
	relative_path: string,
	is_dir: boolean,
	children: DocsTreeNode[],
};

export type EditPromptResult = {
	english_prompt: string,
	korean_summary: string,
	related_files: string[],
};

export type EndedReason = "inactivity_timeout" | "app_quit" | "workday_boundary" | "manual" | "crash_recovered" | 
/**  W5 — session synthesized from migrated SQLite changelog entries. */
"synthetic_migrated";

/**
 *  One file's recorded diff for a journal entry. `patch` is a git-style unified
 *  diff (`a/ b/` headers) — never stored empty.
 */
export type EntryFileDiff = {
	path: string,
	patch: string,
};

/**
 *  User-facing filter for `list_entries`. Empty `types` means "all types".
 *  `search` matches against `title`, `slug`, `body_markdown`, and any tag
 *  in `oculpm_journal_tags` (case-insensitive for ASCII; substring for
 *  other scripts including Hangul).
 */
export type EntryFilters = {
	types: EntryType[],
	verified_only: boolean,
	/**
	 *  Reserved for W4 (LayerComparison). PR2 wires the column path but
	 *  `mismatch_only=true` returns no rows because no entry has been
	 *  flagged yet.
	 */
	mismatch_only: boolean,
	/**  `checkbox == Some(false)` OR `status != "done"`. */
	unfinished_only: boolean,
	search: string | null,
	/**  W5-PR6 — agent_id filter. Empty = no constraint (all agents). */
	agents?: string[],
	/**
	 *  W5-PR6 — difficulty filter. Empty = no constraint. Note the cache
	 *  column is nullable ("미지정"); difficulty filter therefore *cannot*
	 *  match the null bucket — that's a separate W6 toggle.
	 */
	difficulties?: Difficulty[],
};

export type EntryStatus = "planned" | "in_progress" | "done" | "abandoned";

export type EntryType = "bug" | "feature" | "error" | "refactor" | "chore";

export type FileChangeEvent = {
	ts: string,
	session_id: string,
	op: FileOp,
	path: string,
	hash_before: string | null,
	hash_after: string | null,
	/**
	 *  u32 — caps at 4 GB per file. Larger files skip hashing anyway
	 *  (`tags: ["large-file-hash-skipped"]`) so the value will be clamped.
	 */
	bytes: number,
};

export type FileOp = "create" | "update" | "delete" | "rename" | "correct";

export type FileTouched = {
	path: string,
	op: FileOp,
	bytes_added: number | null,
	bytes_removed: number | null,
	rename_from: string | null,
};

/**
 *  A single uncommitted change from `git status`. `op` is one of `"A"` / `"M"` /
 *  `"D"` so it lines up directly with the frontend `ChangeOp` union used by the
 *  변경 diff 화면. Renames/copies report the *new* path as an add.
 */
export type GitChange = {
	path: string,
	op: string,
};

export type GitCommit = {
	sha: string,
	short_sha: string,
	author_name: string,
	author_email: string,
	/**  Unix timestamp in seconds (author date). */
	timestamp: number,
	subject: string,
};

export type GitConfig = {
	journal_committed: boolean,
	forbid_journal_for_paths: string[],
	auto_redact_patterns: string[],
};

/**
 *  One commit in the graph view (Today git graph). Carries `parents` for lane
 *  routing and `refs` (branch/tag/HEAD decorations) so the UI can badge tips.
 */
export type GitGraphCommit = {
	sha: string,
	short_sha: string,
	parents: string[],
	author_name: string,
	/**  Unix timestamp in seconds (author date). */
	timestamp: number,
	subject: string,
	/**
	 *  Ref names pointing here (e.g. `main`, `origin/main`, a tag), HEAD-/tag-
	 *  prefixes stripped.
	 */
	refs: string[],
};

/**
 *  Lite-W6 PR5 — slim wrapper for the TitleBar mini git chip (UI consumer
 *  arrives in PR7). Returns just the branch + the count of `git status
 *  --porcelain` lines (staged + unstaged + untracked).
 */
export type GitHeadStatusBrief = {
	is_git_repo: boolean,
	/**  `None` when the repo is in detached-HEAD state or there is no repo. */
	head_branch: string | null,
	/**  Count of `--porcelain` lines. Capped at u32::MAX in practice. */
	uncommitted: number,
};

export type GitRemote = {
	name: string,
	url: string,
	/**  e.g. "github.com" — derived from the URL. */
	host: string | null,
	owner: string | null,
	repo: string | null,
};

export type GitRepoStatus = {
	is_git_repo: boolean,
	head_branch: string | null,
	remotes: GitRemote[],
};

export type GithubRateLimit = {
	limit: number,
	remaining: number,
	/**  Unix timestamp when the window resets. */
	reset: number,
};

export type GithubUser = {
	login: string,
	name: string | null,
	avatar_url: string | null,
	html_url: string,
};

export type GithubVerifyResult = {
	user: GithubUser,
	rate_limit: GithubRateLimit,
};

export type Goal = {
	id: number,
	project_id: number | null,
	title: string,
	description: string | null,
	status: string,
	priority: number,
	due_date: number | null,
	progress: number | null,
	created_at: number,
	updated_at: number,
};

export type GraphEdgeDto = {
	id: number,
	edge_type: string,
	source: number,
	target: number,
	weight: number | null,
	direction: string,
	estimated: boolean,
};

export type GraphNodeDto = {
	id: number,
	kind: string,
	label: string,
	sub_kind: string | null,
	language: string | null,
	file_id: number,
	file_path: string,
	start_line: number | null,
	end_line: number | null,
};

export type GraphOpts = {
	/**
	 *  Include symbol nodes + `contains` (file→symbol) edges. `false` = only
	 *  file nodes + `imports` edges (lighter payload for large projects).
	 */
	symbol_level: boolean,
};

export type GreenfieldResult = {
	project_id: number,
	scaffold_output: string | null,
	seed_goals: Goal[],
};

/**
 *  One day's worth of activity data for the heatmap. `score` is a UI-friendly
 *  derived value (entries weighted higher than file events).
 */
export type HeatmapCell = {
	workday: string,
	entry_count: number,
	file_event_count: number,
	score: number,
};

export type ImpactNode = {
	file_id: number,
	path: string,
	depth: number,
};

export type ImpactReport = {
	/**  Changed paths that were found in the index (subset of the input). */
	changed: string[],
	/**  Files that (transitively) import a changed file, nearest first. */
	affected: ImpactNode[],
};

export type IndexProgress = {
	current: number,
	total: number,
	current_file: string,
};

export type IndexResult = {
	files_processed: number,
	files_changed: number,
	chunks_created: number,
	took_ms: number,
};

export type IntegrityWarning = {
	/**  One of `frontmatter_parse`, `schema_mismatch`, `orphan_session`, `narrative_mismatch`, `lock_recovered`, ... */
	kind: string,
	path: string,
	message: string,
};

export type JournalEntry = {
	/**  `<workday>/<Category>/<file>.md` — relative to `.oculpm/journal/`. */
	relative_path: string,
	frontmatter: JournalFrontmatter,
	/**  First non-blank line after frontmatter, with the `[ ]`/`[x]` prefix stripped. */
	title: string,
	/**  `None` when first line lacks a checkbox; `Some(true)` for `[x]`, `Some(false)` for `[ ]`. */
	checkbox: boolean | null,
	body_markdown: string,
	/**
	 *  u32 (not u64) for specta BigInt-export compatibility — see
	 *  docs/2026521/Errors/2026-05-21-specta-bigint-export.md. Caps at 4 GB
	 *  which no realistic journal entry will hit.
	 */
	byte_size: number,
	mtime: string,
	/**
	 *  False when the YAML frontmatter failed to parse (the row is still cached
	 *  as a synthesized chore). Drives a ⚠ reliability badge (F7a).
	 */
	parse_ok: boolean,
	/**  Non-fatal parse warnings (missing tz offset, agent-as-string, bad op, …). */
	parse_warnings: string[],
};

export type JournalEntrySummary = {
	relative_path: string,
	workday: string,
	type: EntryType,
	slug: string,
	status: EntryStatus,
	difficulty: Difficulty | null,
	title: string,
	checkbox: boolean | null,
	session_id: string,
	agent_id: string,
	/**
	 *  The model the agent reported (frontmatter `agent.version`), e.g.
	 *  `"Opus 4.8"` / `"Gemini 3 Pro"`. `None` when not reported.
	 */
	agent_version: string | null,
	verified_by_user: boolean,
	created_at: string,
	updated_at: string | null,
	tags: string[],
	files_count: number,
	parse_ok: boolean,
	parse_warnings: string[],
};

export type JournalFrontmatter = {
	schema_version: number,
	type: EntryType,
	slug: string,
	status: EntryStatus,
	difficulty: Difficulty | null,
	created_at: string,
	updated_at: string | null,
	session_id: string,
	agent: AgentRef,
	/**  Two-letter ISO 639-1, e.g. `ko` or `en`. */
	language: string,
	verified_by_user: boolean,
	files_touched: FileTouched[],
	related: RelatedRef[],
	tags: string[],
};

/**
 *  The most recent commit's metadata + the files it touched. Powers the 변경
 *  diff 화면's "직전 커밋" baseline, shown when the working tree is clean so the
 *  screen isn't empty after a coding agent commits its work.
 */
export type LastCommitChanges = {
	sha: string,
	short_sha: string,
	subject: string,
	changes: GitChange[],
};

/**
 *  W4-PR5 — diff between the watcher's ndjson (index, ground truth) and
 *  the union of `files_touched[].path` from journal entries that name a
 *  given `session_id`. See `docs/major_update/oculpm/W4/PR5-compare-layers.md`.
 */
export type LayerComparison = {
	session_id: string,
	workday: string,
	/**
	 *  Distinct project-relative paths from `file_changes.ndjson` for this
	 *  session, after stripping forbidden + `**redacted/sensitive**:*` paths.
	 */
	index_files: string[],
	/**
	 *  Union of `files_touched[].path` across every journal entry that names
	 *  this session, after the same forbidden / redacted strip.
	 */
	journal_files: string[],
	matched: string[],
	/**  In the index but not the journal — likely *missing narrative*. */
	only_in_index: string[],
	/**  In the journal but not the index — likely *hallucinated path*. */
	only_in_journal: string[],
	mismatch_severity: Severity,
	/**
	 *  `|matched| / |union|`. `1.0` when both sets are empty (treated as
	 *  trivially in sync — no activity, nothing to disagree on).
	 */
	jaccard_index: number | null,
};

export type LocalDiffReindexReport = {
	indexed: string[],
	skipped: ReindexSkip[],
	elapsed_ms: number,
	embeddings_updated: number,
	ast_updated: number,
};

export type LockStateView = "healthy" | "held_by_other" | "recovered" | "uninitialized";

export type ManualEntryDraft = {
	type: EntryType,
	slug: string,
	title: string,
	difficulty: Difficulty | null,
	body_markdown: string,
	/**
	 *  `None` → use the active session if any, else fall back to a
	 *  `manual-<workday>-<HHMMSS>` sentinel id.
	 */
	session_id: string | null,
	files_touched: FileTouched[],
	/**  `None` → defaults to `planned`. Spec §3.1. */
	status: EntryStatus | null,
	tags: string[],
};

/**  An available master-template upgrade for a project. */
export type MasterUpgrade = {
	from_version: number,
	to_version: number,
};

export type Message = {
	role: Role,
	content: string,
};

export type OculpmAgentDrift = {
	project_id: number,
	agent_id: string,
	expected_hash: string,
	actual_hash: string,
};

export type OculpmAgentsTemplateChanged = {
	project_id: number,
	relative_path: string,
};

export type OculpmConfig = {
	schema_version: number,
	workday: WorkdayConfig,
	session: SessionConfig,
	git: GitConfig,
	watcher: WatcherConfig,
	agents: AgentsConfig,
};

export type OculpmFileChanged = {
	project_id: number,
	event: FileChangeEvent,
};

export type OculpmInitReport = {
	/**  Project-relative paths that were created. */
	created_dirs: string[],
	wrote_config: boolean,
	wrote_gitignore: boolean,
	lock_state: LockStateView,
};

export type OculpmIntegrityWarning = {
	project_id: number,
	warning: IntegrityWarning,
};

export type OculpmJournalAdded = {
	project_id: number,
	summary: JournalEntrySummary,
};

export type OculpmJournalPathChanged = {
	project_id: number,
	relative_path: string,
	op: FileOp,
};

export type OculpmJournalUpdated = {
	project_id: number,
	summary: JournalEntrySummary,
};

export type OculpmOverviewStats = {
	generated_at: string,
	window_days: number,
	/**  Every workday in the window (entries=0 days included as empty cells). */
	heatmap_cells: HeatmapCell[],
	difficulty_mix: DifficultyMix,
	agent_breakdown: AgentCount[],
	/**  Up to 50 unfinished entries, most recent first. */
	unfinished_entries: JournalEntrySummary[],
	/**  Up to 30 days of session aggregates, most recent first. */
	recent_sessions: SessionDailyAgg[],
};

export type OculpmSessionEnded = {
	project_id: number,
	session: Session,
};

export type OculpmSessionStarted = {
	project_id: number,
	session: Session,
};

export type OculpmStatus = {
	initialized: boolean,
	config_valid: boolean,
	lock_state: LockStateView,
	current_workday: string,
	watcher_state: WatcherStateView,
};

/**  Recent plan activity across all plans — drives the Today "계획 업데이트" block. */
export type PlanActivityDto = {
	plan_id: string,
	plan_title: string,
	item_id: string,
	item_title: string,
	agent_id: string,
	ts: string,
	from_status: string | null,
	to_status: string | null,
	note: string | null,
};

export type PlanDecisionDto = {
	decision_id: string,
	title: string,
	body: string,
	locked_at: string | null,
	agent_id: string | null,
	affects: string[],
};

export type PlanDetail = {
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
};

/**
 *  An edit applied by the app / in-app AI to a plan. External agents edit the
 *  `.md` directly per AGENTS.md (PR-PLN 2); this is the in-app equivalent.
 */
export type PlanEditOp = 
/**  Flip an existing item's status. */
{ kind: "set_status"; item_id: string; status: string } | 
/**  Add a new item under a phase (created if absent). */
{ kind: "add_item"; phase: string; title: string; item_id: string | null; status: string | null } | 
/**  Remove an existing item. */
{ kind: "remove_item"; item_id: string } | 
/**  Rename an existing item's title. */
{ kind: "rename_item"; item_id: string; title: string } | 
/**  Rename a phase heading (keeps its items + tracking id). */
{ kind: "rename_phase"; from: string; to: string } | 
/**  Remove a phase heading and every item under it. */
{ kind: "remove_phase"; phase: string } | 
/**  Reorder a phase among its siblings (`up = true` moves it earlier). */
{ kind: "move_phase"; phase: string; up: boolean };

export type PlanItemDto = {
	item_id: string,
	phase: string | null,
	title: string,
	status: string,
	order_idx: number,
	parent_item: string | null,
	note: string | null,
	last_agent: string | null,
	last_update: string | null,
	/**
	 *  Distinct journal entries linked to this item via the plan-log (the
	 *  agent's `일지` column). Drives the 📓 link + the progress suggestion.
	 */
	journal_refs: string[],
};

export type PlanItemUpdateDto = {
	ts: string,
	item_id: string,
	agent_id: string,
	from_status: string | null,
	to_status: string | null,
	journal_ref: string | null,
	note: string | null,
};

/**  A trackable phase (`## Heading {#id}`) — rollup status + who last touched it. */
export type PlanPhaseDto = {
	phase_id: string | null,
	name: string,
	status: string,
	progress: number | null,
	item_count: number,
	done_count: number,
	last_agent: string | null,
	last_update: string | null,
};

export type PlanSummary = {
	plan_id: string,
	title: string,
	status: string,
	owner_agent: string,
	progress: number | null,
	file_path: string,
	updated_at: string,
	item_count: number,
	done_count: number,
};

export type Project = {
	id: number,
	name: string,
	root_path: string,
	created_at: number,
};

export type ProjectBlueprint = {
	id: number,
	name: string,
	idea_text: string | null,
	target_users: string | null,
	stack_choice: string | null,
	folder_name: string | null,
	folder_path: string | null,
	seed_goals_json: string | null,
	wizard_step: number,
	created_at: number,
	updated_at: number,
};

export type ProjectOverview = {
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
};

export type ProjectStats = {
	files: number,
	chunks: number,
};

/**
 *  One entry in the user-configured failover chain (Settings → LLM → 폴백 체인).
 *  On a failed call the next entry is tried, in order.
 */
export type ProviderModel = {
	provider: string,
	model: string,
};

export type ReindexReport = {
	project_id: number,
	inserted: number,
	updated: number,
	deleted: number,
	skipped: number,
	completed_at: string,
};

export type ReindexSkip = {
	path: string,
	reason: ReindexSkipReason,
};

/**
 *  Per-path outcome surfaced to the UI. Skip reasons let the caller render a
 *  "(skipped: too large)" badge next to the path without re-running
 *  `walk_text_files` filters.
 */
export type ReindexSkipReason = { kind: "not_found" } | { kind: "read_failed"; error: string } | { kind: "upsert_failed"; error: string };

export type RelatedRef = {
	/**  Path relative to `.oculpm/journal/` (e.g. `20260522/Bugs/2050_bug_X.md`). */
	ref: string,
	/**  One of `blocks`, `blocked_by`, `followup`, `duplicate`. */
	kind: string,
};

export type Role = "system" | "user" | "assistant";

export type Session = {
	/**  `YYYYMMDD-NNN`. */
	id: string,
	started_at: string,
	ended_at: string | null,
	ended_reason: EndedReason | null,
	/**
	 *  u32 — caps at ~49 days of continuous active time. A single session
	 *  will never approach this.
	 */
	active_window_ms: number,
	file_event_count: number,
	files_unique: number,
	git_head_at_start: string | null,
	git_head_at_end: string | null,
	agent_label_guess: string | null,
	/**  Paths relative to `.oculpm/journal/<workday>/`. */
	linked_journal_entries: string[],
};

export type SessionConfig = {
	inactivity_timeout_minutes: number,
	auto_close_on_workday_boundary: boolean,
	auto_close_on_app_quit: boolean,
	crash_recovery_grace_minutes: number,
	/**
	 *  W4 dogfooding fix — minutes within which new activity after an
	 *  InactivityTimeout finalize will REOPEN the most recent
	 *  inactivity-closed session instead of starting a new one. Bounded by
	 *  today's workday (we never resurrect sessions across the workday
	 *  boundary). `0` disables resume entirely. Defaults to 15 minutes.
	 */
	session_resume_grace_minutes?: number,
};

export type SessionDailyAgg = {
	workday: string,
	session_count: number,
	total_active_seconds: number,
	files_unique: number,
	journal_entry_count: number,
	/**
	 *  `journal_entry_count / sessions_with_file_events`. `0.0` when no
	 *  sessions have file events (avoids NaN). UI shows as percentage.
	 */
	narrative_rate: number | null,
};

export type Severity = "ok" | "warning" | "critical";

export type Subtask = {
	id: number,
	goal_id: number,
	title: string,
	done: boolean,
	sort_order: number,
};

export type SymbolCall = {
	/**  Caller symbol in this file (None = file top-level). */
	from_symbol: string | null,
	kind: string,
	callee: string,
	/**  Resolved defining file path (None = external / unresolved). */
	target_path: string | null,
	estimated: boolean,
};

export type SymbolDef = {
	name: string,
	kind: string,
	start_line: number,
	end_line: number,
	start_byte: number,
	end_byte: number,
};

/**
 *  PR-R1b (A2) — a symbol hit from `search_symbols` (name LIKE over the AST
 *  symbol index). Unlike `SymbolDef` it carries the owning file path.
 */
export type SymbolSearchResult = {
	name: string,
	kind: string,
	file_path: string,
	start_line: number,
	end_line: number,
};

export type WatcherConfig = {
	ignore: string[],
	respect_gitignore: boolean,
	debounce_ms: number,
	batch_max_events: number,
};

export type WatcherStateView = "running" | "stopped" | "error";

export type WorkdayConfig = {
	/**  IANA timezone name (e.g. `Asia/Seoul`). */
	timezone: string,
	/**  `HH:MM` 24-hour. Late-night coders may use `03:00`. */
	day_starts_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

