// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	dbHealth: () => typedError<DbHealth, string>(__TAURI_INVOKE("db_health")),
	settingsSet: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("settings_set", { key, value })),
	settingsGet: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("settings_get", { key })),
	settingsGetAll: () => typedError<([string, string])[], string>(__TAURI_INVOKE("settings_get_all")),
	settingsSetMany: (entries: ([string, string])[]) => typedError<null, string>(__TAURI_INVOKE("settings_set_many", { entries })),
	appInfo: () => typedError<AppInfo, string>(__TAURI_INVOKE("app_info")),
	clearAllData: () => typedError<null, string>(__TAURI_INVOKE("clear_all_data")),
	secretSet: (name: string, value: string) => typedError<null, string>(__TAURI_INVOKE("secret_set", { name, value })),
	secretHas: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("secret_has", { name })),
	secretDelete: (name: string) => typedError<null, string>(__TAURI_INVOKE("secret_delete", { name })),
	/**
	 *  Verify the cached presence flag against the real keychain. Used when the
	 *  user explicitly asks ("the key isn't working" / "did I really save it?").
	 *  This DOES unlock the keychain.
	 */
	secretVerify: (name: string) => typedError<boolean, string>(__TAURI_INVOKE("secret_verify", { name })),
	chat: (provider: string, messages: Message[], options: ChatOptions, fallbacks: ProviderModel[]) => typedError<ChatResponse, string>(__TAURI_INVOKE("chat", { provider, messages, options, fallbacks })),
	chatStream: (provider: string, messages: Message[], options: ChatOptions, fallbacks: ProviderModel[], onEvent: Channel<ChatEvent>) => typedError<null, string>(__TAURI_INVOKE("chat_stream", { provider, messages, options, fallbacks, onEvent })),
	selectProjectFolder: () => typedError<string | null, string>(__TAURI_INVOKE("select_project_folder")),
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (name: string, rootPath: string) => typedError<number, string>(__TAURI_INVOKE("create_project", { name, rootPath })),
	deleteProject: (projectId: number, deleteOculpm: boolean, deleteAgentsMd: boolean) => typedError<null, string>(__TAURI_INVOKE("delete_project", { projectId, deleteOculpm, deleteAgentsMd })),
	renameProject: (projectId: number, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_project", { projectId, name })),
	projectStats: (projectId: number) => typedError<ProjectStats, string>(__TAURI_INVOKE("project_stats", { projectId })),
	indexProject: (projectId: number, onProgress: Channel<IndexProgress>) => typedError<IndexResult, string>(__TAURI_INVOKE("index_project", { projectId, onProgress })),
	searchChunks: (projectId: number, query: string, limit: number, includeDocs: boolean) => typedError<ChunkSearchResult[], string>(__TAURI_INVOKE("search_chunks", { projectId, query, limit, includeDocs })),
	searchText: (projectId: number, query: string, limit: number) => typedError<ChunkSearchResult[], string>(__TAURI_INVOKE("search_text", { projectId, query, limit })),
	searchSymbols: (projectId: number, query: string, limit: number) => typedError<SymbolSearchResult[], string>(__TAURI_INVOKE("search_symbols", { projectId, query, limit })),
	getFileSymbols: (fileId: number) => typedError<SymbolDef[], string>(__TAURI_INVOKE("get_file_symbols", { fileId })),
	getCodeGraph: (projectId: number, opts: GraphOpts) => typedError<CodeGraph, string>(__TAURI_INVOKE("get_code_graph", { projectId, opts })),
	getChangeImpact: (projectId: number, changedPaths: string[]) => typedError<ImpactReport, string>(__TAURI_INVOKE("get_change_impact", { projectId, changedPaths })),
	getFileCalls: (fileId: number) => typedError<SymbolCall[], string>(__TAURI_INVOKE("get_file_calls", { fileId })),
	clearProjectIndex: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("clear_project_index", { projectId })),
	/**  List the project's plans (summary + progress + done counts). */
	planList: (projectId: number) => typedError<PlanSummary[], string>(__TAURI_INVOKE("plan_list", { projectId })),
	/**
	 *  One plan's detail: items (with per-item last attribution), decisions, and
	 *  non-fatal parse warnings. `None` when the plan_id isn't found.
	 */
	planGet: (projectId: number, planId: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_get", { projectId, planId })),
	/**
	 *  Append-only attribution history for one item (who changed it, when,
	 *  from→to, linked journal).
	 */
	planItemHistory: (projectId: number, planId: string, itemId: string) => typedError<PlanItemUpdateDto[], string>(__TAURI_INVOKE("plan_item_history", { projectId, planId, itemId })),
	/**  Create a new empty plan (`.oculpm/planner/<slug>.md`) and return its summary. */
	planCreate: (projectId: number, title: string) => typedError<PlanSummary, string>(__TAURI_INVOKE("plan_create", { projectId, title })),
	/**
	 *  Apply an edit to a plan's `.md` SSOT: mutate the body (glyph / new item) and
	 *  append an attribution row to the plan-log, stamped with `agent_id`
	 *  (defaults to `user`). Returns the refreshed plan detail.
	 */
	planApplyEdit: (projectId: number, planId: string, op: PlanEditOp, agentId: string | null) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_apply_edit", { projectId, planId, op, agentId })),
	/**
	 *  Ask the configured in-app LLM to update item statuses from recent journal
	 *  activity. The model proposes `{item_id, status}` edits; we apply the valid,
	 *  changed ones via the same plan-log path, stamped `agent_id = inapp:<provider>`.
	 */
	planAiRefresh: (projectId: number, planId: string, provider: string, model: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_ai_refresh", { projectId, planId, provider, model })),
	/**  One-time import of legacy `goals`/`subtasks` into `_imported.md`. */
	planMigrateGoals: (projectId: number) => typedError<PlanSummary, string>(__TAURI_INVOKE("plan_migrate_goals", { projectId })),
	/**  Recent plan activity across all plans — Today's "계획 업데이트" block. */
	planRecentUpdates: (projectId: number, limit: number) => typedError<PlanActivityDto[], string>(__TAURI_INVOKE("plan_recent_updates", { projectId, limit })),
	/**
	 *  Set a plan's lifecycle status (`active` / `done` / `archived`). `done` and
	 *  `archived` LOCK the plan: `plan_apply_edit` / `plan_ai_refresh` refuse to
	 *  touch it and AGENTS.md tells external agents the same — so finished plans
	 *  stay frozen and work moves to a new plan (Planner #1). Returns refreshed
	 *  detail.
	 */
	planSetStatus: (projectId: number, planId: string, status: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_set_status", { projectId, planId, status })),
	/**
	 *  Rename a plan (frontmatter `title:`). The plan `id` / filename stay the same
	 *  so item attribution + references keep working. Returns refreshed detail.
	 */
	planRename: (projectId: number, planId: string, title: string) => typedError<{
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("plan_rename", { projectId, planId, title })),
	/**
	 *  Delete a plan: remove its `.oculpm/planner/<id>.md` file and drop the cache
	 *  rows (a full reproject from disk is the only cache writer, so listing after
	 *  the unlink cleans up). Works regardless of lock state.
	 */
	planDelete: (projectId: number, planId: string) => typedError<null, string>(__TAURI_INVOKE("plan_delete", { projectId, planId })),
	conversationCreate: (title: string, provider: string | null, model: string | null, projectId: number | null) => typedError<Conversation, string>(__TAURI_INVOKE("conversation_create", { title, provider, model, projectId })),
	conversationList: (projectId: number | null) => typedError<Conversation[], string>(__TAURI_INVOKE("conversation_list", { projectId })),
	conversationRename: (conversationId: number, title: string) => typedError<null, string>(__TAURI_INVOKE("conversation_rename", { conversationId, title })),
	conversationSetContext: (conversationId: number, provider: string | null, model: string | null, projectId: number | null) => typedError<null, string>(__TAURI_INVOKE("conversation_set_context", { conversationId, provider, model, projectId })),
	conversationDelete: (conversationId: number) => typedError<null, string>(__TAURI_INVOKE("conversation_delete", { conversationId })),
	chatMessageAppend: (conversationId: number, role: string, content: string, provider: string | null, model: string | null) => typedError<ChatMessage, string>(__TAURI_INVOKE("chat_message_append", { conversationId, role, content, provider, model })),
	chatMessageList: (conversationId: number) => typedError<ChatMessage[], string>(__TAURI_INVOKE("chat_message_list", { conversationId })),
	/**
	 *  Persist that the user applied the ActionProposalCard at `message_index`
	 *  inside `conversation_id`. Idempotent — re-recording just refreshes
	 *  `applied_at`. Replaces the old `localStorage[action_{conv}_{i}]="applied"`
	 *  pattern in `ChatPanel`.
	 */
	recordConversationAction: (conversationId: number, messageIndex: number, status: string | null) => typedError<ConversationAction, string>(__TAURI_INVOKE("record_conversation_action", { conversationId, messageIndex, status })),
	listConversationActions: (conversationId: number) => typedError<ConversationAction[], string>(__TAURI_INVOKE("list_conversation_actions", { conversationId })),
	openDevtools: () => typedError<null, string>(__TAURI_INVOKE("open_devtools")),
	openTerminalWindow: () => typedError<null, string>(__TAURI_INVOKE("open_terminal_window")),
	readProjectFile: (projectId: number, relPath: string) => typedError<string, string>(__TAURI_INVOKE("read_project_file", { projectId, relPath })),
	/**
	 *  Read an inclusive, 1-indexed line range from a project file. Backs the
	 *  symbol-search "펼쳐서 코드 보기" toggle — symbol hits carry only a line
	 *  range, so the UI lazily fetches the body on expand instead of bloating
	 *  every result with content. Out-of-range bounds clamp to the file.
	 */
	readFileRange: (projectId: number, relPath: string, startLine: number, endLine: number) => typedError<string, string>(__TAURI_INVOKE("read_file_range", { projectId, relPath, startLine, endLine })),
	/**  프로젝트 `docs/` 폴더를 마크다운 트리로 반환한다. 폴더가 없으면 `exists=false`. */
	docsTree: (projectId: number) => typedError<DocsTree, string>(__TAURI_INVOKE("docs_tree", { projectId })),
	/**  단일 문서의 마크다운 본문을 읽는다. `rel_path` 는 프로젝트 루트 기준 (`docs/...`). */
	docsRead: (projectId: number, relPath: string) => typedError<string, string>(__TAURI_INVOKE("docs_read", { projectId, relPath })),
	/**  문서가 참조하는 이미지를 base64 로 읽는다. `rel_path` 는 프로젝트 루트 기준. */
	docsAsset: (projectId: number, relPath: string) => typedError<DocsAsset, string>(__TAURI_INVOKE("docs_asset", { projectId, relPath })),
	/**
	 *  List the project's discussions (summary + problem preview + counts).
	 *  Recent-first.
	 */
	discussionList: (projectId: number) => typedError<DiscussionSummary[], string>(__TAURI_INVOKE("discussion_list", { projectId })),
	/**
	 *  One discussion's full detail: problem, candidate options, discussion log,
	 *  conclusion, next steps, attachments, resolution link, and non-fatal parse
	 *  warnings. `None` when the discussion_id isn't found.
	 */
	discussionGet: (projectId: number, discussionId: string) => typedError<{
	discussion: DiscussionSummary,
	problem: string,
	background: string,
	options: DiscussionOptionDto[],
	log: DiscussionLogDto[],
	conclusion: string,
	next_steps: DiscussionNextStepDto[],
	attachments: DiscussionAttachmentDto[],
	resolution_plan_id: string | null,
	resolution_decided_at: string | null,
	tags: string[],
	/**  Non-fatal parse warnings — surfaced so the UI never fails silently. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("discussion_get", { projectId, discussionId })),
	/**
	 *  Create a new discussion folder (`.oculpm/discussion/<slug>/discussion.md`)
	 *  with the section skeleton, returning its summary.
	 */
	discussionCreate: (projectId: number, title: string) => typedError<DiscussionSummary, string>(__TAURI_INVOKE("discussion_create", { projectId, title })),
	/**
	 *  Replace the discussion body (the `## …` sections). Frontmatter is preserved
	 *  and `updated` re-stamped. Rejected when the document is closed (status not
	 *  `open`) — the body is read-only after a discussion is resolved/archived.
	 */
	discussionWrite: (projectId: number, discussionId: string, bodyMd: string) => typedError<{
	discussion: DiscussionSummary,
	problem: string,
	background: string,
	options: DiscussionOptionDto[],
	log: DiscussionLogDto[],
	conclusion: string,
	next_steps: DiscussionNextStepDto[],
	attachments: DiscussionAttachmentDto[],
	resolution_plan_id: string | null,
	resolution_decided_at: string | null,
	tags: string[],
	/**  Non-fatal parse warnings — surfaced so the UI never fails silently. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("discussion_write", { projectId, discussionId, bodyMd })),
	/**
	 *  Read the raw (un-redacted) body markdown (everything after the frontmatter)
	 *  for the in-app editor. Unlike `discussion_get` (redacted projection for
	 *  display), this returns exactly what's on disk so a save round-trip is
	 *  lossless — the user is editing their own file. `discussion_write` saves it.
	 */
	discussionReadRaw: (projectId: number, discussionId: string) => typedError<string, string>(__TAURI_INVOKE("discussion_read_raw", { projectId, discussionId })),
	/**
	 *  Set a discussion's lifecycle status (`open` / `resolved` / `archived`).
	 *  `archived` moves the folder into `_archive/`; un-archiving moves it back.
	 */
	discussionSetStatus: (projectId: number, discussionId: string, status: string) => typedError<{
	discussion: DiscussionSummary,
	problem: string,
	background: string,
	options: DiscussionOptionDto[],
	log: DiscussionLogDto[],
	conclusion: string,
	next_steps: DiscussionNextStepDto[],
	attachments: DiscussionAttachmentDto[],
	resolution_plan_id: string | null,
	resolution_decided_at: string | null,
	tags: string[],
	/**  Non-fatal parse warnings — surfaced so the UI never fails silently. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("discussion_set_status", { projectId, discussionId, status })),
	/**
	 *  Rename a discussion (frontmatter `title:`). The `id` / folder stay the same
	 *  so references keep working.
	 */
	discussionRename: (projectId: number, discussionId: string, title: string) => typedError<{
	discussion: DiscussionSummary,
	problem: string,
	background: string,
	options: DiscussionOptionDto[],
	log: DiscussionLogDto[],
	conclusion: string,
	next_steps: DiscussionNextStepDto[],
	attachments: DiscussionAttachmentDto[],
	resolution_plan_id: string | null,
	resolution_decided_at: string | null,
	tags: string[],
	/**  Non-fatal parse warnings — surfaced so the UI never fails silently. */
	warnings: string[],
} | null, string>(__TAURI_INVOKE("discussion_rename", { projectId, discussionId, title })),
	/**
	 *  Delete a discussion: remove its folder (incl. attachments) and refresh the
	 *  cache (a full reproject from disk is the only cache writer).
	 */
	discussionDelete: (projectId: number, discussionId: string) => typedError<null, string>(__TAURI_INVOKE("discussion_delete", { projectId, discussionId })),
	/**
	 *  Copy an external file (known absolute path, e.g. a drag-drop) into the
	 *  discussion's `attachments/` sidecar. Returns the new `attachments/<file>`.
	 */
	discussionAttach: (projectId: number, discussionId: string, sourcePath: string) => typedError<string, string>(__TAURI_INVOKE("discussion_attach", { projectId, discussionId, sourcePath })),
	/**
	 *  Open a native file picker and attach the chosen file. Returns the new
	 *  `attachments/<file>` path, or `None` if the user cancelled.
	 */
	discussionAttachViaDialog: (projectId: number, discussionId: string) => typedError<string | null, string>(__TAURI_INVOKE("discussion_attach_via_dialog", { projectId, discussionId })),
	/**
	 *  Read an attachment as base64 + MIME for inline rendering. `rel_path` is the
	 *  `attachments/<file>` path from `discussion_get`.
	 */
	discussionAsset: (projectId: number, discussionId: string, relPath: string) => typedError<DiscussionAsset, string>(__TAURI_INVOKE("discussion_asset", { projectId, discussionId, relPath })),
	/**  Remove one attachment file. `rel_path` is `attachments/<file>`. */
	discussionDetach: (projectId: number, discussionId: string, relPath: string) => typedError<null, string>(__TAURI_INVOKE("discussion_detach", { projectId, discussionId, relPath })),
	/**
	 *  Promote a resolved discussion into a Planner plan: create a new
	 *  `.oculpm/planner/<id>.md` whose items are the discussion's `## 다음 단계`,
	 *  then mark the discussion `resolved` with a `resolution_ref` back-link. The
	 *  new plan_id is returned (the frontend navigates to it). LLM-free.
	 */
	discussionPromoteToPlan: (projectId: number, discussionId: string) => typedError<string, string>(__TAURI_INVOKE("discussion_promote_to_plan", { projectId, discussionId })),
	startPtySession: (sessionId: string, cwd: string, rows: number, cols: number) => typedError<null, string>(__TAURI_INVOKE("start_pty_session", { sessionId, cwd, rows, cols })),
	/**
	 *  살아있는 세션의 스크롤백 스냅샷을 반환한다 (없으면 None). 화면 재마운트가
	 *  `start` 대신 이걸 먼저 불러 세션을 이어받는다.
	 */
	attachPtySession: (sessionId: string) => typedError<{
	/**  지금까지의 스크롤백 (상한 내). xterm 에 그대로 write 해 리플레이한다. */
	text: string,
	/**  스냅샷에 포함된 마지막 청크의 seq — 이 값 이하의 라이브 이벤트는 중복. */
	seq: number,
} | null, string>(__TAURI_INVOKE("attach_pty_session", { sessionId })),
	writeToPty: (sessionId: string, data: string) => typedError<null, string>(__TAURI_INVOKE("write_to_pty", { sessionId, data })),
	resizePty: (sessionId: string, rows: number, cols: number) => typedError<null, string>(__TAURI_INVOKE("resize_pty", { sessionId, rows, cols })),
	killPtySession: (sessionId: string) => typedError<null, string>(__TAURI_INVOKE("kill_pty_session", { sessionId })),
	gitLog: (projectId: number, limit: number) => typedError<GitCommit[], string>(__TAURI_INVOKE("git_log", { projectId, limit })),
	gitGraph: (projectId: number, limit: number) => typedError<GitGraphCommit[], string>(__TAURI_INVOKE("git_graph", { projectId, limit })),
	gitStatus: (projectId: number) => typedError<GitRepoStatus, string>(__TAURI_INVOKE("git_status", { projectId })),
	/**  Lite-W6 PR5 — slim head + dirty-count wrapper for the Today mini git chip. */
	gitHeadStatusBrief: (projectId: number) => typedError<GitHeadStatusBrief, string>(__TAURI_INVOKE("git_head_status_brief", { projectId })),
	/**
	 *  Re-run the indexing pipeline for `paths` (relative to the project root).
	 *  Mirrors the per-file branch of `commands::project::index_project` so that
	 *  LocalDiffView can refresh a small set without re-scanning the whole tree.
	 */
	reindexPaths: (projectId: number, paths: string[]) => typedError<LocalDiffReindexReport, string>(__TAURI_INVOKE("reindex_paths", { projectId, paths })),
	/**
	 *  Hybrid diff: tries git first, falls back to the captured snapshot when git
	 *  can't help. Returns `SnapshotsUnavailable` only when neither baseline exists
	 *  — never bubbles `fatal: bad revision 'HEAD'` to the UI.
	 */
	computeDiff: (projectId: number, path: string, maxBytes: number, baseline: string | null) => typedError<DiffResult, string>(__TAURI_INVOKE("compute_diff", { projectId, path, maxBytes, baseline })),
	/**
	 *  PR6.6 — re-capture snapshots for the supplied paths from disk content.
	 *  Powers the LocalDiffView "비우기" action: after the user acknowledges a
	 *  batch of changes, the diff baselines are advanced so subsequent edits
	 *  show against the just-cleared state instead of the original index.
	 */
	resnapshotPaths: (projectId: number, paths: string[]) => typedError<number, string>(__TAURI_INVOKE("resnapshot_paths", { projectId, paths })),
	/**
	 *  Persistent uncommitted-change list for the 변경 diff 화면. Backed by
	 *  `git status` so it survives app restarts and project switches (the live
	 *  file-watcher buffer does neither). Non-git projects return an empty Vec and
	 *  the UI keeps using the watcher buffer + snapshot baselines.
	 */
	gitUncommittedChanges: (projectId: number) => typedError<GitChange[], string>(__TAURI_INVOKE("git_uncommitted_changes", { projectId })),
	/**
	 *  Files changed by the most recent commit, with its sha/subject. The 변경 diff
	 *  화면 shows these when the working tree is clean (e.g. the agent committed its
	 *  work) so the screen isn't empty. `None` for non-git / no-commit repos.
	 */
	gitLastCommitChanges: (projectId: number) => typedError<{
	sha: string,
	short_sha: string,
	subject: string,
	changes: GitChange[],
} | null, string>(__TAURI_INVOKE("git_last_commit_changes", { projectId })),
	openInEditor: (projectRoot: string, relPath: string, editorCmd: string) => typedError<null, string>(__TAURI_INVOKE("open_in_editor", { projectRoot, relPath, editorCmd })),
	/**
	 *  Open an http(s) URL in the user's default browser. Used by the Today commit
	 *  graph to jump to a commit on GitHub. We shell out to the OS opener
	 *  (`open` / `xdg-open` / `cmd start`) rather than the opener plugin so no
	 *  path/url scope config is needed (mirrors `oculpm_open_entry_in_editor`).
	 *  Only http/https is allowed — never a local path or arbitrary scheme.
	 */
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	getProjectOverview: (projectId: number) => typedError<{
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
} | null, string>(__TAURI_INVOKE("get_project_overview", { projectId })),
	generateProjectOverview: (projectId: number, provider: string, model: string) => typedError<ProjectOverview, string>(__TAURI_INVOKE("generate_project_overview", { projectId, provider, model })),
	/**
	 *  Returns `Some(new)` when the LLM was invoked, `None` when the cached
	 *  overview was still fresh enough to skip work.
	 */
	refreshProjectOverviewIfStale: (projectId: number, provider: string, model: string) => typedError<{
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
} | null, string>(__TAURI_INVOKE("refresh_project_overview_if_stale", { projectId, provider, model })),
	/**
	 *  Save a user-edited overview body. Setting `source_signature = None` is
	 *  load-bearing: the indexing hook checks for it and refuses to auto-regen
	 *  over manual edits (MASTER-GUIDE §4.2 "수동 편집 보호"). Identity and
	 *  stack_json are passed through unchanged from the caller — the frontend
	 *  editor lets users tweak the markdown body for now; richer per-section
	 *  edits land later.
	 */
	updateProjectOverview: (projectId: number, identity: string | null, stackJson: string | null, overviewMd: string) => typedError<ProjectOverview, string>(__TAURI_INVOKE("update_project_overview", { projectId, identity, stackJson, overviewMd })),
	dailyBrief: (projectId: number, dateUnix: number | null) => typedError<DailyBrief, string>(__TAURI_INVOKE("daily_brief", { projectId, dateUnix })),
	saveBlueprint: (id: number | null, name: string, ideaText: string | null, targetUsers: string | null, stackChoice: string | null, folderName: string | null, folderPath: string | null, seedGoalsJson: string | null, wizardStep: number) => typedError<ProjectBlueprint, string>(__TAURI_INVOKE("save_blueprint", { id, name, ideaText, targetUsers, stackChoice, folderName, folderPath, seedGoalsJson, wizardStep })),
	getBlueprint: (blueprintId: number) => typedError<ProjectBlueprint, string>(__TAURI_INVOKE("get_blueprint", { blueprintId })),
	listBlueprints: () => typedError<ProjectBlueprint[], string>(__TAURI_INVOKE("list_blueprints")),
	deleteBlueprint: (blueprintId: number) => typedError<null, string>(__TAURI_INVOKE("delete_blueprint", { blueprintId })),
	/**
	 *  Check if a CLI tool is available on the system PATH (or common install
	 *  locations). Returns availability, resolved path, and version string.
	 * 
	 *  The check uses `which`(Unix) / `where`(Windows) followed by a
	 *  `--version` probe. On failure, we scan well-known install directories
	 *  as a fallback (e.g. `~/.cargo/bin` for `cargo`).
	 */
	checkCliAvailable: (cliName: string) => typedError<CliCheckResult, string>(__TAURI_INVOKE("check_cli_available", { cliName })),
	/**
	 *  Create a new project from the Greenfield wizard.
	 * 
	 *  1. Creates the folder (if it doesn't exist)
	 *  2. Optionally runs a scaffold CLI (e.g. `pnpm create vite`)
	 *  3. Registers the project in the database via `create_project`
	 *  3b. (W3-PR10) Optionally initialises `.oculpm/` for the new project so
	 *      the user does not see the onboarding modal on first Today open.
	 *      Failure is **non-fatal**: the project row is already committed and
	 *      EmptyToday V1 provides a "활성화" recovery path.
	 *  4. Cleans up the blueprint (if any)
	 *  5. Returns the new project ID
	 */
	createGreenfieldProject: (name: string, rootPath: string, scaffoldCmd: string | null, scaffoldArgs: string[] | null, blueprintId: number | null, initOculpm: boolean) => typedError<GreenfieldResult, string>(__TAURI_INVOKE("create_greenfield_project", { name, rootPath, scaffoldCmd, scaffoldArgs, blueprintId, initOculpm })),
	/**
	 *  Ask the LLM to generate 3~5 initial goals for a newly created project
	 *  based on the user's idea and chosen tech stack. The goals are persisted
	 *  via `goal_create` and returned to the frontend for display in the wizard.
	 */
	generateSeedGoals: (projectId: number, ideaText: string, stackChoice: string, provider: string, model: string) => typedError<Goal[], string>(__TAURI_INVOKE("generate_seed_goals", { projectId, ideaText, stackChoice, provider, model })),
	/**
	 *  Idempotent project initialisation — creates `.oculpm/`, writes default
	 *  config, acquires the lock, and patches `.gitignore`. Returns a report of
	 *  what changed so the UI can surface "added 5 lines to .gitignore" etc.
	 */
	oculpmInit: (projectId: number) => typedError<OculpmInitReport, string>(__TAURI_INVOKE("oculpm_init", { projectId })),
	/**
	 *  Current `.oculpm/` status (initialised, lock, current workday, watcher).
	 *  Safe to call before init — returns a default uninitialised view.
	 */
	oculpmGetStatus: (projectId: number) => typedError<OculpmStatus, string>(__TAURI_INVOKE("oculpm_get_status", { projectId })),
	/**
	 *  Read the validated in-memory `OculpmConfig`. Errors if `oculpm_init` has
	 *  not been called for this project.
	 */
	oculpmGetConfig: (projectId: number) => typedError<OculpmConfig, string>(__TAURI_INVOKE("oculpm_get_config", { projectId })),
	/**
	 *  Validate + persist a new `OculpmConfig` (atomic write) and refresh the
	 *  in-memory `WorkdayResolver`. Rejects invalid tz / HH:MM without touching
	 *  disk.
	 */
	oculpmSetConfig: (projectId: number, newConfig: OculpmConfig) => typedError<null, string>(__TAURI_INVOKE("oculpm_set_config", { projectId, newConfig })),
	/**  Manually start a session. Idempotent — returns existing if already active. */
	oculpmStartSessionManual: (projectId: number) => typedError<{
	/**  `YYYYMMDD-NNN`. */
	id: string,
	started_at: string,
	ended_at: string | null,
	ended_reason: EndedReason | null,
	/**
	 *  u32 — caps at ~49 days of continuous active time. A single session
	 *  will never approach this.
	 */
	active_window_ms: number,
	file_event_count: number,
	files_unique: number,
	git_head_at_start: string | null,
	git_head_at_end: string | null,
	agent_label_guess: string | null,
	/**  Paths relative to `.oculpm/journal/<workday>/`. */
	linked_journal_entries: string[],
} | null, string>(__TAURI_INVOKE("oculpm_start_session_manual", { projectId })),
	/**  Manually end a session. `session_id` must match the active session. */
	oculpmEndSessionManual: (projectId: number, sessionId: string) => typedError<null, string>(__TAURI_INVOKE("oculpm_end_session_manual", { projectId, sessionId })),
	/**  List sessions for a workday. `workday = None` → today. */
	oculpmListSessions: (projectId: number, workday: string | null) => typedError<Session[], string>(__TAURI_INVOKE("oculpm_list_sessions", { projectId, workday })),
	/**  Get file change events for a workday, optionally filtered by session_id. */
	oculpmGetFileChanges: (projectId: number, workday: string, sessionId: string | null) => typedError<FileChangeEvent[], string>(__TAURI_INVOKE("oculpm_get_file_changes", { projectId, workday, sessionId })),
	/**  Start the filesystem watcher. Idempotent. Requires lock ownership. */
	oculpmWatcherStart: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("oculpm_watcher_start", { projectId })),
	/**  Stop the filesystem watcher. Idempotent. */
	oculpmWatcherStop: (projectId: number) => typedError<null, string>(__TAURI_INVOKE("oculpm_watcher_stop", { projectId })),
	/**
	 *  List cached journal entries for a workday (or today if None) with filters.
	 *  Returns `[]` for uninitialised projects so the UI can render EmptyToday
	 *  without a special-case error path.
	 */
	oculpmListJournalEntries: (projectId: number, workday: string | null, filters: {
	types: EntryType[],
	verified_only: boolean,
	/**
	 *  Reserved for W4 (LayerComparison). PR2 wires the column path but
	 *  `mismatch_only=true` returns no rows because no entry has been
	 *  flagged yet.
	 */
	mismatch_only: boolean,
	/**  `checkbox == Some(false)` OR `status != "done"`. */
	unfinished_only: boolean,
	search: string | null,
	/**  W5-PR6 — agent_id filter. Empty = no constraint (all agents). */
	agents?: string[],
	/**
	 *  W5-PR6 — difficulty filter. Empty = no constraint. Note the cache
	 *  column is nullable ("미지정"); difficulty filter therefore *cannot*
	 *  match the null bucket — that's a separate W6 toggle.
	 */
	difficulties?: Difficulty[],
} | null) => typedError<JournalEntrySummary[], string>(__TAURI_INVOKE("oculpm_list_journal_entries", { projectId, workday, filters })),
	/**
	 *  Get a single journal entry by relative path. Falls back to on-demand
	 *  disk read + cache upsert if the row is missing. Returns `None` only
	 *  when the file does not exist on disk either.
	 */
	oculpmGetJournalEntry: (projectId: number, relativePath: string) => typedError<{
	/**  `<workday>/<Category>/<file>.md` — relative to `.oculpm/journal/`. */
	relative_path: string,
	frontmatter: JournalFrontmatter,
	/**  First non-blank line after frontmatter, with the `[ ]`/`[x]` prefix stripped. */
	title: string,
	/**  `None` when first line lacks a checkbox; `Some(true)` for `[x]`, `Some(false)` for `[ ]`. */
	checkbox: boolean | null,
	body_markdown: string,
	/**
	 *  u32 (not u64) for specta BigInt-export compatibility — see
	 *  docs/2026521/Errors/2026-05-21-specta-bigint-export.md. Caps at 4 GB
	 *  which no realistic journal entry will hit.
	 */
	byte_size: number,
	mtime: string,
	/**
	 *  False when the YAML frontmatter failed to parse (the row is still cached
	 *  as a synthesized chore). Drives a ⚠ reliability badge (F7a).
	 */
	parse_ok: boolean,
	/**  Non-fatal parse warnings (missing tz offset, agent-as-string, bad op, …). */
	parse_warnings: string[],
} | null, string>(__TAURI_INVOKE("oculpm_get_journal_entry", { projectId, relativePath })),
	/**
	 *  Read the per-file diffs recorded for a journal entry at the moment it was
	 *  first indexed (see `oculpm::entry_diffs`). Returns `[]` when nothing was
	 *  captured — the entry predates the feature, the project isn't a git repo, or
	 *  it was written after committing — and the UI renders "기록된 변경 없음".
	 */
	oculpmGetEntryDiffs: (projectId: number, relativePath: string) => typedError<EntryFileDiff[], string>(__TAURI_INVOKE("oculpm_get_entry_diffs", { projectId, relativePath })),
	/**
	 *  Group the watcher's changed file paths by the journal entry that recorded
	 *  each, with the plan items linked to that entry (Dogfooding #3). Files no
	 *  entry recorded land in a trailing `entry_path: None` bucket.
	 */
	oculpmGroupChanges: (projectId: number, paths: string[]) => typedError<ChangeGroup[], string>(__TAURI_INVOKE("oculpm_group_changes", { projectId, paths })),
	/**
	 *  Toggle `verified_by_user` on a journal entry's frontmatter. Atomic
	 *  write-through: file is rewritten first, then the cache is upserted in
	 *  the same call so the UI sees the change immediately.
	 */
	oculpmSetJournalVerified: (projectId: number, relativePath: string, verified: boolean) => typedError<null, string>(__TAURI_INVOKE("oculpm_set_journal_verified", { projectId, relativePath, verified })),
	/**
	 *  v2 U7 — 커맨드 팔레트 엔티티 점프 ("go to anything"): 일지·플랜·플랜
	 *  항목·토의를 제목으로 통합 검색한다. SQLite 캐시만 읽는 저비용 경로
	 *  (타이핑 debounce 마다 호출됨).
	 */
	oculpmSearchEntities: (projectId: number, query: string, limit: number) => typedError<EntityHit[], string>(__TAURI_INVOKE("oculpm_search_entities", { projectId, query, limit })),
	/**
	 *  v2 U12 — 워크데이 집합의 일지 요약 + 오늘 bytes 합 + 미완 플랜 항목 +
	 *  총 일지 수를 IPC 1회에. 서버측 fan-in — SQL 비용은 기존과 동일하고
	 *  왕복(직렬화·스케줄링)만 제거된다.
	 */
	oculpmWorkdayBrief: (projectId: number, workdays: string[], bytesWorkday: string | null) => typedError<WorkdayBrief, string>(__TAURI_INVOKE("oculpm_workday_brief", { projectId, workdays, bytesWorkday })),
	/**
	 *  Rebuild the journal cache from disk. Drops every cached row for the
	 *  project and re-walks `.oculpm/journal/`. Use after manual sqlite
	 *  tampering or schema migration.
	 */
	oculpmReindexCache: (projectId: number) => typedError<ReindexReport, string>(__TAURI_INVOKE("oculpm_reindex_cache", { projectId })),
	/**
	 *  Write a manual journal entry from the user-authored draft. Validates
	 *  the slug (kebab-case ASCII, 1..=60 chars), resolves the session_id
	 *  (active session / draft override / sentinel), writes the file with
	 *  the spec's `<HHMM>_<type>_<slug>.md` naming, and returns the hydrated
	 *  `JournalEntry`. On filename collision the writer suffixes `__2`/`__3`.
	 */
	oculpmCreateManualEntry: (projectId: number, draft: ManualEntryDraft) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_create_manual_entry", { projectId, draft })),
	/**
	 *  Inline-edit one or both of `difficulty` / `status` on an existing entry.
	 *  Same write-through semantics as `oculpm_set_journal_verified` — atomic
	 *  file write then cache upsert — and returns the hydrated entry so the
	 *  frontend's optimistic UI can resync to truth without a second fetch.
	 * 
	 *  Argument shape: send `null` for a field to leave it unchanged. To clear
	 *  `difficulty`, send `Some(None)` (encoded over the wire as the JSON
	 *  `null` *inside* a present object key); the frontend wrapper handles
	 *  this distinction.
	 */
	oculpmUpdateEntryMeta: (projectId: number, relativePath: string, difficultyChange: {
	value: Difficulty | null,
} | null, status: "planned" | "in_progress" | "done" | "abandoned" | null) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_update_entry_meta", { projectId, relativePath, difficultyChange, status })),
	/**
	 *  F7a-B Unit B — apply the tz-offset coercion to the entry's on-disk
	 *  frontmatter once (explicit user action). Only timestamps are written; the
	 *  slug stays display-coerced (filename coupling). Returns the re-projected
	 *  entry so the UI can drop the "보정됨" tz note.
	 */
	oculpmCoerceEntryOnDisk: (projectId: number, relativePath: string) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_coerce_entry_on_disk", { projectId, relativePath })),
	/**
	 *  Re-render every adapter according to `config.agents.active`. Idempotent —
	 *  when nothing's changed since the last sync, every result is `unchanged`
	 *  and disk mtimes don't move. Called by:
	 *    - the Greenfield wizard right after init (W3-PR10)
	 *    - the OculpmSettings save (W4-PR7)
	 *    - the watcher's `.oculpm/agents/**` handler (master template edits)
	 */
	oculpmAgentsSyncActive: (projectId: number) => typedError<AgentSyncReport, string>(__TAURI_INVOKE("oculpm_agents_sync_active", { projectId })),
	/**
	 *  Read-only adapter heuristic. Used by Settings "감지" button + Greenfield
	 *  default active set.
	 */
	oculpmAgentsDetect: (projectId: number) => typedError<AgentDetection[], string>(__TAURI_INVOKE("oculpm_agents_detect", { projectId })),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — return the project's master template
	 *  text so the UI's "프롬프트 복사" action can paste it into a chat. Read-only;
	 *  does not touch any adapter files. Separates the *file sync* concern (which
	 *  `oculpm_agents_sync_active` already handles) from the *one-shot prompt
	 *  delivery* concern that the user actually wants when clicking "복사".
	 */
	oculpmAgentsGetMasterTemplate: (projectId: number) => typedError<string, string>(__TAURI_INVOKE("oculpm_agents_get_master_template", { projectId })),
	/**
	 *  Is a newer agent-rules master template available than the one on disk?
	 *  `None` = up-to-date. Surfaced as an "update" prompt on project open.
	 */
	oculpmAgentsCheckMasterUpgrade: (projectId: number) => typedError<{
	from_version: number,
	to_version: number,
} | null, string>(__TAURI_INVOKE("oculpm_agents_check_master_upgrade", { projectId })),
	/**
	 *  Upgrade the on-disk master to the embedded one + re-sync adapters (AGENTS.md
	 *  etc.). The previous master is backed up to `_template.md.bak`.
	 */
	oculpmAgentsApplyMasterUpgrade: (projectId: number) => typedError<AgentSyncReport, string>(__TAURI_INVOKE("oculpm_agents_apply_master_upgrade", { projectId })),
	/**
	 *  W4-PR5 — compare a session's index ndjson against the union of journal
	 *  `files_touched` paths. Returns matched / missing / hallucinated sets +
	 *  jaccard severity. (Lite-W6 PR3 retired the DiffVsNarrative UI; the
	 *  command is kept for backend introspection + potential future surfaces.)
	 */
	oculpmCompareLayers: (projectId: number, sessionId: string) => typedError<LayerComparison, string>(__TAURI_INVOKE("oculpm_compare_layers", { projectId, sessionId })),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — return the absolute path to the
	 *  directory holding the daily-rotated `oculpm.log.YYYY-MM-DD` files. Settings
	 *  uses this for the "로그 폴더 열기" button (delegates to opener plugin).
	 *  Returns `None` if the process started with file logging disabled (test
	 *  runs / unsupported platform).
	 */
	oculpmGetLogDir: () => typedError<string | null, string>(__TAURI_INVOKE("oculpm_get_log_dir")),
	/**
	 *  W4 dogfooding follow-up (2026-05-26) — bridge `console.*` calls from the
	 *  webview into the backend's `tracing` layers so the user only has to grab
	 *  **one** file when something breaks. The frontend wraps console.log/warn/
	 *  error in `setupOculpmLogBridge()` (App.tsx) and forwards every call here.
	 * 
	 *  We intentionally don't echo back to the webview; the webview already
	 *  printed the original line in DevTools. We just want it in `oculpm.log`.
	 */
	oculpmLog: (level: string, target: string, message: string) => __TAURI_INVOKE<void>("oculpm_log", { level, target, message }),
	/**
	 *  W4 dogfooding (2026-05-27) — overwrite the body markdown of an existing
	 *  journal entry. Frontmatter is preserved verbatim. Returns the hydrated
	 *  entry so the UI can resync without a second fetch.
	 */
	oculpmUpdateEntryBody: (projectId: number, relativePath: string, bodyMarkdown: string) => typedError<JournalEntry, string>(__TAURI_INVOKE("oculpm_update_entry_body", { projectId, relativePath, bodyMarkdown })),
	/**
	 *  W4 dogfooding (2026-05-27) — open a journal entry's `.md` file with the
	 *  OS default app. The opener plugin's path-glob scope keeps rejecting
	 *  project-local paths (3 dogfooding regressions); this command resolves the
	 *  absolute path inside the backend and invokes `open` / `xdg-open` /
	 *  `cmd /c start` directly, sidestepping the scope check entirely.
	 */
	oculpmOpenEntryInEditor: (projectId: number, relativePath: string) => typedError<null, string>(__TAURI_INVOKE("oculpm_open_entry_in_editor", { projectId, relativePath })),
	/**
	 *  Single-shot fetch of every Overview widget. `window_days` clamps to
	 *  1..=365 inside the manager — the modal-facing default is 90 (heatmap).
	 */
	oculpmOverviewStats: (projectId: number, windowDays: number) => typedError<OculpmOverviewStats, string>(__TAURI_INVOKE("oculpm_overview_stats", { projectId, windowDays })),
	/**
	 *  Synthesise one journal entry per recent git commit (cold-start backfill).
	 *  Idempotent: re-running only adds commits not seen before. `max_commits`
	 *  caps the scan (clamped 1..=2000 in the manager).
	 */
	oculpmBackfillFromGit: (projectId: number, maxCommits: number) => typedError<BackfillReport, string>(__TAURI_INVOKE("oculpm_backfill_from_git", { projectId, maxCommits })),
	/**
	 *  Deterministic signals for a workday range — no LLM. `since`/`until` are
	 *  inclusive "YYYYMMDD".
	 */
	retroSignals: (projectId: number, since: string, until: string) => typedError<RetroSignals, string>(__TAURI_INVOKE("retro_signals", { projectId, since, until })),
	/**
	 *  기간의 일지 + 활성 플랜을 스탠드업/PR 본문/주간 보고 마크다운으로 만든다.
	 *  provider/model 이 없거나 LLM 이 실패하면 결정적 마크다운으로 폴백한다
	 *  (`used_llm`/`note` 로 구분) — API 키 없이도 항상 동작.
	 */
	oculpmGenerateSummary: (projectId: number, since: string, until: string, style: SummaryStyle, provider: string | null, model: string | null) => typedError<GeneratedSummary, string>(__TAURI_INVOKE("oculpm_generate_summary", { projectId, since, until, style, provider, model })),
	/**  The cached retro narrative for a range, or `None` if never generated. */
	getRetro: (projectId: number, rangeKey: string) => typedError<{
	project_id: number,
	/**  "YYYYMMDD..YYYYMMDD" (inclusive workday range). */
	range_key: string,
	signature: string,
	retro_md: string,
	generated_at: number,
	generated_by_model: string | null,
} | null, string>(__TAURI_INVOKE("get_retro", { projectId, rangeKey })),
	/**
	 *  Run the configured LLM over the range's signals and cache a Korean retro.
	 *  Always regenerates (the user clicked "생성") — the signature is stored so the
	 *  UI can later tell whether the data has drifted.
	 */
	generateRetro: (projectId: number, since: string, until: string, provider: string, model: string) => typedError<RetroInsight, string>(__TAURI_INVOKE("generate_retro", { projectId, since, until, provider, model })),
	/**
	 *  PR-CI6 (EDD-lite) — 프로젝트 루트 `EVALS.md` 의 `## 기록` 표를 점수 추이로.
	 *  파일이 없으면 `None` (UI 는 섹션을 그리지 않는다). 기간과 무관 — 문서
	 *  전체가 신호다.
	 */
	evalSignals: (projectId: number) => typedError<{
	/**  날짜 오름차순 (동일 날짜는 문서 순서 유지), 최근 200건. */
	records: EvalRecord[],
	/**  등장한 스위트명 (등장 순서). */
	suites: string[],
} | null, string>(__TAURI_INVOKE("eval_signals", { projectId })),
	/**
	 *  Render the range digest, open a native save dialog (default `.md` name), and
	 *  write the file. Returns the saved path, or `None` if the user cancelled.
	 *  `since`/`until` are inclusive "YYYYMMDD" workdays.
	 */
	oculpmExportDigest: (projectId: number, since: string, until: string) => typedError<string | null, string>(__TAURI_INVOKE("oculpm_export_digest", { projectId, since, until })),
	/**  프로젝트+전역 스킬을 한 번에 나열한다. 스킬 폴더가 없으면 빈 목록. */
	skillsList: (projectId: number) => typedError<SkillsOverview, string>(__TAURI_INVOKE("skills_list", { projectId })),
	/**  단일 스킬의 SKILL.md 원문과 보조 파일 목록을 읽는다. */
	skillsRead: (projectId: number, scope: SkillScope, dirName: string) => typedError<SkillDetail, string>(__TAURI_INVOKE("skills_read", { projectId, scope, dirName })),
	/**
	 *  SKILL.md 를 저장한다. `create=true` 면 새 폴더 생성(중복 거부),
	 *  `false` 면 기존 스킬(비활성 포함)의 본문 교체.
	 */
	skillsSave: (projectId: number, scope: SkillScope, dirName: string, content: string, create: boolean) => typedError<SkillEntry, string>(__TAURI_INVOKE("skills_save", { projectId, scope, dirName, content, create })),
	/**  스킬 폴더를 통째로 삭제한다 (보조 파일 포함, 복구 불가). */
	skillsDelete: (projectId: number, scope: SkillScope, dirName: string) => typedError<null, string>(__TAURI_INVOKE("skills_delete", { projectId, scope, dirName })),
	/**  스킬 활성/비활성 토글 — `<skills>/` ↔ `<skills>/.disabled/` 이동. */
	skillsSetEnabled: (projectId: number, scope: SkillScope, dirName: string, enabled: boolean) => typedError<SkillEntry, string>(__TAURI_INVOKE("skills_set_enabled", { projectId, scope, dirName, enabled })),
	/**
	 *  스킬을 다른 스코프로 복사한다 (프로젝트 ↔ 전역). 대상에 같은 이름이 있으면 거부.
	 *  복사본은 항상 활성 위치에 놓인다.
	 */
	skillsCopy: (projectId: number, fromScope: SkillScope, toScope: SkillScope, dirName: string) => typedError<SkillEntry, string>(__TAURI_INVOKE("skills_copy", { projectId, fromScope, toScope, dirName })),
	/**  CLAUDE.md 슬롯 + 프로젝트/전역 규칙을 한 번에 나열한다. */
	rulesList: (projectId: number) => typedError<RulesOverview, string>(__TAURI_INVOKE("rules_list", { projectId })),
	/**  단일 규칙/CLAUDE.md 파일 원문을 읽는다. */
	rulesRead: (projectId: number, scope: RuleScope, relPath: string) => typedError<RuleDetail, string>(__TAURI_INVOKE("rules_read", { projectId, scope, relPath })),
	/**
	 *  저장 (`create=true` 는 신규 — 기존 파일 거부). 프로젝트 규칙이고 번역이
	 *  켜져 있으면 Cursor 미러를 병행 갱신해 결과를 함께 돌려준다.
	 */
	rulesSave: (projectId: number, scope: RuleScope, relPath: string, content: string, create: boolean) => typedError<RuleSaveOutcome, string>(__TAURI_INVOKE("rules_save", { projectId, scope, relPath, content, create })),
	/**
	 *  규칙 삭제 (`.claude/rules/**` 만 — CLAUDE.md 계열은 구조적으로 거부).
	 *  프로젝트 규칙이면 마커 미러도 함께 걷어낸다 (옵인 여부 무관 — 잔재 제거).
	 */
	rulesDelete: (projectId: number, scope: RuleScope, relPath: string) => typedError<{
	/**  번역 타깃 id (v1: "cursor"). */
	target: string,
	/**  원본 rel_path. */
	source_rel: string,
	/**  "written" | "unchanged" | "removed" | "conflict". */
	action: string,
	/**  미러 파일의 프로젝트 상대 경로. */
	mirror_rel: string,
} | null, string>(__TAURI_INVOKE("rules_delete", { projectId, scope, relPath })),
	/**  config 기준으로 미러 전체를 화해시킨다 (토글 직후 + 수동 재동기화). */
	rulesSyncTranslations: (projectId: number) => typedError<MirrorWriteResult[], string>(__TAURI_INVOKE("rules_sync_translations", { projectId })),
	/**
	 *  기간 내 반복 실패 클러스터(규칙 후보)를 결정적으로 뽑는다 — LLM 없음.
	 *  이미 규칙이 덮는 영역·승격된 후보(promoted-from 마커)는 제외된다.
	 */
	ruleCandidates: (projectId: number, since: string, until: string) => typedError<RuleCandidate[], string>(__TAURI_INVOKE("rule_candidates", { projectId, since, until })),
	/**
	 *  후보 하나의 증거(일지 본문 redact 발췌 + entry_diffs 변경 파일)로 LLM 규칙
	 *  초안을 만든다. 과금 호출 — 사용자가 버튼으로만 트리거한다. 파일은 쓰지
	 *  않는다 (저장은 프런트의 `rules_save` 승인 경로 전담).
	 */
	ruleDraftGenerate: (projectId: number, since: string, until: string, candidateKey: string, provider: string, model: string) => typedError<RuleDraft, string>(__TAURI_INVOKE("rule_draft_generate", { projectId, since, until, candidateKey, provider, model })),
	/**  현재 설치 상태 조회 (쓰기 없음). */
	claudeHooksStatus: (projectId: number) => typedError<ClaudeHooksStatus, string>(__TAURI_INVOKE("claude_hooks_status", { projectId })),
	/**  훅 설치 (멱등 — 드리프트 복구도 이걸 다시 부르면 된다). */
	claudeHooksInstall: (projectId: number) => typedError<ClaudeHooksStatus, string>(__TAURI_INVOKE("claude_hooks_install", { projectId })),
	/**  훅 제거 (우리 서명 엔트리만 — 사용자 훅·인박스 파일은 보존). */
	claudeHooksUninstall: (projectId: number) => typedError<ClaudeHooksStatus, string>(__TAURI_INVOKE("claude_hooks_uninstall", { projectId })),
	mcpStatus: (projectId: number) => typedError<McpRegistrationStatus, string>(__TAURI_INVOKE("mcp_status", { projectId })),
	mcpRegister: (projectId: number) => typedError<McpRegistrationStatus, string>(__TAURI_INVOKE("mcp_register", { projectId })),
	mcpUnregister: (projectId: number) => typedError<McpRegistrationStatus, string>(__TAURI_INVOKE("mcp_unregister", { projectId })),
	mcpDesktopStatus: (projectId: number) => typedError<DesktopRegistrationStatus, string>(__TAURI_INVOKE("mcp_desktop_status", { projectId })),
	mcpDesktopRegister: (projectId: number) => typedError<DesktopRegistrationStatus, string>(__TAURI_INVOKE("mcp_desktop_register", { projectId })),
	mcpDesktopUnregister: (projectId: number) => typedError<DesktopRegistrationStatus, string>(__TAURI_INVOKE("mcp_desktop_unregister", { projectId })),
	/**  토큰/부모 페이지 설정 상태 (네트워크 없음). */
	notionStatus: () => typedError<NotionStatus, string>(__TAURI_INVOKE("notion_status")),
	/**
	 *  입력한 토큰을 실검증한다 (`GET /users/me`) — 성공 시 통합(봇) 이름.
	 *  저장은 하지 않는다: UI 가 검증 성공 후 기존 `secret_set` 으로 키체인에 쓴다.
	 */
	notionVerifyToken: (token: string) => typedError<string, string>(__TAURI_INVOKE("notion_verify_token", { token })),
	/**
	 *  부모 페이지 설정 — URL/ID 를 정규화해 저장한다. 빈 입력은 해제.
	 *  반환: 저장된 정규화 id (해제 시 None).
	 */
	notionSetParent: (input: string) => typedError<string | null, string>(__TAURI_INVOKE("notion_set_parent", { input })),
	/**  마크다운을 부모 페이지 아래 새 Notion 페이지로 내보낸다 — 성공 시 페이지 URL. */
	notionExport: (projectId: number, title: string, markdown: string) => typedError<string, string>(__TAURI_INVOKE("notion_export", { projectId, title, markdown })),
	trayOpenMain: (nav: {
	view: string,
	project_id: number | null,
	/**  `.oculpm/` 상대 일지 경로 — 있으면 해당 일지를 연다. */
	entry_path: string | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("tray_open_main", { nav })),
	trayHidePopover: () => typedError<null, string>(__TAURI_INVOKE("tray_hide_popover")),
	/**  설정 UI 가 토글 저장 직후 호출 — 아이콘 표시/숨김 즉시 반영. */
	trayApplySettings: () => typedError<null, string>(__TAURI_INVOKE("tray_apply_settings")),
};

/** Events */
export const events = {
	oculpmAgentDrift: makeEvent<OculpmAgentDrift>("oculpm-agent-drift"),
	oculpmAgentsTemplateChanged: makeEvent<OculpmAgentsTemplateChanged>("oculpm-agents-template-changed"),
	oculpmFileChanged: makeEvent<OculpmFileChanged>("oculpm-file-changed"),
	oculpmIntegrityWarning: makeEvent<OculpmIntegrityWarning>("oculpm-integrity-warning"),
	oculpmJournalAdded: makeEvent<OculpmJournalAdded>("oculpm-journal-added"),
	oculpmJournalPathChanged: makeEvent<OculpmJournalPathChanged>("oculpm-journal-path-changed"),
	oculpmJournalUpdated: makeEvent<OculpmJournalUpdated>("oculpm-journal-updated"),
	oculpmPlanReconciled: makeEvent<OculpmPlanReconciled>("oculpm-plan-reconciled"),
	oculpmSessionEnded: makeEvent<OculpmSessionEnded>("oculpm-session-ended"),
	oculpmSessionStarted: makeEvent<OculpmSessionStarted>("oculpm-session-started"),
	trayNavigate: makeEvent<TrayNavigate>("tray-navigate"),
};

/* Types */
export type AgentCount = {
	agent_id: string,
	entry_count: number,
	/**  `entry_count / total_entries`. `0.0` when no entries. */
	share: number | null,
};

export type AgentDetection = {
	agent_id: string,
	confidence: DetectConfidence,
	adapter_path_exists: boolean,
	adjacent_marker_exists: boolean,
};

export type AgentRef = {
	/**
	 *  e.g. `claude-code`, `cursor`, `antigravity`, `gemini-cli`, `pi`,
	 *  `windsurf`, `copilot`, `codex`, `aider`, `cline`, `zed`, `manual`
	 *  (자유 문자열 — 미지의 id 도 저장은 된다).
	 */
	id: string,
	/**  The model the agent ran on, e.g. `"Opus 4.8"` / `"Gemini 3 Pro"`. */
	version: string | null,
};

export type AgentSyncReport = {
	results: AgentSyncResult[],
};

export type AgentSyncResult = {
	id: string,
	/**  One of `inserted`, `updated`, `unchanged`, `removed`, `error`. */
	action: string,
	error: string | null,
	/**
	 *  blake3 hex of the bytes we own on disk after this sync. For
	 *  `Overwrite` adapters it's the file hash; for `ManagedBlock` adapters
	 *  it's the hash of the inner block content (between the markers). Used
	 *  by W4-PR4 to seed the drift comparator. `None` when the adapter was
	 *  removed / errored / left untouched without a file present.
	 */
	last_hash: string | null,
};

export type AgentsConfig = {
	/**
	 *  Subset of `config::KNOWN_AGENT_IDS` — `agents-md` + 도구별 어댑터
	 *  (claude-code/cursor/antigravity/gemini-cli/windsurf/copilot/aider/cline/zed).
	 */
	active: string[],
	auto_detect_on_open: boolean,
	auto_sync_adapters: boolean,
	/**
	 *  F1 — when on, the watcher reconciles the single active plan against each
	 *  newly-written journal entry via a background LLM call (`auto:<provider>`
	 *  attribution). Opt-in (default `false`): it triggers automatic, billable
	 *  LLM requests that send journal/plan text to the configured provider.
	 *  `#[serde(default)]` so pre-F1 `config.toml` files parse to `false`.
	 */
	auto_reconcile?: boolean,
	/**
	 *  PR-CI1 — when on, a hook-detected Claude Code session end (AgentExit)
	 *  triggers a background LLM summary of the session transcript into ONE
	 *  journal draft (skipped if the agent wrote its own entry). Opt-in
	 *  (default `false`): billable, and sends transcript excerpts to the
	 *  configured provider.
	 */
	auto_journal_draft?: boolean,
	/**
	 *  PR-CI3 — 규칙 크로스툴 번역 타깃 (`rules::TRANSLATE_TARGETS` 의 부분집합,
	 *  v1: "cursor"). 켜져 있으면 `.claude/rules/*.md` 저장 시 해당 도구의
	 *  규칙 파일로 병행 배포한다. `#[serde(default)]` 라 기존 config 는 빈
	 *  배열(off)로 파싱된다.
	 */
	rules_translate?: string[],
};

export type AppInfo = {
	db_path: string,
	app_data_dir: string,
	secrets_store: string,
	version: string,
};

/**
 *  Result of a git-history backfill (F5): one synthesised journal entry per
 *  commit. `skipped` counts commits already backfilled (idempotent re-runs).
 */
export type BackfillReport = {
	project_id: number,
	scanned: number,
	created: number,
	skipped: number,
};

/**
 *  A group of changed files attributed to one journal entry (Dogfooding #3).
 *  `entry_path == None` is the trailing "미기록 변경" bucket for files no
 *  journal entry recorded.
 */
export type ChangeGroup = {
	entry_path: string | null,
	entry_title: string | null,
	entry_type: string | null,
	created_at: string | null,
	plan_refs: ChangePlanRef[],
	files: string[],
};

/**
 *  One plan item linked (via the plan-log `journal_ref`) to a changed-file
 *  group's journal entry. Dogfooding #3 — surfaces "어떤 plan 에서" in the diff.
 */
export type ChangePlanRef = {
	plan_id: string,
	plan_title: string,
	item_title: string,
};

export type ChatEvent = { kind: "delta"; text: string } | { kind: "done" } | { kind: "error"; message: string };

export type ChatMessage = {
	id: number,
	conversation_id: number,
	role: string,
	content: string,
	provider: string | null,
	model: string | null,
	created_at: number,
};

export type ChatOptions = {
	model: string,
	temperature: number | null,
	max_tokens: number | null,
};

export type ChatResponse = {
	content: string,
	model: string,
	provider: string,
};

export type ChunkSearchResult = {
	chunk_id: number,
	file_path: string,
	start_line: number,
	end_line: number,
	content: string,
	distance: number | null,
};

export type ClaudeHooksStatus = {
	/**  3개 이벤트 전부에 우리 엔트리가 있다. */
	installed: boolean,
	/**  일부 이벤트에만 있다 (외부 편집으로 인한 드리프트 — 재설치 권장). */
	partial: boolean,
	/**  우리 것 아닌 훅 엔트리도 존재한다 (정보 표시용 — 건드리지 않음). */
	foreign_hooks: boolean,
	/**  `.claude/settings.local.json` 절대경로 (UI "파일 열기"용). */
	settings_path: string,
	/**
	 *  인박스 파일 현재 크기 (0 = 없음). 성장 관찰용. u32 saturating —
	 *  specta 가 u64(BigInt) 내보내기를 금지하고, 4GiB 넘는 인박스는 표시
	 *  정밀도가 무의미하다.
	 */
	inbox_bytes: number,
};

export type CliCheckResult = {
	available: boolean,
	cli_name: string,
	path: string | null,
	version: string | null,
};

export type CodeGraph = {
	nodes: GraphNodeDto[],
	edges: GraphEdgeDto[],
};

export type Conversation = {
	id: number,
	title: string,
	provider: string | null,
	model: string | null,
	project_id: number | null,
	created_at: number,
	updated_at: number,
	last_message_at: number | null,
};

export type ConversationAction = {
	id: number,
	conversation_id: number,
	message_index: number,
	status: string,
	applied_at: number,
};

/**
 *  Structured payload backing the Today screen. The frontend formats the
 *  numbers; we just join the underlying tables in a single round trip.
 * 
 *  `date_unix` is the local-day start (00:00) for which the brief was built.
 *  Callers can request any day, defaulting to "today" by passing `None`.
 * 
 *  Lite-W6 PR4: the changelog-derived fields were retired. The DTO shape
 *  is kept (with empty/zero placeholders) until the legacy DailyBrief
 *  view in TodayScreen is removed in a later PR; today's authoritative
 *  activity source is the journal entries rendered by TimelineView.
 */
export type DailyBrief = {
	date_unix: number,
	/**  Top 3 active goals — already ordered by priority then due_date. */
	focus_goals: Goal[],
	/**
	 *  Goals whose `updated_at` falls inside the requested day AND that are
	 *  marked completed. The "what did I finish" column.
	 */
	completed_today: Goal[],
};

export type DbHealth = {
	sqlite_version: string,
	vec_version: string,
	schema_version: number,
	path: string,
};

export type DesktopRegistrationStatus = {
	/**  설정 폴더가 존재한다 — Claude Desktop 설치 추정 근거. */
	installed: boolean,
	/**  이 프로젝트의 서버 엔트리가 등록되어 있다. */
	registered: boolean,
	config_path: string,
	/**  이 프로젝트가 쓰는 서버 키 (`oculpm-<폴더명>`). */
	server_key: string,
	/**  oculpm 아닌 서버 정의 수 (정보 표시용 — 건드리지 않음). */
	foreign_servers: number,
};

export type DetectConfidence = 
/**
 *  The adapter path itself exists — either we wrote it before, or a user
 *  (or another tool) is already aware of the adapter.
 */
"present" | 
/**
 *  An adjacent marker (`.cursor/`, `.claude/`, `.agent/`, `.gemini/`)
 *  exists but the adapter path doesn't — the user clearly uses this LLM
 *  even if our adapter isn't installed yet.
 */
"likely" | 
/**  No signal at all. */
"unknown";

export type DiffResult = {
	path: string,
	source: DiffSource,
};

export type DiffSource = 
/**  `git diff HEAD -- <path>` output. Empty `patch` = no diff. */
{ source: "git"; patch: string } | 
/**
 *  PR6.6 — snapshot vs disk unified-diff. Used when the git path can't
 *  serve a baseline: fresh repo (HEAD-less), non-git project, or git
 *  returned an empty patch but the file changed on disk after indexing.
 */
{ source: "snapshot"; patch: string } | 
/**
 *  The file has neither a git baseline nor a captured snapshot. UI prompts
 *  the user to run a partial reindex first.
 */
{ source: "snapshots_unavailable" };

export type Difficulty = "superhigh" | "high" | "medium" | "low" | "verylow";

/**
 *  Wire wrapper so the frontend can express "set difficulty to None" vs
 *  "leave difficulty alone". Two-step Option unfolds to:
 *    - omitted / null → `None` (leave alone)
 *    - `{ value: null }` → `Some(None)` (clear)
 *    - `{ value: "high" }` → `Some(Some(High))` (set)
 */
export type DifficultyChange = {
	value: Difficulty | null,
};

export type DifficultyMix = {
	verylow: number,
	low: number,
	medium: number,
	high: number,
	superhigh: number,
	/**  Entries that didn't specify a difficulty in frontmatter. */
	null_count: number,
};

/**
 *  An attachment's bytes for inline rendering — base64 + MIME, assembled into a
 *  `data:` URI by the frontend (mirrors `DocsAsset`).
 */
export type DiscussionAsset = {
	mime: string,
	base64: string,
};

export type DiscussionAttachmentDto = {
	rel_path: string,
	kind: string,
};

export type DiscussionDetail = {
	discussion: DiscussionSummary,
	problem: string,
	background: string,
	options: DiscussionOptionDto[],
	log: DiscussionLogDto[],
	conclusion: string,
	next_steps: DiscussionNextStepDto[],
	attachments: DiscussionAttachmentDto[],
	resolution_plan_id: string | null,
	resolution_decided_at: string | null,
	tags: string[],
	/**  Non-fatal parse warnings — surfaced so the UI never fails silently. */
	warnings: string[],
};

export type DiscussionLogDto = {
	ts: string,
	author: string,
	body: string,
};

export type DiscussionNextStepDto = {
	step_id: string,
	title: string,
	done: boolean,
	order_idx: number,
};

export type DiscussionOptionDto = {
	option_id: string,
	title: string,
	body: string,
	order_idx: number,
};

export type DiscussionSummary = {
	discussion_id: string,
	title: string,
	status: string,
	owner: string,
	/**  First line of the problem statement, truncated — for the list preview. */
	problem_preview: string,
	option_count: number,
	next_step_count: number,
	resolution_plan_id: string | null,
	file_path: string,
	created_at: string,
	updated_at: string,
};

/**  `docs_asset` 응답 — 이미지 바이트를 base64 + MIME 으로. 프런트는 `data:` URI 로 조립한다. */
export type DocsAsset = {
	mime: string,
	base64: string,
};

/**  `docs_tree` 응답. `exists=false` 면 프로젝트에 `docs/` 폴더가 없다 (빈 상태 UI). */
export type DocsTree = {
	exists: boolean,
	nodes: DocsTreeNode[],
};

/**
 *  docs 트리 한 노드. `relative_path` 는 **프로젝트 루트 기준** 슬래시 경로
 *  (예: `docs/graph-upgrade/00-master-plan.md`) — 그대로 `docs_read`/`docs_asset` 인자로 쓴다.
 */
export type DocsTreeNode = {
	name: string,
	relative_path: string,
	is_dir: boolean,
	children: DocsTreeNode[],
};

/**
 *  A file where effort concentrated, annotated with its graph fan-out so the
 *  retro can say "time went into a high-fan-out core module" with evidence.
 */
export type EffortHotspot = {
	path: string,
	/**  Distinct journal entries that touched it in the range. */
	touch_count: number,
	/**
	 *  Files that (transitively) import it (`get_change_impact` reverse-BFS).
	 *  0 when the path isn't in the code index (deleted / non-source / not yet
	 *  indexed).
	 */
	impact_fan_out: number,
	is_hub: boolean,
};

export type EndedReason = "inactivity_timeout" | "app_quit" | "workday_boundary" | "manual" | "crash_recovered" | 
/**  W5 — session synthesized from migrated SQLite changelog entries. */
"synthetic_migrated" | 
/**
 *  PR-CI0 — external agent hook reported the session ended (Claude Code
 *  SessionEnd). Precise close, unlike the InactivityTimeout heuristic.
 */
"agent_exit";

export type EntityHit = {
	kind: EntityKind,
	id: string,
	title: string,
	/**  보조 문맥 — 일지: "워크데이 · 타입", 플랜 항목: 플랜 제목, 토의: status. */
	subtitle: string,
};

/**
 *  v2 U7 (docs/20260706_v2/02-features-spec.md §2) — 팔레트 "go to anything"
 *  히트 한 건. `id` 는 kind 별 라우팅 키: journal=relative_path,
 *  plan=plan_id, plan_item="plan_id#item_id", discussion=discussion_id.
 */
export type EntityKind = "journal" | "plan" | "plan_item" | "discussion";

/**
 *  One file's recorded diff for a journal entry. `patch` is a git-style unified
 *  diff (`a/ b/` headers) — never stored empty.
 */
export type EntryFileDiff = {
	path: string,
	patch: string,
};

/**
 *  User-facing filter for `list_entries`. Empty `types` means "all types".
 *  `search` matches against `title`, `slug`, `body_markdown`, and any tag
 *  in `oculpm_journal_tags` (case-insensitive for ASCII; substring for
 *  other scripts including Hangul).
 */
export type EntryFilters = {
	types: EntryType[],
	verified_only: boolean,
	/**
	 *  Reserved for W4 (LayerComparison). PR2 wires the column path but
	 *  `mismatch_only=true` returns no rows because no entry has been
	 *  flagged yet.
	 */
	mismatch_only: boolean,
	/**  `checkbox == Some(false)` OR `status != "done"`. */
	unfinished_only: boolean,
	search: string | null,
	/**  W5-PR6 — agent_id filter. Empty = no constraint (all agents). */
	agents?: string[],
	/**
	 *  W5-PR6 — difficulty filter. Empty = no constraint. Note the cache
	 *  column is nullable ("미지정"); difficulty filter therefore *cannot*
	 *  match the null bucket — that's a separate W6 toggle.
	 */
	difficulties?: Difficulty[],
};

export type EntryStatus = "planned" | "in_progress" | "done" | "abandoned";

export type EntryType = "bug" | "feature" | "error" | "refactor" | "chore";

/**  `## 기록` 표의 한 행. */
export type EvalRecord = {
	/**  `YYYY-MM-DD`. */
	date: string,
	suite: string,
	passed: number,
	total: number,
	memo: string,
};

/**
 *  `eval_signals` 응답. `EVALS.md` 자체가 없으면 커맨드가 `None` 을 돌려
 *  UI 가 섹션을 그리지 않는다.
 */
export type EvalSignals = {
	/**  날짜 오름차순 (동일 날짜는 문서 순서 유지), 최근 200건. */
	records: EvalRecord[],
	/**  등장한 스위트명 (등장 순서). */
	suites: string[],
};

export type FileChangeEvent = {
	ts: string,
	session_id: string,
	op: FileOp,
	path: string,
	hash_before: string | null,
	hash_after: string | null,
	/**
	 *  u32 — caps at 4 GB per file. Larger files skip hashing anyway
	 *  (`tags: ["large-file-hash-skipped"]`) so the value will be clamped.
	 */
	bytes: number,
};

export type FileOp = "create" | "update" | "delete" | "rename" | "correct";

export type FileTouched = {
	path: string,
	op: FileOp,
	bytes_added: number | null,
	bytes_removed: number | null,
	rename_from: string | null,
};

export type GeneratedSummary = {
	style: SummaryStyle,
	markdown: string,
	entry_count: number,
	used_llm: boolean,
	/**  LLM 폴백 사유 등 사용자에게 알릴 한 줄 (없으면 None). */
	note: string | null,
};

/**
 *  A single uncommitted change from `git status`. `op` is one of `"A"` / `"M"` /
 *  `"D"` so it lines up directly with the frontend `ChangeOp` union used by the
 *  변경 diff 화면. Renames/copies report the *new* path as an add.
 */
export type GitChange = {
	path: string,
	op: string,
};

export type GitCommit = {
	sha: string,
	short_sha: string,
	author_name: string,
	author_email: string,
	/**  Unix timestamp in seconds (author date). */
	timestamp: number,
	subject: string,
};

export type GitConfig = {
	journal_committed: boolean,
	forbid_journal_for_paths: string[],
	auto_redact_patterns: string[],
};

/**
 *  One commit in the graph view (Today git graph). Carries `parents` for lane
 *  routing and `refs` (branch/tag/HEAD decorations) so the UI can badge tips.
 */
export type GitGraphCommit = {
	sha: string,
	short_sha: string,
	parents: string[],
	author_name: string,
	/**  Unix timestamp in seconds (author date). */
	timestamp: number,
	subject: string,
	/**
	 *  Ref names pointing here (e.g. `main`, `origin/main`, a tag), HEAD-/tag-
	 *  prefixes stripped.
	 */
	refs: string[],
};

/**
 *  Lite-W6 PR5 — slim wrapper for the TitleBar mini git chip (UI consumer
 *  arrives in PR7). Returns just the branch + the count of `git status
 *  --porcelain` lines (staged + unstaged + untracked).
 */
export type GitHeadStatusBrief = {
	is_git_repo: boolean,
	/**  `None` when the repo is in detached-HEAD state or there is no repo. */
	head_branch: string | null,
	/**  Count of `--porcelain` lines. Capped at u32::MAX in practice. */
	uncommitted: number,
};

export type GitRemote = {
	name: string,
	url: string,
	/**  e.g. "github.com" — derived from the URL. */
	host: string | null,
	owner: string | null,
	repo: string | null,
};

export type GitRepoStatus = {
	is_git_repo: boolean,
	head_branch: string | null,
	remotes: GitRemote[],
};

export type Goal = {
	id: number,
	project_id: number | null,
	title: string,
	description: string | null,
	status: string,
	priority: number,
	due_date: number | null,
	progress: number | null,
	created_at: number,
	updated_at: number,
};

export type GraphEdgeDto = {
	id: number,
	edge_type: string,
	source: number,
	target: number,
	weight: number | null,
	direction: string,
	estimated: boolean,
};

export type GraphNodeDto = {
	id: number,
	kind: string,
	label: string,
	sub_kind: string | null,
	language: string | null,
	file_id: number,
	file_path: string,
	start_line: number | null,
	end_line: number | null,
};

export type GraphOpts = {
	/**
	 *  Include symbol nodes + `contains` (file→symbol) edges. `false` = only
	 *  file nodes + `imports` edges (lighter payload for large projects).
	 */
	symbol_level: boolean,
};

export type GreenfieldResult = {
	project_id: number,
	scaffold_output: string | null,
	seed_goals: Goal[],
};

/**
 *  One day's worth of activity data for the heatmap. `score` is a UI-friendly
 *  derived value (entries weighted higher than file events).
 */
export type HeatmapCell = {
	workday: string,
	entry_count: number,
	file_event_count: number,
	score: number,
};

export type ImpactNode = {
	file_id: number,
	path: string,
	depth: number,
};

export type ImpactReport = {
	/**  Changed paths that were found in the index (subset of the input). */
	changed: string[],
	/**  Files that (transitively) import a changed file, nearest first. */
	affected: ImpactNode[],
};

export type IndexProgress = {
	current: number,
	total: number,
	current_file: string,
};

export type IndexResult = {
	files_processed: number,
	files_changed: number,
	chunks_created: number,
	took_ms: number,
};

export type IntegrityWarning = {
	/**  One of `frontmatter_parse`, `schema_mismatch`, `orphan_session`, `narrative_mismatch`, `lock_recovered`, ... */
	kind: string,
	path: string,
	message: string,
};

export type JournalEntry = {
	/**  `<workday>/<Category>/<file>.md` — relative to `.oculpm/journal/`. */
	relative_path: string,
	frontmatter: JournalFrontmatter,
	/**  First non-blank line after frontmatter, with the `[ ]`/`[x]` prefix stripped. */
	title: string,
	/**  `None` when first line lacks a checkbox; `Some(true)` for `[x]`, `Some(false)` for `[ ]`. */
	checkbox: boolean | null,
	body_markdown: string,
	/**
	 *  u32 (not u64) for specta BigInt-export compatibility — see
	 *  docs/2026521/Errors/2026-05-21-specta-bigint-export.md. Caps at 4 GB
	 *  which no realistic journal entry will hit.
	 */
	byte_size: number,
	mtime: string,
	/**
	 *  False when the YAML frontmatter failed to parse (the row is still cached
	 *  as a synthesized chore). Drives a ⚠ reliability badge (F7a).
	 */
	parse_ok: boolean,
	/**  Non-fatal parse warnings (missing tz offset, agent-as-string, bad op, …). */
	parse_warnings: string[],
};

export type JournalEntrySummary = {
	relative_path: string,
	workday: string,
	type: EntryType,
	slug: string,
	status: EntryStatus,
	difficulty: Difficulty | null,
	title: string,
	checkbox: boolean | null,
	session_id: string,
	agent_id: string,
	/**
	 *  The model the agent reported (frontmatter `agent.version`), e.g.
	 *  `"Opus 4.8"` / `"Gemini 3 Pro"`. `None` when not reported.
	 */
	agent_version: string | null,
	verified_by_user: boolean,
	created_at: string,
	updated_at: string | null,
	tags: string[],
	files_count: number,
	parse_ok: boolean,
	parse_warnings: string[],
};

export type JournalFrontmatter = {
	schema_version: number,
	type: EntryType,
	slug: string,
	status: EntryStatus,
	difficulty: Difficulty | null,
	created_at: string,
	updated_at: string | null,
	session_id: string,
	agent: AgentRef,
	/**  Two-letter ISO 639-1, e.g. `ko` or `en`. */
	language: string,
	verified_by_user: boolean,
	files_touched: FileTouched[],
	related: RelatedRef[],
	tags: string[],
};

/**
 *  The most recent commit's metadata + the files it touched. Powers the 변경
 *  diff 화면's "직전 커밋" baseline, shown when the working tree is clean so the
 *  screen isn't empty after a coding agent commits its work.
 */
export type LastCommitChanges = {
	sha: string,
	short_sha: string,
	subject: string,
	changes: GitChange[],
};

/**
 *  W4-PR5 — diff between the watcher's ndjson (index, ground truth) and
 *  the union of `files_touched[].path` from journal entries that name a
 *  given `session_id`. See `docs/major_update/oculpm/W4/PR5-compare-layers.md`.
 */
export type LayerComparison = {
	session_id: string,
	workday: string,
	/**
	 *  Distinct project-relative paths from `file_changes.ndjson` for this
	 *  session, after stripping forbidden + `**redacted/sensitive**:*` paths.
	 */
	index_files: string[],
	/**
	 *  Union of `files_touched[].path` across every journal entry that names
	 *  this session, after the same forbidden / redacted strip.
	 */
	journal_files: string[],
	matched: string[],
	/**  In the index but not the journal — likely *missing narrative*. */
	only_in_index: string[],
	/**  In the journal but not the index — likely *hallucinated path*. */
	only_in_journal: string[],
	mismatch_severity: Severity,
	/**
	 *  `|matched| / |union|`. `1.0` when both sets are empty (treated as
	 *  trivially in sync — no activity, nothing to disagree on).
	 */
	jaccard_index: number | null,
};

export type LocalDiffReindexReport = {
	indexed: string[],
	skipped: ReindexSkip[],
	elapsed_ms: number,
	embeddings_updated: number,
	ast_updated: number,
};

export type LockStateView = "healthy" | "held_by_other" | "recovered" | "uninitialized";

export type ManualEntryDraft = {
	type: EntryType,
	slug: string,
	title: string,
	difficulty: Difficulty | null,
	body_markdown: string,
	/**
	 *  `None` → use the active session if any, else fall back to a
	 *  `manual-<workday>-<HHMMSS>` sentinel id.
	 */
	session_id: string | null,
	files_touched: FileTouched[],
	/**  `None` → defaults to `planned`. Spec §3.1. */
	status: EntryStatus | null,
	tags: string[],
	/**
	 *  PR-CI1 — `None` → `manual` (수동 모달의 기존 의미). 훅 기반 자동 초안은
	 *  실측 에이전트(`claude-code` + transcript 의 model)를 넣는다.
	 */
	agent?: AgentRef | null,
	/**
	 *  PR-CI1 — `None` → `true` (수동 모달 = 사용자가 직접 씀). 자동 초안은
	 *  `Some(false)` — 사용자가 UI 에서 검토 후 토글한다.
	 */
	verified_by_user?: boolean | null,
};

/**  An available master-template upgrade for a project. */
export type MasterUpgrade = {
	from_version: number,
	to_version: number,
};

export type McpRegistrationStatus = {
	/**  `.mcp.json` 에 우리 서버가 등록되어 있다. */
	registered: boolean,
	/**  사이드카 바이너리를 찾았다 (없으면 등록 불가 — dev 는 `cargo build`). */
	binary_found: boolean,
	binary_path: string | null,
	mcp_json_path: string,
	/**  Claude Desktop `claude_desktop_config.json` 에 붙여넣을 스니펫. */
	desktop_snippet: string,
	/**  우리 것 아닌 MCP 서버 정의 수 (정보 표시용 — 건드리지 않음). */
	foreign_servers: number,
};

export type Message = {
	role: Role,
	content: string,
};

/**  Cursor 미러 상태 — 프로젝트 스코프 `Rule` 에만 의미가 있다. */
export type MirrorState = 
/**  미러 없음 (번역 꺼짐 포함). */
"none" | 
/**  우리 마커가 있는 미러가 존재. */
"mirrored" | 
/**  같은 경로에 마커 없는 파일이 존재 — 건드리지 않는다. */
"conflict";

/**  미러 쓰기/제거 한 건의 결과. */
export type MirrorWriteResult = {
	/**  번역 타깃 id (v1: "cursor"). */
	target: string,
	/**  원본 rel_path. */
	source_rel: string,
	/**  "written" | "unchanged" | "removed" | "conflict". */
	action: string,
	/**  미러 파일의 프로젝트 상대 경로. */
	mirror_rel: string,
};

export type NotionStatus = {
	/**
	 *  키체인에 internal integration token 이 있는가 — 없으면 UI 는 내보내기
	 *  버튼 자체를 그리지 않는다 (수용 기준: 토큰 없으면 기능 비노출).
	 */
	has_token: boolean,
	/**  정규화된 부모 페이지 id (설정 안 됐으면 None). */
	parent_page_id: string | null,
};

export type OculpmAgentDrift = {
	project_id: number,
	agent_id: string,
	expected_hash: string,
	actual_hash: string,
};

export type OculpmAgentsTemplateChanged = {
	project_id: number,
	relative_path: string,
};

export type OculpmConfig = {
	schema_version: number,
	workday: WorkdayConfig,
	session: SessionConfig,
	git: GitConfig,
	watcher: WatcherConfig,
	agents: AgentsConfig,
};

export type OculpmFileChanged = {
	project_id: number,
	event: FileChangeEvent,
};

export type OculpmInitReport = {
	/**  Project-relative paths that were created. */
	created_dirs: string[],
	wrote_config: boolean,
	wrote_gitignore: boolean,
	lock_state: LockStateView,
};

export type OculpmIntegrityWarning = {
	project_id: number,
	warning: IntegrityWarning,
};

export type OculpmJournalAdded = {
	project_id: number,
	summary: JournalEntrySummary,
};

export type OculpmJournalPathChanged = {
	project_id: number,
	relative_path: string,
	op: FileOp,
};

export type OculpmJournalUpdated = {
	project_id: number,
	summary: JournalEntrySummary,
};

export type OculpmOverviewStats = {
	generated_at: string,
	window_days: number,
	/**  Every workday in the window (entries=0 days included as empty cells). */
	heatmap_cells: HeatmapCell[],
	difficulty_mix: DifficultyMix,
	agent_breakdown: AgentCount[],
	/**  Up to 50 unfinished entries, most recent first. */
	unfinished_entries: JournalEntrySummary[],
	/**  Up to 30 days of session aggregates, most recent first. */
	recent_sessions: SessionDailyAgg[],
};

/**
 *  F1 — emitted after auto-reconcile applies status flips to a plan, so the UI
 *  can toast ("AI 가 N개 항목을 자동 갱신") and refresh the planner. Only fired on
 *  an actual change (≥1 applied); skips/no-ops stay silent.
 */
export type OculpmPlanReconciled = {
	project_id: number,
	plan_id: string,
	/**  Number of item statuses changed. */
	applied: number,
};

export type OculpmSessionEnded = {
	project_id: number,
	session: Session,
};

export type OculpmSessionStarted = {
	project_id: number,
	session: Session,
};

export type OculpmStatus = {
	initialized: boolean,
	config_valid: boolean,
	lock_state: LockStateView,
	current_workday: string,
	watcher_state: WatcherStateView,
};

/**
 *  v2 U10 (C1) — 활성 플랜의 미완 항목 한 건 (스탠드업 "오늘 할 일"/"막힘" 소스).
 *  v2 U12 에서 Today "다음 할 일" 위젯도 이 shape 를 소비한다 (workday brief).
 */
export type OpenPlanItem = {
	plan_id: string,
	plan_title: string,
	item_id: string,
	item_title: string,
	/**  항목이 속한 phase 헤딩 (없으면 None — UI 는 플랜 제목으로 폴백). */
	phase: string | null,
	/**  todo | in_progress | blocked */
	status: string,
};

/**  Recent plan activity across all plans — drives the Today "계획 업데이트" block. */
export type PlanActivityDto = {
	plan_id: string,
	plan_title: string,
	item_id: string,
	item_title: string,
	agent_id: string,
	ts: string,
	from_status: string | null,
	to_status: string | null,
	note: string | null,
};

export type PlanDecisionDto = {
	decision_id: string,
	title: string,
	body: string,
	locked_at: string | null,
	agent_id: string | null,
	affects: string[],
};

export type PlanDetail = {
	plan: PlanSummary,
	items: PlanItemDto[],
	phases: PlanPhaseDto[],
	decisions: PlanDecisionDto[],
	/**
	 *  Non-fatal parse warnings (broken glyphs, missing ids, …). Surfaced so
	 *  the UI never fails silently on a malformed plan.
	 */
	warnings: string[],
};

/**
 *  An edit applied by the app / in-app AI to a plan. External agents edit the
 *  `.md` directly per AGENTS.md (PR-PLN 2); this is the in-app equivalent.
 */
export type PlanEditOp = 
/**  Flip an existing item's status. */
{ kind: "set_status"; item_id: string; status: string } | 
/**  Add a new item under a phase (created if absent). */
{ kind: "add_item"; phase: string; title: string; item_id: string | null; status: string | null } | 
/**  Remove an existing item. */
{ kind: "remove_item"; item_id: string } | 
/**  Rename an existing item's title. */
{ kind: "rename_item"; item_id: string; title: string } | 
/**  Rename a phase heading (keeps its items + tracking id). */
{ kind: "rename_phase"; from: string; to: string } | 
/**  Remove a phase heading and every item under it. */
{ kind: "remove_phase"; phase: string } | 
/**  Reorder a phase among its siblings (`up = true` moves it earlier). */
{ kind: "move_phase"; phase: string; up: boolean };

export type PlanItemDto = {
	item_id: string,
	phase: string | null,
	title: string,
	status: string,
	order_idx: number,
	parent_item: string | null,
	note: string | null,
	last_agent: string | null,
	last_update: string | null,
	/**
	 *  Distinct journal entries linked to this item via the plan-log (the
	 *  agent's `일지` column). Drives the 📓 link + the progress suggestion.
	 */
	journal_refs: string[],
};

export type PlanItemUpdateDto = {
	ts: string,
	item_id: string,
	agent_id: string,
	from_status: string | null,
	to_status: string | null,
	journal_ref: string | null,
	note: string | null,
};

/**  A trackable phase (`## Heading {#id}`) — rollup status + who last touched it. */
export type PlanPhaseDto = {
	phase_id: string | null,
	name: string,
	status: string,
	progress: number | null,
	item_count: number,
	done_count: number,
	last_agent: string | null,
	last_update: string | null,
};

export type PlanSummary = {
	plan_id: string,
	title: string,
	status: string,
	owner_agent: string,
	progress: number | null,
	file_path: string,
	updated_at: string,
	item_count: number,
	done_count: number,
};

export type Project = {
	id: number,
	name: string,
	root_path: string,
	created_at: number,
};

export type ProjectBlueprint = {
	id: number,
	name: string,
	idea_text: string | null,
	target_users: string | null,
	stack_choice: string | null,
	folder_name: string | null,
	folder_path: string | null,
	seed_goals_json: string | null,
	wizard_step: number,
	created_at: number,
	updated_at: number,
};

export type ProjectOverview = {
	project_id: number,
	identity: string | null,
	/**
	 *  JSON-encoded stack metadata. Stored as TEXT for forward compatibility
	 *  (the LLM is free to add new keys without a migration).
	 */
	stack_json: string | null,
	overview_md: string | null,
	source_signature: string | null,
	generated_at: number | null,
	generated_by_model: string | null,
};

export type ProjectStats = {
	files: number,
	chunks: number,
};

/**
 *  One entry in the user-configured failover chain (Settings → LLM → 폴백 체인).
 *  On a failed call the next entry is tried, in order.
 */
export type ProviderModel = {
	provider: string,
	model: string,
};

export type PtyAttach = {
	/**  지금까지의 스크롤백 (상한 내). xterm 에 그대로 write 해 리플레이한다. */
	text: string,
	/**  스냅샷에 포함된 마지막 청크의 seq — 이 값 이하의 라이브 이벤트는 중복. */
	seq: number,
};

export type ReindexReport = {
	project_id: number,
	inserted: number,
	updated: number,
	deleted: number,
	skipped: number,
	completed_at: string,
};

export type ReindexSkip = {
	path: string,
	reason: ReindexSkipReason,
};

/**
 *  Per-path outcome surfaced to the UI. Skip reasons let the caller render a
 *  "(skipped: too large)" badge next to the path without re-running
 *  `walk_text_files` filters.
 */
export type ReindexSkipReason = { kind: "not_found" } | { kind: "read_failed"; error: string } | { kind: "upsert_failed"; error: string };

export type RelatedRef = {
	/**  Path relative to `.oculpm/journal/` (e.g. `20260522/Bugs/2050_bug_X.md`). */
	ref: string,
	/**  One of `blocks`, `blocked_by`, `followup`, `duplicate`. */
	kind: string,
};

/**
 *  A file touched by 2+ error/bug entries in the range — a recurring trouble
 *  spot.
 */
export type RepeatedFile = {
	path: string,
	/**  Number of distinct error/bug entries that touched it. */
	count: number,
};

/**  A friction unit — an error/bug journal entry. */
export type ResistanceItem = {
	/**  Raw frontmatter type: `error` | `bug`. */
	kind: string,
	title: string,
	status: string,
	workday: string,
};

/**
 *  F4 — one cached retrospective for a workday range. `signature` is a hash of
 *  the deterministic signals; when it diverges from the current signals the
 *  frontend marks the cached narrative stale. Mirrors `project_overviews`.
 */
export type RetroInsight = {
	project_id: number,
	/**  "YYYYMMDD..YYYYMMDD" (inclusive workday range). */
	range_key: string,
	signature: string,
	retro_md: string,
	generated_at: number,
	generated_by_model: string | null,
};

/**
 *  The deterministic signal set the retro is grounded in. Returned to the UI
 *  directly *and* fed to the LLM. `signature` hashes everything but itself, so
 *  the frontend can compare it to a cached retro's signature to show staleness.
 */
export type RetroSignals = {
	/**  Workday "YYYYMMDD". */
	since: string,
	until: string,
	/**  "since..until". */
	range_key: string,
	signature: string,
	total_entries: number,
	shipped: ShippedItem[],
	resistance: ResistanceItem[],
	repeated_files: RepeatedFile[],
	effort_hotspots: EffortHotspot[],
	agent_breakdown: AgentCount[],
	difficulty_mix: DifficultyMix,
};

export type Role = "system" | "user" | "assistant";

/**  결정적 규칙 후보 — 한 코드 영역의 반복 실패 클러스터. */
export type RuleCandidate = {
	/**  억제/재조회 키 (`area:<영역>`). */
	key: string,
	/**  공유 디렉터리 영역 (예: `src-tauri/src/oculpm`). */
	area: string,
	/**  클러스터의 실패(error/bug) 일지 수. */
	entry_count: number,
	/**  등장한 종류 (정렬: `bug`, `error`). */
	kinds: string[],
	/**  표본 제목 (최신순, 최대 4). */
	sample_titles: string[],
	/**  증거 일지의 캐시 상대경로 (최신순 — 초안 생성이 본문을 읽는다). */
	entry_rels: string[],
	/**  결정적 paths 제안 (`<area>/**`) — LLM 이 다듬되 폴백으로도 쓴다. */
	suggested_paths: string[],
	/**  가장 최근 실패 workday. */
	last_workday: string,
};

/**  `rules_read` 응답. */
export type RuleDetail = {
	entry: RuleEntry,
	content: string,
	/**  절대 경로 — 외부 에디터로 열 때 사용. */
	abs_path: string,
};

/**
 *  LLM 이 만든 규칙 초안. `content` 가 저장용 완성본 — 프런트는 슬러그만
 *  바꿔서 `rules_save(".claude/rules/<slug>.md", content, create=true)` 를
 *  부른다 (승인 없이는 어떤 파일도 쓰이지 않는다).
 */
export type RuleDraft = {
	candidate_key: string,
	slug: string,
	title: string,
	paths: string[],
	body_markdown: string,
	/**  frontmatter(paths) + promoted-from 마커 + 본문의 저장용 완성본. */
	content: string,
	/**  제안 저장 위치 (`.claude/rules/<slug>.md`). */
	rel_path: string,
};

/**  목록의 한 줄. `(scope, rel_path)` 가 조작 키다. */
export type RuleEntry = {
	scope: RuleScope,
	kind: RuleKind,
	/**  스코프 루트 상대 경로 (`CLAUDE.md`, `.claude/rules/api/validation.md` …). */
	rel_path: string,
	/**  표시명 — ClaudeMd 는 파일명, Rule 은 rules/ 이하 스템 (`api/validation`). */
	name: string,
	/**  본문 첫 H1 텍스트 (없으면 빈 문자열) — 목록 부제용. */
	title: string,
	/**  ClaudeMd 슬롯 전용 — 파일이 아직 없으면 false ("만들기" 어포던스). */
	exists: boolean,
	/**  frontmatter `paths` (없으면 빈 배열 = 항상 로드). */
	paths: string[],
	bytes: number,
	mirror: MirrorState,
};

export type RuleKind = 
/**  CLAUDE.md 계열 고정 슬롯 (항상 로드되는 메모리 파일). */
"claude_md" | 
/**  `.claude/rules/**\/*.md` 규칙 파일. */
"rule";

/**  `rules_save` 응답 — 저장된 엔트리 + (옵인 시) 미러 결과. */
export type RuleSaveOutcome = {
	entry: RuleEntry,
	mirror: MirrorWriteResult | null,
};

export type RuleScope = 
/**  프로젝트 루트 기준 (`<project>/CLAUDE.md`, `<project>/.claude/rules/…`). */
"project" | 
/**  홈 디렉터리 기준 (`~/.claude/CLAUDE.md`, `~/.claude/rules/…`). */
"global";

/**  `rules_list` 응답 — 전 스코프를 한 번에 (스킬 overview 패턴). */
export type RulesOverview = {
	/**  고정 슬롯 (프로젝트 3 + 전역 1, exists=false 포함). */
	claude_md: RuleEntry[],
	project_rules: RuleEntry[],
	global_rules: RuleEntry[],
	/**  절대 경로 — 빈 상태 안내용. */
	project_rules_dir: string,
	global_rules_dir: string,
	/**  `config.agents.rules_translate` 에 "cursor" 가 있는가. */
	cursor_translate: boolean,
};

export type Session = {
	/**  `YYYYMMDD-NNN`. */
	id: string,
	started_at: string,
	ended_at: string | null,
	ended_reason: EndedReason | null,
	/**
	 *  u32 — caps at ~49 days of continuous active time. A single session
	 *  will never approach this.
	 */
	active_window_ms: number,
	file_event_count: number,
	files_unique: number,
	git_head_at_start: string | null,
	git_head_at_end: string | null,
	agent_label_guess: string | null,
	/**  Paths relative to `.oculpm/journal/<workday>/`. */
	linked_journal_entries: string[],
};

export type SessionConfig = {
	inactivity_timeout_minutes: number,
	auto_close_on_workday_boundary: boolean,
	auto_close_on_app_quit: boolean,
	crash_recovery_grace_minutes: number,
	/**
	 *  W4 dogfooding fix — minutes within which new activity after an
	 *  InactivityTimeout finalize will REOPEN the most recent
	 *  inactivity-closed session instead of starting a new one. Bounded by
	 *  today's workday (we never resurrect sessions across the workday
	 *  boundary). `0` disables resume entirely. Defaults to 15 minutes.
	 */
	session_resume_grace_minutes?: number,
};

export type SessionDailyAgg = {
	workday: string,
	session_count: number,
	total_active_seconds: number,
	files_unique: number,
	journal_entry_count: number,
	/**
	 *  `journal_entry_count / sessions_with_file_events`. `0.0` when no
	 *  sessions have file events (avoids NaN). UI shows as percentage.
	 */
	narrative_rate: number | null,
};

export type Severity = "ok" | "warning" | "critical";

/**  A shipped unit — a completed feature/refactor journal entry. */
export type ShippedItem = {
	/**  Raw frontmatter type: `feature` | `refactor`. */
	kind: string,
	title: string,
	agent_id: string,
	workday: string,
};

/**  `skills_read` 응답 — 원문 + 보조 파일 목록. */
export type SkillDetail = {
	entry: SkillEntry,
	/**  SKILL.md 원문 (frontmatter 포함). */
	content: string,
	/**  스킬 폴더 내 보조 파일 상대 경로 (SKILL.md 제외, 최대 50개). */
	files: string[],
	/**  SKILL.md 절대 경로 — 외부 에디터로 열 때 사용. */
	skill_md_path: string,
};

/**  스킬 목록의 한 줄. `dir_name` 이 (scope 내) 조작 키다. */
export type SkillEntry = {
	scope: SkillScope,
	dir_name: string,
	/**  frontmatter `name` (없으면 폴더명). */
	name: string,
	/**  frontmatter `description` (없으면 빈 문자열) — 에이전트 자동 발동 기준. */
	description: string,
	enabled: boolean,
	/**  표시용 경로 — project 는 프로젝트 루트 상대, global 은 `~/…`. */
	display_path: string,
	/**  SKILL.md 를 제외한 보조 파일 수 (참고 문서·스크립트 등). */
	extra_files: number,
};

export type SkillScope = 
/**  `<project>/.claude/skills` — 이 프로젝트에서만 로드. */
"project" | 
/**  `~/.claude/skills` — 모든 프로젝트에서 로드. */
"global";

/**  `skills_list` 응답. 두 스코프를 한 번에 내려 UI 왕복을 줄인다. */
export type SkillsOverview = {
	project: SkillEntry[],
	global: SkillEntry[],
	/**  절대 경로 — 빈 상태 안내·"폴더 열기" 용. */
	project_skills_dir: string,
	global_skills_dir: string,
};

export type SummaryStyle = "standup" | "pr_description" | "weekly_status";

export type SymbolCall = {
	/**  Caller symbol in this file (None = file top-level). */
	from_symbol: string | null,
	kind: string,
	callee: string,
	/**  Resolved defining file path (None = external / unresolved). */
	target_path: string | null,
	estimated: boolean,
};

export type SymbolDef = {
	name: string,
	kind: string,
	start_line: number,
	end_line: number,
	start_byte: number,
	end_byte: number,
};

/**
 *  PR-R1b (A2) — a symbol hit from `search_symbols` (name LIKE over the AST
 *  symbol index). Unlike `SymbolDef` it carries the owning file path.
 */
export type SymbolSearchResult = {
	name: string,
	kind: string,
	file_path: string,
	start_line: number,
	end_line: number,
};

/**  팝오버 → 메인 창 딥링크 (D5). `view` 는 프런트 `UiV2View` 문자열. */
export type TrayNavigate = {
	view: string,
	project_id: number | null,
	/**  `.oculpm/` 상대 일지 경로 — 있으면 해당 일지를 연다. */
	entry_path: string | null,
};

export type WatcherConfig = {
	ignore: string[],
	respect_gitignore: boolean,
	debounce_ms: number,
	batch_max_events: number,
};

export type WatcherStateView = "running" | "stopped" | "error";

/**
 *  v2 U12 (N3) — Today/저널 타임라인의 단일 집계 응답. 기존에 Today 오픈이
 *  [요일당 list 7회 + 오늘 엔트리당 get 1회 + 플랜당 get 1회 + 365일 히트맵]
 *  = 12+N 회 IPC 를 유발하던 것을 이 커맨드 1회로 대체한다.
 */
export type WorkdayBrief = {
	days: WorkdayBucket[],
	/**  `bytes_workday` 로 지정한 워크데이의 bytes 합 (미지정 시 0/0). */
	bytes_added: number,
	bytes_removed: number,
	/**  활성 플랜의 미완 항목 (진행중 우선) — Today "다음 할 일" + 스탠드업 공유. */
	open_plan_items: OpenPlanItem[],
	/**  프로젝트 전체 일지 수 (365일 히트맵 대체 스칼라). */
	total_entries: number,
};

/**  v2 U12 (N3) — 워크데이 버킷 하나. */
export type WorkdayBucket = {
	workday: string,
	entries: JournalEntrySummary[],
};

export type WorkdayConfig = {
	/**  IANA timezone name (e.g. `Asia/Seoul`). */
	timezone: string,
	/**  `HH:MM` 24-hour. Late-night coders may use `03:00`. */
	day_starts_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

