#Requires -Version 7.0
<#
.SYNOPSIS
  Windows 설치 파일이 싣는 Microsoft Visual C++ 재배포 패키지(x64)를 받아 검증한다
  (크로스플랫폼 W3 · L-PKG). `pnpm tauri build`(Windows) **전에** 한 번 돈다 — 번들 잡과
  release.yml 둘 다.

.DESCRIPTION
  왜: ocul-pm.exe · oculpm-mcp.exe 는 MSVCP140.dll · MSVCP140_1.dll 을 가져온다(사전 빌드
  ONNX Runtime 이 동적 CRT /MD). VC++ 재배포가 없는 PC 에서는 0xC0000135 로 아예 안 뜬다
  (install smoke 실측). 설치 파일의 NSIS 훅(src-tauri/windows/installer-hooks.nsh)이 없거나
  낡았을 때만 이 파일을 돌린다.

  무엇을 받나: Microsoft 의 "최신 지원 VC++ 재배포" 영구 링크 https://aka.ms/vc14/vc_redist.x64.exe
  가 2026-09-25 에 가리키던 판 — 그 리다이렉트의 **판 고정 URL**(경로에 SHA-256 이 들어 있다)과
  해시를 여기에 박는다. aka.ms 를 그대로 쓰면 Microsoft 가 판을 올리는 날 빌드가 조용히 바뀐다.
  판을 올릴 때: `curl -sI https://aka.ms/vc14/vc_redist.x64.exe` 의 Location 으로 아래 세 값을
  바꾸고, 새 판의 빌드가 installer-hooks.nsh 의 OCULPM_VCRT_MIN_BLD 이상인지 본다(이 스크립트가
  단언한다).

  검증: SHA-256 일치 · Authenticode 서명 유효 + 서명자 Microsoft Corporation · 파일 버전 일치 ·
  빌드 ≥ OCULPM_VCRT_MIN_BLD. 하나라도 어긋나면 실패한다(설치 파일을 만들지 않는다).

  산출: src-tauri/windows/vcredist/VC_redist.x64.exe 와 vcredist.nsh(NSIS 정의 — 훅이 include).
  둘 다 커밋하지 않는다(그 폴더의 .gitignore).
#>
[CmdletBinding()]
param(
    [string] $OutDir = (Join-Path $PSScriptRoot '..\..\src-tauri\windows\vcredist')
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# ── 고정 값 (판을 올릴 때 셋을 함께 바꾼다) ────────────────────────────────
$Url = 'https://download.visualstudio.microsoft.com/download/pr/ebdab8e5-1d7b-4d9f-a11b-cbb1720c3b12/843068991DAAA1F73AD9F6239BCE4D0F6A07A51F18C37EA2A867E9BECA71295C/VC_redist.x64.exe'
$Sha256 = '843068991DAAA1F73AD9F6239BCE4D0F6A07A51F18C37EA2A867E9BECA71295C'
$Version = '14.51.36247.0'

$HooksFile = Join-Path $PSScriptRoot '..\..\src-tauri\windows\installer-hooks.nsh'

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$OutDir = (Resolve-Path -LiteralPath $OutDir).Path
$Exe = Join-Path $OutDir 'VC_redist.x64.exe'

# 이미 받아 둔 것이 해시까지 맞으면 다시 받지 않는다(로컬 반복 빌드).
$have = (Test-Path -LiteralPath $Exe) -and ((Get-FileHash -LiteralPath $Exe -Algorithm SHA256).Hash -eq $Sha256)
if (-not $have) {
    $tmp = "$Exe.download"
    for ($i = 1; $i -le 4; $i++) {
        try {
            Invoke-WebRequest -Uri $Url -OutFile $tmp -UseBasicParsing
            break
        } catch {
            if ($i -eq 4) { throw "vc_redist 받기 실패(4회): $($_.Exception.Message)" }
            Write-Host "받기 실패 ($i/4) — $([int][math]::Pow(2, $i))초 뒤 다시: $($_.Exception.Message)"
            Start-Sleep -Seconds ([int][math]::Pow(2, $i))
        }
    }
    Move-Item -LiteralPath $tmp -Destination $Exe -Force
}

$hash = (Get-FileHash -LiteralPath $Exe -Algorithm SHA256).Hash
if ($hash -ne $Sha256) { throw "SHA-256 불일치: $hash (기대 $Sha256)" }

$sig = Get-AuthenticodeSignature -LiteralPath $Exe
if ($sig.Status -ne 'Valid') { throw "Authenticode 서명이 유효하지 않다: $($sig.Status) $($sig.StatusMessage)" }
$subject = $sig.SignerCertificate.Subject
if ($subject -notmatch '(^|,\s*)O=Microsoft Corporation(,|$)') { throw "서명자가 Microsoft Corporation 이 아니다: $subject" }

$fileVersion = (Get-Item -LiteralPath $Exe).VersionInfo.FileVersion
if ($fileVersion -ne $Version) { throw "파일 버전이 다르다: $fileVersion (기대 $Version)" }
$bld = [int]($Version.Split('.')[2])

$hooks = Get-Content -LiteralPath $HooksFile -Raw
$m = [regex]::Match($hooks, '(?m)^!define OCULPM_VCRT_MIN_BLD (\d+)')
if (-not $m.Success) { throw "$HooksFile 에서 OCULPM_VCRT_MIN_BLD 를 못 찾았다" }
$minBld = [int]$m.Groups[1].Value
if ($bld -lt $minBld) { throw "받은 vc_redist 빌드 $bld 가 요구 최소 $minBld 보다 낮다 — 더 새 판으로 고정을 올릴 것" }

# 이 기계가 링크에 쓸 MSVC 도구 계열(14.xx)이 동봉 재배포보다 새면 안 된다 — Microsoft 규칙
# "재배포는 앱 구성 요소가 쓴 가장 새 도구 이상". 러너 이미지가 도구를 올리는 날 여기서 멈추고,
# 고정 판(과 installer-hooks.nsh 의 OCULPM_VCRT_MIN_BLD)을 함께 올리라고 알린다.
$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path -LiteralPath $vswhere)) { throw "vswhere.exe 가 없다 — MSVC 도구 판을 확인할 수 없다: $vswhere" }
$toolsFile = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    -find 'VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt' | Select-Object -First 1
if (-not $toolsFile) { throw 'MSVC x64 도구(VC.Tools.x86.x64)를 못 찾았다' }
$tools = [version]((Get-Content -LiteralPath $toolsFile -Raw).Trim())
$redist = [version]$Version
if ($tools.Major -ne $redist.Major -or $tools.Minor -gt $redist.Minor) {
    throw "빌드 도구 MSVC $tools 가 동봉 재배포 $Version 보다 새 계열이다 — 재배포 고정 판을 올릴 것"
}

# NSIS 는 BOM 없는 include 를 ANSI 로 읽는다 — 여기는 ASCII 만 쓴다(경로도 러너에선 ASCII).
$nsh = @"
; generated by .github/scripts/fetch-vcredist.ps1 -- do not edit, do not commit
!define OCULPM_VCREDIST_EXE "$Exe"
!define OCULPM_VCREDIST_VERSION "$Version"
!define OCULPM_VCREDIST_BLD $bld
!define OCULPM_VCREDIST_SHA256 "$Sha256"
"@
Set-Content -LiteralPath (Join-Path $OutDir 'vcredist.nsh') -Value $nsh -Encoding ascii

$size = (Get-Item -LiteralPath $Exe).Length
$line = "vc_redist $Version (빌드 $bld ≥ 요구 $minBld · 링크 도구 MSVC $tools 계열 ≤ 재배포 계열) · $([math]::Round($size / 1MB, 1)) MB · SHA-256 $Sha256 · 서명 $($sig.Status) ($($sig.SignerCertificate.Subject))"
Write-Host $line
if ($env:GITHUB_STEP_SUMMARY) { Add-Content -LiteralPath $env:GITHUB_STEP_SUMMARY -Value "- $line" -Encoding utf8 }
