//! Project file walking, line-based chunking, and indexing pipeline.

use std::collections::HashSet;
use std::path::{Component, Path, PathBuf};

use ignore::{overrides::OverrideBuilder, WalkBuilder};

pub const DEFAULT_MAX_FILE_BYTES: u64 = 500_000; // 500 KB
pub const DEFAULT_CHUNK_LINES: usize = 30;
pub const DEFAULT_CHUNK_OVERLAP: usize = 4;
const MAX_BINARY_PROBE: usize = 1024;

/// 한 줄이 이 길이를 넘는 파일은 minified/생성 파일로 보고 색인하지 않는다.
///
/// 근거(2026-08-30 실측): 22줄에 최장 줄이 216KB 인 emscripten 산출물
/// (`libktx.js`) 하나가 AST 심볼 503개마다 그 줄을 통째로 복제해 청크 104MB 를
/// 만들었다 — 앱 DB 558MB 의 1/5. 사람이 검색해서 읽을 코드에 4KB 짜리 한 줄은
/// 없고, 있다면(데이터 URI·번들) 검색 결과로 보여 줄 가치도 없다.
pub const MAX_LINE_BYTES: usize = 4_096;

/// 청크 하나의 본문 상한. 임베딩 모델은 어차피 앞 512 토큰만 보므로 그 이상은
/// 저장·전송 비용만 든다. 넘는 범위는 줄 창으로 다시 쪼갠다.
pub const MAX_CHUNK_BYTES: usize = 16_384;

/// `.gitignore` 와 무관하게 절대 걷지 않는 디렉터리 이름 — 벤더·캐시·빌드
/// 산출물. `.gitignore` 자체가 없는 프로젝트를 위한 마지막 그물이다. `dist`·
/// `build`·`out` 은 일부러 뺐다: 소스 폴더로 쓰는 프로젝트가 있고, 산출물이면
/// `.gitignore` 가 이미 막는다.
const DENY_DIR_NAMES: &[&str] = &[
    "node_modules",
    ".git",
    "target",
    ".venv",
    "venv",
    "__pycache__",
    ".next",
    ".nuxt",
    ".turbo",
    ".cache",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".gradle",
    "Pods",
    "DerivedData",
    "coverage",
    "bower_components",
    ".svelte-kit",
    ".angular",
    ".parcel-cache",
];

/// Bug 2 — minimum number of *meaningful* lines a gap between AST symbols must
/// have to become its own chunk. Gaps below this (a lone `import`, a closing
/// `}`, a blank run) are skipped instead of indexed as tiny single-line chunks
/// that pollute search results. The symbols themselves are always chunked.
const MIN_GAP_CHUNK_LINES: usize = 3;

/// Runtime configuration loaded from the `settings` table. All knobs have
/// sensible defaults that match the previous hardcoded values.
#[derive(Debug, Clone)]
pub struct IndexConfig {
    pub max_file_bytes: u64,
    pub chunk_lines: usize,
    pub chunk_overlap: usize,
    /// Extra gitignore-style patterns added on top of the project's .gitignore.
    pub extra_exclude_patterns: Vec<String>,
}

impl Default for IndexConfig {
    fn default() -> Self {
        Self {
            max_file_bytes: DEFAULT_MAX_FILE_BYTES,
            chunk_lines: DEFAULT_CHUNK_LINES,
            chunk_overlap: DEFAULT_CHUNK_OVERLAP,
            extra_exclude_patterns: Vec::new(),
        }
    }
}

/// Filenames that are noise for semantic code search — typically autogenerated
/// or huge serialized blobs.
const SKIP_FILENAMES: &[&str] = &[
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "bun.lockb",
    "composer.lock",
    "poetry.lock",
    "uv.lock",
];

/// Filename suffix patterns to skip.
const SKIP_SUFFIXES: &[&str] = &[
    ".min.js",
    ".min.css",
    ".min.mjs",
    ".map",      // sourcemaps
    ".lock",     // generic lock files (Cargo.lock still wanted? — skip for now)
    ".snap",     // jest snapshots
];

/// Discover indexable text files under `root`, respecting `.gitignore` and
/// skipping binaries / oversized files.
pub fn walk_text_files(root: &Path, config: &IndexConfig) -> Vec<PathBuf> {
    let mut files = Vec::new();

    let mut builder = WalkBuilder::new(root);
    builder.standard_filters(true);
    // ignore 크레이트는 기본적으로 **git 저장소 안에서만** `.gitignore` 를 적용한다
    // (`require_git(true)`). `git init` 을 안 한 프로젝트에서 `.gitignore` 에
    // `node_modules` 가 있는데도 21K 청크·118MB 가 색인된 사고(2026-08-30)의
    // 원인이다. 워처 쪽(`watcher.rs load_project_gitignore`)은 파일을 직접 읽어
    // git 유무와 무관하게 적용하므로, 걷기도 같은 의미로 맞춘다.
    builder.require_git(false);
    builder.filter_entry(|entry| {
        !(entry.file_type().is_some_and(|t| t.is_dir()) && is_denied_dir_name(entry.path()))
    });

    // Apply user-supplied glob patterns as gitignore-style overrides.
    if !config.extra_exclude_patterns.is_empty() {
        let mut overrides = OverrideBuilder::new(root);
        for pat in &config.extra_exclude_patterns {
            let trimmed = pat.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            // OverrideBuilder treats `!pattern` as an *un-ignore*, so to
            // exclude a path we add the pattern as-is.
            let _ = overrides.add(&format!("!{}", trimmed));
        }
        if let Ok(ov) = overrides.build() {
            builder.overrides(ov);
        }
    }

    let walker = builder.build();
    for entry in walker.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if is_skipped_name(path) {
            continue;
        }
        let Ok(metadata) = entry.metadata() else { continue };
        if metadata.len() == 0 || metadata.len() > config.max_file_bytes {
            continue;
        }
        if looks_binary(path) {
            continue;
        }
        files.push(path.to_path_buf());
    }
    files
}

/// Whether a single file qualifies for indexing — the per-file half of
/// `walk_text_files` (skip-name, size cap, binary probe), minus the directory
/// walk + gitignore (the watcher already applies gitignore before calling).
/// Used by the watcher's incremental reindex so a lock file or binary blob
/// touched on disk doesn't get embedded.
pub fn is_indexable_path(path: &Path, config: &IndexConfig) -> bool {
    if is_skipped_name(path) || has_denied_component(path) {
        return false;
    }
    let Ok(metadata) = std::fs::metadata(path) else {
        return false;
    };
    if metadata.len() == 0 || metadata.len() > config.max_file_bytes {
        return false;
    }
    !looks_binary(path)
}

/// 읽은 내용이 색인할 가치가 있는가 — minified/생성 파일 판정. 경로·크기
/// 검사([`is_indexable_path`]) 를 통과한 뒤, 본문을 읽은 자리에서 한 번 더
/// 거른다. 파일 전체를 거부하는 이유: 긴 줄만 빼면 줄 범위 의미가 깨진다.
pub fn is_indexable_content(content: &str) -> bool {
    !content.lines().any(|line| line.len() > MAX_LINE_BYTES)
}

fn is_denied_dir_name(path: &Path) -> bool {
    path.file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|name| DENY_DIR_NAMES.contains(&name))
}

/// 경로 구성 요소 중 하나라도 [`DENY_DIR_NAMES`] 에 있으면 true — 워처처럼
/// 걷기를 거치지 않고 경로 하나를 판정할 때 쓴다.
fn has_denied_component(path: &Path) -> bool {
    path.components().any(|c| {
        matches!(c, Component::Normal(name)
            if name.to_str().is_some_and(|n| DENY_DIR_NAMES.contains(&n)))
    })
}

fn is_skipped_name(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
        return false;
    };
    if SKIP_FILENAMES.contains(&name) {
        return true;
    }
    SKIP_SUFFIXES.iter().any(|s| name.ends_with(s))
}

/// Heuristic: a file is treated as binary if its first KB contains a NUL byte.
fn looks_binary(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else {
        return true;
    };
    let mut buf = [0u8; MAX_BINARY_PROBE];
    let Ok(n) = f.read(&mut buf) else {
        return true;
    };
    buf[..n].contains(&0)
}

#[derive(Debug)]
pub struct Chunk {
    pub kind: &'static str,
    pub start_line: u32,
    pub end_line: u32,
    pub content: String,
}

/// Normalizes a path, removing redundant '.' and '..' components.
pub fn clean_path(path: &Path) -> PathBuf {
    use std::path::Component;
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::ParentDir => {
                out.pop();
            }
            Component::Normal(c) => {
                out.push(c);
            }
            Component::CurDir => {}
            _ => {
                out.push(component.as_os_str());
            }
        }
    }
    out
}

/// A single tsconfig-style path alias mapping (e.g. `"@/*": ["./src/*"]`).
#[derive(Debug, Clone, Default)]
pub struct PathAliases {
    /// (alias_prefix_without_star, list_of_replacement_prefixes_without_star)
    pub entries: Vec<(String, Vec<String>)>,
}

impl PathAliases {
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Best-effort tsconfig.json paths loader. Scans `tsconfig.json` and
/// `tsconfig.app.json` at the project root for a `compilerOptions.paths` map.
/// Strips leading `./` from replacements and normalizes trailing `*`.
pub fn load_path_aliases(project_root: &Path) -> PathAliases {
    let mut aliases = PathAliases::default();
    for fname in ["tsconfig.json", "tsconfig.app.json", "jsconfig.json"] {
        let p = project_root.join(fname);
        let Ok(text) = std::fs::read_to_string(&p) else { continue };
        // Strip // and /* */ comments — tsconfig allows them
        let cleaned = strip_jsonc_comments(&text);
        let Ok(json) = serde_json::from_str::<serde_json::Value>(&cleaned) else { continue };
        let Some(paths) = json
            .get("compilerOptions")
            .and_then(|c| c.get("paths"))
            .and_then(|p| p.as_object())
        else {
            continue;
        };
        for (pattern, replacements) in paths {
            let Some(arr) = replacements.as_array() else { continue };
            // Strip trailing /* or *
            let alias_prefix = pattern
                .trim_end_matches('*')
                .trim_end_matches('/')
                .to_string();
            let alias_prefix = if alias_prefix.is_empty() {
                pattern.clone()
            } else {
                format!("{}/", alias_prefix)
            };
            let repl_prefixes: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str())
                .map(|s| {
                    let s = s.trim_end_matches('*').trim_end_matches('/');
                    let s = s.trim_start_matches("./");
                    if s.is_empty() {
                        String::new()
                    } else {
                        format!("{}/", s)
                    }
                })
                .collect();
            if !repl_prefixes.is_empty() {
                aliases.entries.push((alias_prefix, repl_prefixes));
            }
        }
        // First config that exists wins to avoid duplicates
        if !aliases.is_empty() {
            break;
        }
    }
    aliases
}

/// Strip `//` line comments and `/* ... */` block comments from JSON-with-comments.
fn strip_jsonc_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    let mut in_str = false;
    let mut esc = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_str {
            out.push(b as char);
            if esc {
                esc = false;
            } else if b == b'\\' {
                esc = true;
            } else if b == b'"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_str = true;
            out.push('"');
            i += 1;
            continue;
        }
        if b == b'/' && i + 1 < bytes.len() {
            if bytes[i + 1] == b'/' {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            if bytes[i + 1] == b'*' {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i = (i + 2).min(bytes.len());
                continue;
            }
        }
        out.push(b as char);
        i += 1;
    }
    out
}

/// File-extension candidates to try when resolving a relative import. Driven by
/// the *source* file's extension since that determines the import semantics.
fn candidate_extensions(source_ext: &str) -> &'static [&'static str] {
    match source_ext {
        "ts" | "tsx" | "js" | "jsx" | "mjs" | "cjs" => &[
            "", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
            "/index.ts", "/index.tsx", "/index.js", "/index.jsx",
        ],
        "py" => &["", ".py", "/__init__.py"],
        "rb" => &["", ".rb"],
        "php" => &["", ".php"],
        "c" | "h" | "cpp" | "cc" | "cxx" | "hpp" | "hxx" | "hh" => &["", ".h", ".hpp", ".hxx"],
        "rs" => &["", ".rs", "/mod.rs"],
        "go" => &["", ".go"],
        _ => &[
            "", ".ts", ".tsx", ".js", ".jsx",
            "/index.ts", "/index.tsx", "/index.js", "/index.jsx",
        ],
    }
}

fn try_candidates(
    target_rel_str: &str,
    source_ext: &str,
    project_files: &std::collections::HashMap<String, u32>,
) -> Option<u32> {
    for suffix in candidate_extensions(source_ext) {
        let candidate = format!("{}{}", target_rel_str, suffix);
        if let Some(&file_id) = project_files.get(&candidate) {
            return Some(file_id);
        }
    }
    None
}

/// Resolves an import path to a target file ID in the project files map.
pub fn resolve_import(
    project_root: &Path,
    source_rel_path: &str,
    import_str: &str,
    project_files: &std::collections::HashMap<String, u32>,
    path_aliases: &PathAliases,
) -> Option<u32> {
    let source_abs_path = project_root.join(source_rel_path);
    let parent_dir = source_abs_path.parent()?;
    let source_ext = Path::new(source_rel_path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");

    // Case 0: tsconfig path aliases (e.g. "@/foo" → "src/foo")
    for (alias_prefix, repls) in &path_aliases.entries {
        if let Some(suffix) = import_str.strip_prefix(alias_prefix) {
            for repl in repls {
                let mapped = format!("{}{}", repl, suffix);
                let target_abs = clean_path(&project_root.join(&mapped));
                if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
                    let target_rel_str = target_rel.to_string_lossy().to_string();
                    if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                        return Some(id);
                    }
                }
            }
        }
    }

    // Case 1a: Python-style relative import — leading dots without a slash.
    //   from .utils import x         → leading_dots=1, rest="utils"
    //   from ..pkg.subpkg import y   → leading_dots=2, rest="pkg.subpkg"
    //   from . import x              → leading_dots=1, rest=""
    if source_ext == "py" && import_str.starts_with('.') && !import_str.contains('/') {
        let leading_dots = import_str.chars().take_while(|c| *c == '.').count();
        let rest = &import_str[leading_dots..];

        // First leading dot = current package; each additional dot moves up one.
        let mut base_dir = parent_dir.to_path_buf();
        for _ in 1..leading_dots {
            if let Some(p) = base_dir.parent() {
                base_dir = p.to_path_buf();
            }
        }

        let target_abs = if rest.is_empty() {
            base_dir.clone()
        } else {
            base_dir.join(rest.replace('.', "/"))
        };
        if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, "py", project_files) {
                return Some(id);
            }
        }
    }

    // Case 1b: Unix-style relative path (./foo, ../foo) for TS/JS/C/Ruby/etc.
    if import_str.starts_with('.') && (import_str.contains('/') || import_str.contains('\\')) {
        let target_abs = clean_path(&parent_dir.join(import_str));
        if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                return Some(id);
            }
        }
    }

    // Case 1c: Pure "./" or "." path (current dir)
    if (import_str == "." || import_str == "./") && source_ext != "py" {
        if let Ok(target_rel) = parent_dir.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                return Some(id);
            }
        }
    }

    // Case 2: Rust :: paths (crate::, super::, self::, or anything containing ::)
    if import_str.contains("::") || source_ext == "rs" {
        let segments: Vec<&str> = import_str.split("::").filter(|s| !s.is_empty()).collect();
        if !segments.is_empty() {
            // Walk up to nearest Cargo.toml to find crate src/
            let mut crate_root: Option<PathBuf> = None;
            let mut current = source_abs_path.parent();
            while let Some(dir) = current {
                if dir.join("Cargo.toml").exists() {
                    crate_root = Some(dir.join("src"));
                    break;
                }
                if dir == project_root {
                    break;
                }
                current = dir.parent();
            }

            let start_idx = match segments[0] {
                "crate" | "super" | "self" => 1,
                _ => 0,
            };

            let base_dir = if segments[0] == "crate" {
                crate_root.clone()?
            } else if segments[0] == "super" {
                parent_dir.parent().unwrap_or(parent_dir).to_path_buf()
            } else {
                parent_dir.to_path_buf()
            };

            // Try decreasing matching prefix lengths
            let remaining = segments.len().saturating_sub(start_idx);
            for len in (1..=remaining).rev() {
                let sub_segs = &segments[start_idx..(start_idx + len)];
                let sub_path = sub_segs.join("/");
                let full_target = base_dir.join(&sub_path);

                if let Ok(rel_path) = full_target.strip_prefix(project_root) {
                    let rel_str = rel_path.to_string_lossy().to_string();
                    if let Some(id) = try_candidates(&rel_str, "rs", project_files) {
                        return Some(id);
                    }
                }
            }
        }
    }

    // Case 3: Suffix-segment match for absolute module paths
    // (Python `import pkg.mod`, Go `github.com/x/y`, Java `com.foo.Bar`, etc.)
    let mut import_normalized = import_str.replace("::", "/").replace('\\', "/");
    if !import_str.starts_with('.') {
        import_normalized = import_normalized.replace('.', "/");
    }
    let segments: Vec<&str> = import_normalized
        .split('/')
        .filter(|s| !s.is_empty())
        .collect();
    if !segments.is_empty() {
        // Special-cased file stems that act as "package init" / "barrel" files
        const WILDCARD_STEMS: &[&str] = &["mod", "index", "__init__", "package", "lib", "main"];

        // Iterate files; for each, compare the suffix of the file path against
        // the suffix of the import. This makes nested project layouts resolve
        // correctly (e.g. src/app/models/user.py for `app.models.user`).
        for (file_path, &file_id) in project_files {
            let file_normalized = file_path.replace('\\', "/");
            let file_parts: Vec<&str> = file_normalized.split('/').collect();
            if file_parts.is_empty() {
                continue;
            }

            for seg_len in (1..=segments.len()).rev() {
                if file_parts.len() < seg_len {
                    continue;
                }
                let import_suffix = &segments[segments.len() - seg_len..];
                let file_suffix_start = file_parts.len() - seg_len;

                let mut matches = true;
                for i in 0..seg_len {
                    let raw = file_parts[file_suffix_start + i];
                    // Strip extension on the final filename
                    let stem = if file_suffix_start + i == file_parts.len() - 1 {
                        raw.rsplit_once('.').map(|p| p.0).unwrap_or(raw)
                    } else {
                        raw
                    };
                    if stem != import_suffix[i] && !WILDCARD_STEMS.contains(&stem) {
                        matches = false;
                        break;
                    }
                }
                if matches {
                    return Some(file_id);
                }
            }
        }
    }

    None
}

/// Split file content into chunks using AST nodes (symbols) if available, with line-based fallback.
pub fn chunk_file(
    path: &Path,
    content: &str,
    config: &IndexConfig,
) -> (Vec<Chunk>, Option<crate::ast::AstAnalysis>) {
    let analysis = crate::ast::analyze_file(path, content);
    let mut chunks = Vec::new();

    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() {
        return (chunks, analysis);
    }

    if let Some(ref ana) = analysis {
        if !ana.symbols.is_empty() {
            let mut symbols = ana.symbols.clone();
            symbols.sort_by_key(|s| s.start_line);

            let mut last_covered_line = 0usize;
            // 같은 줄 범위의 심볼은 하나만 청크가 된다. 한 줄에 심볼이 수백 개인
            // 파일(번들·minified)에서 심볼마다 그 줄 전체가 복제되던 것을 막는다 —
            // `is_indexable_content` 가 앞에서 거르지만, 4KB 안쪽의 빽빽한 줄도
            // 같은 병리를 작게 반복한다.
            let mut seen_ranges: HashSet<(u32, u32)> = HashSet::new();

            for sym in symbols {
                let start_idx = (sym.start_line as usize).saturating_sub(1);
                let end_idx = (sym.end_line as usize).min(lines.len());

                if !seen_ranges.insert((sym.start_line, sym.end_line)) {
                    last_covered_line = last_covered_line.max(end_idx);
                    continue;
                }

                if start_idx > last_covered_line {
                    let uncovered_content = lines[last_covered_line..start_idx].join("\n");
                    if meaningful_line_count(&uncovered_content) >= MIN_GAP_CHUNK_LINES {
                        let sub_chunks = chunk_lines_with_offset(
                            &uncovered_content,
                            last_covered_line + 1,
                            config,
                        );
                        chunks.extend(sub_chunks);
                    }
                }

                if start_idx < end_idx {
                    let body = lines[start_idx..end_idx].join("\n");
                    if !body.trim().is_empty() {
                        let header = format!("// AST Symbol: {} ({})\n", sym.name, sym.kind);
                        if body.len() <= MAX_CHUNK_BYTES {
                            chunks.push(Chunk {
                                kind: "ast",
                                start_line: sym.start_line,
                                end_line: sym.end_line,
                                content: format!("{header}{body}"),
                            });
                        } else {
                            // 거대 심볼(수천 줄 컴포넌트·모듈 단위 클래스)은 창으로
                            // 쪼개되 머리줄은 각 창에 남겨 임베딩이 소속을 안다.
                            for window in chunk_lines_with_offset(&body, sym.start_line as usize, config) {
                                chunks.push(Chunk {
                                    kind: "ast",
                                    start_line: window.start_line,
                                    end_line: window.end_line,
                                    content: format!("{header}{}", window.content),
                                });
                            }
                        }
                    }
                }

                last_covered_line = last_covered_line.max(end_idx);
            }

            if last_covered_line < lines.len() {
                let uncovered_content = lines[last_covered_line..].join("\n");
                if meaningful_line_count(&uncovered_content) >= MIN_GAP_CHUNK_LINES {
                    let sub_chunks = chunk_lines_with_offset(
                        &uncovered_content,
                        last_covered_line + 1,
                        config,
                    );
                    chunks.extend(sub_chunks);
                }
            }

            return (chunks, analysis);
        }
    }

    let sub_chunks = chunk_lines_with_offset(content, 1, config);
    (sub_chunks, None)
}

/// Count lines that carry real content — non-blank lines with at least one
/// alphanumeric character. Pure-punctuation lines (`}`, `);`, `{`) and blanks
/// don't count, so a between-symbol gap that is only braces (or a single
/// `import`) is treated as noise rather than an indexable chunk (Bug 2).
fn meaningful_line_count(content: &str) -> usize {
    content
        .lines()
        .filter(|l| l.chars().any(|c| c.is_alphanumeric()))
        .count()
}

/// Fallback helper to split a text range into sliding line windows.
pub fn chunk_lines_with_offset(
    content: &str,
    line_offset: usize,
    config: &IndexConfig,
) -> Vec<Chunk> {
    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() {
        return Vec::new();
    }

    let chunk_lines = config.chunk_lines.max(1);
    let chunk_overlap = config.chunk_overlap.min(chunk_lines.saturating_sub(1));

    let mut chunks = Vec::new();
    let mut start = 0usize;

    while start < lines.len() {
        let mut end = (start + chunk_lines).min(lines.len());
        // 바이트 상한 — 줄이 길면 창을 줄여 맞춘다 (최소 1줄). 줄 하나가 상한을
        // 넘는 파일은 `is_indexable_content` 가 앞에서 거르므로 여기선 안 생긴다.
        let mut bytes: usize = lines[start..end].iter().map(|l| l.len() + 1).sum();
        while bytes > MAX_CHUNK_BYTES && end - start > 1 {
            end -= 1;
            bytes -= lines[end].len() + 1;
        }
        let body = lines[start..end].join("\n");
        if !body.trim().is_empty() {
            chunks.push(Chunk {
                kind: "lines",
                start_line: (start + line_offset) as u32,
                end_line: (end + line_offset - 1) as u32,
                content: body,
            });
        }
        if end == lines.len() {
            break;
        }
        // 겹침은 실제 창 크기 기준 — 창이 줄었어도 줄을 건너뛰지 않고, 항상 전진한다.
        start += (end - start).saturating_sub(chunk_overlap).max(1);
    }
    chunks
}

/// Settings-table keys that influence indexing behavior. Kept in sync with the
/// frontend `settings.ts`.
pub const SETTING_CHUNK_SIZE: &str = "chunk_size";
pub const SETTING_CHUNK_OVERLAP: &str = "chunk_overlap";
pub const SETTING_MAX_FILE_KB: &str = "max_file_size_kb";
pub const SETTING_EXCLUDE_PATTERNS: &str = "exclude_patterns";

/// Build an IndexConfig from a settings map. Missing/invalid values fall back
/// to the defaults so the indexer is always safe to call.
pub fn config_from_settings(
    get: impl Fn(&str) -> Option<String>,
) -> IndexConfig {
    let chunk_lines = get(SETTING_CHUNK_SIZE)
        .and_then(|s| s.parse::<usize>().ok())
        .filter(|n| *n > 0 && *n <= 500)
        .unwrap_or(DEFAULT_CHUNK_LINES);

    let chunk_overlap = get(SETTING_CHUNK_OVERLAP)
        .and_then(|s| s.parse::<usize>().ok())
        .filter(|n| *n < chunk_lines)
        .unwrap_or(DEFAULT_CHUNK_OVERLAP);

    let max_file_bytes = get(SETTING_MAX_FILE_KB)
        .and_then(|s| s.parse::<u64>().ok())
        .filter(|n| *n > 0)
        .map(|kb| kb * 1024)
        .unwrap_or(DEFAULT_MAX_FILE_BYTES);

    let extra_exclude_patterns = get(SETTING_EXCLUDE_PATTERNS)
        .map(|s| {
            s.lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect()
        })
        .unwrap_or_default();

    IndexConfig {
        chunk_lines,
        chunk_overlap,
        max_file_bytes,
        extra_exclude_patterns,
    }
}

/// Guess a language tag from the file extension. Used purely as a hint stored
/// alongside file metadata.
pub fn language_for(path: &Path) -> Option<&'static str> {
    match path.extension()?.to_str()? {
        "rs" => Some("rust"),
        "ts" | "tsx" => Some("typescript"),
        "js" | "jsx" | "mjs" | "cjs" => Some("javascript"),
        "py" => Some("python"),
        "go" => Some("go"),
        "java" => Some("java"),
        "kt" | "kts" => Some("kotlin"),
        "swift" => Some("swift"),
        "c" | "h" => Some("c"),
        "cpp" | "cc" | "cxx" | "hpp" => Some("cpp"),
        "cs" => Some("csharp"),
        "rb" => Some("ruby"),
        "php" => Some("php"),
        "sh" | "bash" | "zsh" => Some("shell"),
        "md" | "mdx" => Some("markdown"),
        "json" => Some("json"),
        "yaml" | "yml" => Some("yaml"),
        "toml" => Some("toml"),
        "sql" => Some("sql"),
        "html" | "htm" => Some("html"),
        "css" | "scss" | "sass" => Some("css"),
        _ => None,
    }
}

#[cfg(test)]
mod chunk_tests {
    use super::*;

    #[test]
    fn meaningful_line_count_ignores_blanks_and_punctuation() {
        assert_eq!(meaningful_line_count("}"), 0);
        assert_eq!(meaningful_line_count("}\n);\n  {"), 0);
        assert_eq!(meaningful_line_count("\n\n  \n"), 0);
        assert_eq!(meaningful_line_count("import x from 'y';"), 1);
        assert_eq!(meaningful_line_count("let a = 1;\nlet b = 2;\nlet c = 3;"), 3);
    }

    #[test]
    fn tiny_punctuation_only_range_below_threshold() {
        // A lone closing-brace / single-import gap is below MIN_GAP_CHUNK_LINES
        // and would be skipped at the gap sites in chunk_file.
        assert!(meaningful_line_count("}") < MIN_GAP_CHUNK_LINES);
        assert!(meaningful_line_count("import a from 'a';") < MIN_GAP_CHUNK_LINES);
        // A real 3-line block clears the bar.
        assert!(meaningful_line_count("a()\nb()\nc()") >= MIN_GAP_CHUNK_LINES);
    }

    /// 2026-08-30 실측 재현: 한 줄에 심볼 N개인 파일은 청크 N개가 아니라 1개다.
    /// (libktx.js — 22줄·심볼 503개 → 청크 503개·104MB 이던 병리.)
    #[test]
    fn same_line_symbols_collapse_to_one_chunk() {
        let one_line: String = (0..40)
            .map(|i| format!("function f{i}() {{ return {i}; }}"))
            .collect::<Vec<_>>()
            .join(" ");
        let (chunks, analysis) =
            chunk_file(Path::new("bundle.js"), &one_line, &IndexConfig::default());
        let symbols = analysis.map(|a| a.symbols.len()).unwrap_or(0);
        assert!(symbols >= 40, "tree-sitter 가 심볼을 뽑아야 재현이 성립한다: {symbols}");
        assert_eq!(chunks.len(), 1, "같은 줄 범위는 한 번만: {:?}", chunks.len());
    }

    /// 거대 심볼(수천 줄 함수)은 하나의 청크가 아니라 상한 안의 창으로 쪼개진다.
    #[test]
    fn giant_symbol_is_windowed_under_byte_cap() {
        let body: String = (0..3000)
            .map(|i| format!("  const v{i} = {i}; // padding line"))
            .collect::<Vec<_>>()
            .join("\n");
        let src = format!("function giant() {{\n{body}\n}}\n");
        let (chunks, _) = chunk_file(Path::new("giant.js"), &src, &IndexConfig::default());
        assert!(chunks.len() > 1);
        for c in &chunks {
            assert!(
                c.content.len() <= MAX_CHUNK_BYTES + 64,
                "청크 {}..{} 가 {}B — 상한 초과",
                c.start_line,
                c.end_line,
                c.content.len()
            );
        }
        // 창들이 본문을 빠짐없이 덮는다 (마지막 창의 끝 = 마지막 줄).
        let last = chunks.iter().map(|c| c.end_line).max().unwrap();
        assert_eq!(last as usize, src.lines().count());
    }

    /// 줄이 길면 창이 줄어든다 — 30줄 × 1KB 는 16KB 안에 못 들어가므로 여러 창.
    #[test]
    fn line_windows_shrink_to_byte_cap_without_skipping_lines() {
        let src: String = (0..30)
            .map(|i| format!("{i:03}{}", "x".repeat(1000)))
            .collect::<Vec<_>>()
            .join("\n");
        let chunks = chunk_lines_with_offset(&src, 1, &IndexConfig::default());
        assert!(chunks.len() >= 2);
        for c in &chunks {
            assert!(c.content.len() <= MAX_CHUNK_BYTES);
        }
        assert_eq!(chunks[0].start_line, 1);
        assert_eq!(chunks.last().unwrap().end_line, 30);
        // 겹침(4줄)을 빼고도 다음 창이 이전 창 안에서 시작한다 — 줄을 건너뛰지 않는다.
        for w in chunks.windows(2) {
            assert!(w[1].start_line <= w[0].end_line + 1);
        }
    }

    #[test]
    fn minified_content_is_not_indexable() {
        let minified = format!("var a=1;{}", "b=a+1;".repeat(1000));
        assert!(minified.len() > MAX_LINE_BYTES);
        assert!(!is_indexable_content(&minified));
        assert!(is_indexable_content("fn main() {}\nfn helper() {}\n"));
    }
}

#[cfg(test)]
mod walk_tests {
    use super::*;
    use std::fs;

    fn write(root: &Path, rel: &str, body: &str) {
        let p = root.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(p, body).unwrap();
    }

    fn rel_paths(root: &Path, config: &IndexConfig) -> Vec<String> {
        let mut v: Vec<String> = walk_text_files(root, config)
            .into_iter()
            .map(|p| p.strip_prefix(root).unwrap().to_string_lossy().into_owned())
            .collect();
        v.sort();
        v
    }

    /// 2026-08-30 사고 재현: `.git` 이 없어도 `.gitignore` 는 적용돼야 한다.
    #[test]
    fn gitignore_is_honored_without_a_git_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".gitignore", "generated/\n");
        write(root, "src/a.ts", "export const a = 1;\n");
        write(root, "generated/big.ts", "export const g = 1;\n");
        assert!(!root.join(".git").exists());
        assert_eq!(rel_paths(root, &IndexConfig::default()), vec!["src/a.ts"]);
    }

    /// `.gitignore` 자체가 없어도 벤더 디렉터리는 절대 걷지 않는다.
    #[test]
    fn vendor_dirs_are_denied_without_any_gitignore() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, "src/a.ts", "export const a = 1;\n");
        write(root, "node_modules/pkg/index.js", "module.exports = 1;\n");
        write(root, "nested/node_modules/pkg/index.js", "module.exports = 1;\n");
        write(root, "target/debug/build.rs", "fn main() {}\n");
        write(root, "__pycache__/x.pyc.py", "x = 1\n");
        assert_eq!(rel_paths(root, &IndexConfig::default()), vec!["src/a.ts"]);
        // 워처 경로 판정도 같은 그물을 쓴다.
        assert!(!is_indexable_path(
            &root.join("node_modules/pkg/index.js"),
            &IndexConfig::default()
        ));
        assert!(is_indexable_path(&root.join("src/a.ts"), &IndexConfig::default()));
    }
}
