//! Project file walking, line-based chunking, and indexing pipeline.

use std::path::{Path, PathBuf};

use ignore::{overrides::OverrideBuilder, WalkBuilder};

pub const DEFAULT_MAX_FILE_BYTES: u64 = 500_000; // 500 KB
pub const DEFAULT_CHUNK_LINES: usize = 30;
pub const DEFAULT_CHUNK_OVERLAP: usize = 4;
const MAX_BINARY_PROBE: usize = 1024;

/// Runtime configuration loaded from the `settings` table. All knobs have
/// sensible defaults that match the previous hardcoded values.
#[derive(Debug, Clone)]
pub struct IndexConfig {
    pub max_file_bytes: u64,
    pub chunk_lines: usize,
    pub chunk_overlap: usize,
    /// Extra gitignore-style patterns added on top of the project's .gitignore.
    pub extra_exclude_patterns: Vec<String>,
}

impl Default for IndexConfig {
    fn default() -> Self {
        Self {
            max_file_bytes: DEFAULT_MAX_FILE_BYTES,
            chunk_lines: DEFAULT_CHUNK_LINES,
            chunk_overlap: DEFAULT_CHUNK_OVERLAP,
            extra_exclude_patterns: Vec::new(),
        }
    }
}

/// Filenames that are noise for semantic code search — typically autogenerated
/// or huge serialized blobs.
const SKIP_FILENAMES: &[&str] = &[
    "pnpm-lock.yaml",
    "package-lock.json",
    "yarn.lock",
    "bun.lockb",
    "composer.lock",
    "poetry.lock",
    "uv.lock",
];

/// Filename suffix patterns to skip.
const SKIP_SUFFIXES: &[&str] = &[
    ".min.js",
    ".min.css",
    ".min.mjs",
    ".map",      // sourcemaps
    ".lock",     // generic lock files (Cargo.lock still wanted? — skip for now)
    ".snap",     // jest snapshots
];

/// Discover indexable text files under `root`, respecting `.gitignore` and
/// skipping binaries / oversized files.
pub fn walk_text_files(root: &Path, config: &IndexConfig) -> Vec<PathBuf> {
    let mut files = Vec::new();

    let mut builder = WalkBuilder::new(root);
    builder.standard_filters(true);

    // Apply user-supplied glob patterns as gitignore-style overrides.
    if !config.extra_exclude_patterns.is_empty() {
        let mut overrides = OverrideBuilder::new(root);
        for pat in &config.extra_exclude_patterns {
            let trimmed = pat.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            // OverrideBuilder treats `!pattern` as an *un-ignore*, so to
            // exclude a path we add the pattern as-is.
            let _ = overrides.add(&format!("!{}", trimmed));
        }
        if let Ok(ov) = overrides.build() {
            builder.overrides(ov);
        }
    }

    let walker = builder.build();
    for entry in walker.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if is_skipped_name(path) {
            continue;
        }
        let Ok(metadata) = entry.metadata() else { continue };
        if metadata.len() == 0 || metadata.len() > config.max_file_bytes {
            continue;
        }
        if looks_binary(path) {
            continue;
        }
        files.push(path.to_path_buf());
    }
    files
}

fn is_skipped_name(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
        return false;
    };
    if SKIP_FILENAMES.contains(&name) {
        return true;
    }
    SKIP_SUFFIXES.iter().any(|s| name.ends_with(s))
}

/// Heuristic: a file is treated as binary if its first KB contains a NUL byte.
fn looks_binary(path: &Path) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(path) else {
        return true;
    };
    let mut buf = [0u8; MAX_BINARY_PROBE];
    let Ok(n) = f.read(&mut buf) else {
        return true;
    };
    buf[..n].contains(&0)
}

#[derive(Debug)]
pub struct Chunk {
    pub kind: &'static str,
    pub start_line: u32,
    pub end_line: u32,
    pub content: String,
}

/// Normalizes a path, removing redundant '.' and '..' components.
pub fn clean_path(path: &Path) -> PathBuf {
    use std::path::Component;
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            Component::ParentDir => {
                out.pop();
            }
            Component::Normal(c) => {
                out.push(c);
            }
            Component::CurDir => {}
            _ => {
                out.push(component.as_os_str());
            }
        }
    }
    out
}

/// A single tsconfig-style path alias mapping (e.g. `"@/*": ["./src/*"]`).
#[derive(Debug, Clone, Default)]
pub struct PathAliases {
    /// (alias_prefix_without_star, list_of_replacement_prefixes_without_star)
    pub entries: Vec<(String, Vec<String>)>,
}

impl PathAliases {
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }
}

/// Best-effort tsconfig.json paths loader. Scans `tsconfig.json` and
/// `tsconfig.app.json` at the project root for a `compilerOptions.paths` map.
/// Strips leading `./` from replacements and normalizes trailing `*`.
pub fn load_path_aliases(project_root: &Path) -> PathAliases {
    let mut aliases = PathAliases::default();
    for fname in ["tsconfig.json", "tsconfig.app.json", "jsconfig.json"] {
        let p = project_root.join(fname);
        let Ok(text) = std::fs::read_to_string(&p) else { continue };
        // Strip // and /* */ comments — tsconfig allows them
        let cleaned = strip_jsonc_comments(&text);
        let Ok(json) = serde_json::from_str::<serde_json::Value>(&cleaned) else { continue };
        let Some(paths) = json
            .get("compilerOptions")
            .and_then(|c| c.get("paths"))
            .and_then(|p| p.as_object())
        else {
            continue;
        };
        for (pattern, replacements) in paths {
            let Some(arr) = replacements.as_array() else { continue };
            // Strip trailing /* or *
            let alias_prefix = pattern
                .trim_end_matches('*')
                .trim_end_matches('/')
                .to_string();
            let alias_prefix = if alias_prefix.is_empty() {
                pattern.clone()
            } else {
                format!("{}/", alias_prefix)
            };
            let repl_prefixes: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str())
                .map(|s| {
                    let s = s.trim_end_matches('*').trim_end_matches('/');
                    let s = s.trim_start_matches("./");
                    if s.is_empty() {
                        String::new()
                    } else {
                        format!("{}/", s)
                    }
                })
                .collect();
            if !repl_prefixes.is_empty() {
                aliases.entries.push((alias_prefix, repl_prefixes));
            }
        }
        // First config that exists wins to avoid duplicates
        if !aliases.is_empty() {
            break;
        }
    }
    aliases
}

/// Strip `//` line comments and `/* ... */` block comments from JSON-with-comments.
fn strip_jsonc_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let bytes = text.as_bytes();
    let mut i = 0;
    let mut in_str = false;
    let mut esc = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_str {
            out.push(b as char);
            if esc {
                esc = false;
            } else if b == b'\\' {
                esc = true;
            } else if b == b'"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        if b == b'"' {
            in_str = true;
            out.push('"');
            i += 1;
            continue;
        }
        if b == b'/' && i + 1 < bytes.len() {
            if bytes[i + 1] == b'/' {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
                continue;
            }
            if bytes[i + 1] == b'*' {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i = (i + 2).min(bytes.len());
                continue;
            }
        }
        out.push(b as char);
        i += 1;
    }
    out
}

/// File-extension candidates to try when resolving a relative import. Driven by
/// the *source* file's extension since that determines the import semantics.
fn candidate_extensions(source_ext: &str) -> &'static [&'static str] {
    match source_ext {
        "ts" | "tsx" | "js" | "jsx" | "mjs" | "cjs" => &[
            "", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
            "/index.ts", "/index.tsx", "/index.js", "/index.jsx",
        ],
        "py" => &["", ".py", "/__init__.py"],
        "rb" => &["", ".rb"],
        "php" => &["", ".php"],
        "c" | "h" | "cpp" | "cc" | "cxx" | "hpp" | "hxx" | "hh" => &["", ".h", ".hpp", ".hxx"],
        "rs" => &["", ".rs", "/mod.rs"],
        "go" => &["", ".go"],
        _ => &[
            "", ".ts", ".tsx", ".js", ".jsx",
            "/index.ts", "/index.tsx", "/index.js", "/index.jsx",
        ],
    }
}

fn try_candidates(
    target_rel_str: &str,
    source_ext: &str,
    project_files: &std::collections::HashMap<String, u32>,
) -> Option<u32> {
    for suffix in candidate_extensions(source_ext) {
        let candidate = format!("{}{}", target_rel_str, suffix);
        if let Some(&file_id) = project_files.get(&candidate) {
            return Some(file_id);
        }
    }
    None
}

/// Resolves an import path to a target file ID in the project files map.
pub fn resolve_import(
    project_root: &Path,
    source_rel_path: &str,
    import_str: &str,
    project_files: &std::collections::HashMap<String, u32>,
    path_aliases: &PathAliases,
) -> Option<u32> {
    let source_abs_path = project_root.join(source_rel_path);
    let parent_dir = source_abs_path.parent()?;
    let source_ext = Path::new(source_rel_path)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("");

    // Case 0: tsconfig path aliases (e.g. "@/foo" → "src/foo")
    for (alias_prefix, repls) in &path_aliases.entries {
        if let Some(suffix) = import_str.strip_prefix(alias_prefix) {
            for repl in repls {
                let mapped = format!("{}{}", repl, suffix);
                let target_abs = clean_path(&project_root.join(&mapped));
                if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
                    let target_rel_str = target_rel.to_string_lossy().to_string();
                    if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                        return Some(id);
                    }
                }
            }
        }
    }

    // Case 1a: Python-style relative import — leading dots without a slash.
    //   from .utils import x         → leading_dots=1, rest="utils"
    //   from ..pkg.subpkg import y   → leading_dots=2, rest="pkg.subpkg"
    //   from . import x              → leading_dots=1, rest=""
    if source_ext == "py" && import_str.starts_with('.') && !import_str.contains('/') {
        let leading_dots = import_str.chars().take_while(|c| *c == '.').count();
        let rest = &import_str[leading_dots..];

        // First leading dot = current package; each additional dot moves up one.
        let mut base_dir = parent_dir.to_path_buf();
        for _ in 1..leading_dots {
            if let Some(p) = base_dir.parent() {
                base_dir = p.to_path_buf();
            }
        }

        let target_abs = if rest.is_empty() {
            base_dir.clone()
        } else {
            base_dir.join(rest.replace('.', "/"))
        };
        if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, "py", project_files) {
                return Some(id);
            }
        }
    }

    // Case 1b: Unix-style relative path (./foo, ../foo) for TS/JS/C/Ruby/etc.
    if import_str.starts_with('.') && (import_str.contains('/') || import_str.contains('\\')) {
        let target_abs = clean_path(&parent_dir.join(import_str));
        if let Ok(target_rel) = target_abs.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                return Some(id);
            }
        }
    }

    // Case 1c: Pure "./" or "." path (current dir)
    if (import_str == "." || import_str == "./") && source_ext != "py" {
        if let Ok(target_rel) = parent_dir.strip_prefix(project_root) {
            let target_rel_str = target_rel.to_string_lossy().to_string();
            if let Some(id) = try_candidates(&target_rel_str, source_ext, project_files) {
                return Some(id);
            }
        }
    }

    // Case 2: Rust :: paths (crate::, super::, self::, or anything containing ::)
    if import_str.contains("::") || source_ext == "rs" {
        let segments: Vec<&str> = import_str.split("::").filter(|s| !s.is_empty()).collect();
        if !segments.is_empty() {
            // Walk up to nearest Cargo.toml to find crate src/
            let mut crate_root: Option<PathBuf> = None;
            let mut current = source_abs_path.parent();
            while let Some(dir) = current {
                if dir.join("Cargo.toml").exists() {
                    crate_root = Some(dir.join("src"));
                    break;
                }
                if dir == project_root {
                    break;
                }
                current = dir.parent();
            }

            let start_idx = match segments[0] {
                "crate" | "super" | "self" => 1,
                _ => 0,
            };

            let base_dir = if segments[0] == "crate" {
                crate_root.clone()?
            } else if segments[0] == "super" {
                parent_dir.parent().unwrap_or(parent_dir).to_path_buf()
            } else {
                parent_dir.to_path_buf()
            };

            // Try decreasing matching prefix lengths
            let remaining = segments.len().saturating_sub(start_idx);
            for len in (1..=remaining).rev() {
                let sub_segs = &segments[start_idx..(start_idx + len)];
                let sub_path = sub_segs.join("/");
                let full_target = base_dir.join(&sub_path);

                if let Ok(rel_path) = full_target.strip_prefix(project_root) {
                    let rel_str = rel_path.to_string_lossy().to_string();
                    if let Some(id) = try_candidates(&rel_str, "rs", project_files) {
                        return Some(id);
                    }
                }
            }
        }
    }

    // Case 3: Suffix-segment match for absolute module paths
    // (Python `import pkg.mod`, Go `github.com/x/y`, Java `com.foo.Bar`, etc.)
    let mut import_normalized = import_str.replace("::", "/").replace('\\', "/");
    if !import_str.starts_with('.') {
        import_normalized = import_normalized.replace('.', "/");
    }
    let segments: Vec<&str> = import_normalized
        .split('/')
        .filter(|s| !s.is_empty())
        .collect();
    if !segments.is_empty() {
        // Special-cased file stems that act as "package init" / "barrel" files
        const WILDCARD_STEMS: &[&str] = &["mod", "index", "__init__", "package", "lib", "main"];

        // Iterate files; for each, compare the suffix of the file path against
        // the suffix of the import. This makes nested project layouts resolve
        // correctly (e.g. src/app/models/user.py for `app.models.user`).
        for (file_path, &file_id) in project_files {
            let file_normalized = file_path.replace('\\', "/");
            let file_parts: Vec<&str> = file_normalized.split('/').collect();
            if file_parts.is_empty() {
                continue;
            }

            for seg_len in (1..=segments.len()).rev() {
                if file_parts.len() < seg_len {
                    continue;
                }
                let import_suffix = &segments[segments.len() - seg_len..];
                let file_suffix_start = file_parts.len() - seg_len;

                let mut matches = true;
                for i in 0..seg_len {
                    let raw = file_parts[file_suffix_start + i];
                    // Strip extension on the final filename
                    let stem = if file_suffix_start + i == file_parts.len() - 1 {
                        raw.rsplit_once('.').map(|p| p.0).unwrap_or(raw)
                    } else {
                        raw
                    };
                    if stem != import_suffix[i] && !WILDCARD_STEMS.contains(&stem) {
                        matches = false;
                        break;
                    }
                }
                if matches {
                    return Some(file_id);
                }
            }
        }
    }

    None
}

/// Split file content into chunks using AST nodes (symbols) if available, with line-based fallback.
pub fn chunk_file(
    path: &Path,
    content: &str,
    config: &IndexConfig,
) -> (Vec<Chunk>, Option<crate::ast::AstAnalysis>) {
    let analysis = crate::ast::analyze_file(path, content);
    let mut chunks = Vec::new();

    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() {
        return (chunks, analysis);
    }

    if let Some(ref ana) = analysis {
        if !ana.symbols.is_empty() {
            let mut symbols = ana.symbols.clone();
            symbols.sort_by_key(|s| s.start_line);

            let mut last_covered_line = 0usize;

            for sym in symbols {
                let start_idx = (sym.start_line as usize).saturating_sub(1);
                let end_idx = (sym.end_line as usize).min(lines.len());

                if start_idx > last_covered_line {
                    let uncovered_content = lines[last_covered_line..start_idx].join("\n");
                    let sub_chunks = chunk_lines_with_offset(
                        &uncovered_content,
                        last_covered_line + 1,
                        config,
                    );
                    chunks.extend(sub_chunks);
                }

                if start_idx < end_idx {
                    let body = lines[start_idx..end_idx].join("\n");
                    if !body.trim().is_empty() {
                        chunks.push(Chunk {
                            kind: "ast",
                            start_line: sym.start_line,
                            end_line: sym.end_line,
                            content: format!("// AST Symbol: {} ({})\n{}", sym.name, sym.kind, body),
                        });
                    }
                }

                last_covered_line = end_idx;
            }

            if last_covered_line < lines.len() {
                let uncovered_content = lines[last_covered_line..].join("\n");
                let sub_chunks = chunk_lines_with_offset(
                    &uncovered_content,
                    last_covered_line + 1,
                    config,
                );
                chunks.extend(sub_chunks);
            }

            return (chunks, analysis);
        }
    }

    let sub_chunks = chunk_lines_with_offset(content, 1, config);
    (sub_chunks, None)
}

/// Fallback helper to split a text range into sliding line windows.
pub fn chunk_lines_with_offset(
    content: &str,
    line_offset: usize,
    config: &IndexConfig,
) -> Vec<Chunk> {
    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() {
        return Vec::new();
    }

    let chunk_lines = config.chunk_lines.max(1);
    let chunk_overlap = config.chunk_overlap.min(chunk_lines.saturating_sub(1));
    let step = chunk_lines.saturating_sub(chunk_overlap).max(1);

    let mut chunks = Vec::new();
    let mut start = 0usize;

    while start < lines.len() {
        let end = (start + chunk_lines).min(lines.len());
        let body = lines[start..end].join("\n");
        if !body.trim().is_empty() {
            chunks.push(Chunk {
                kind: "lines",
                start_line: (start + line_offset) as u32,
                end_line: (end + line_offset - 1) as u32,
                content: body,
            });
        }
        if end == lines.len() {
            break;
        }
        start += step;
    }
    chunks
}

/// Settings-table keys that influence indexing behavior. Kept in sync with the
/// frontend `settings.ts`.
pub const SETTING_CHUNK_SIZE: &str = "chunk_size";
pub const SETTING_CHUNK_OVERLAP: &str = "chunk_overlap";
pub const SETTING_MAX_FILE_KB: &str = "max_file_size_kb";
pub const SETTING_EXCLUDE_PATTERNS: &str = "exclude_patterns";

/// Build an IndexConfig from a settings map. Missing/invalid values fall back
/// to the defaults so the indexer is always safe to call.
pub fn config_from_settings(
    get: impl Fn(&str) -> Option<String>,
) -> IndexConfig {
    let chunk_lines = get(SETTING_CHUNK_SIZE)
        .and_then(|s| s.parse::<usize>().ok())
        .filter(|n| *n > 0 && *n <= 500)
        .unwrap_or(DEFAULT_CHUNK_LINES);

    let chunk_overlap = get(SETTING_CHUNK_OVERLAP)
        .and_then(|s| s.parse::<usize>().ok())
        .filter(|n| *n < chunk_lines)
        .unwrap_or(DEFAULT_CHUNK_OVERLAP);

    let max_file_bytes = get(SETTING_MAX_FILE_KB)
        .and_then(|s| s.parse::<u64>().ok())
        .filter(|n| *n > 0)
        .map(|kb| kb * 1024)
        .unwrap_or(DEFAULT_MAX_FILE_BYTES);

    let extra_exclude_patterns = get(SETTING_EXCLUDE_PATTERNS)
        .map(|s| {
            s.lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect()
        })
        .unwrap_or_default();

    IndexConfig {
        chunk_lines,
        chunk_overlap,
        max_file_bytes,
        extra_exclude_patterns,
    }
}

/// Guess a language tag from the file extension. Used purely as a hint stored
/// alongside file metadata.
pub fn language_for(path: &Path) -> Option<&'static str> {
    match path.extension()?.to_str()? {
        "rs" => Some("rust"),
        "ts" | "tsx" => Some("typescript"),
        "js" | "jsx" | "mjs" | "cjs" => Some("javascript"),
        "py" => Some("python"),
        "go" => Some("go"),
        "java" => Some("java"),
        "kt" | "kts" => Some("kotlin"),
        "swift" => Some("swift"),
        "c" | "h" => Some("c"),
        "cpp" | "cc" | "cxx" | "hpp" => Some("cpp"),
        "cs" => Some("csharp"),
        "rb" => Some("ruby"),
        "php" => Some("php"),
        "sh" | "bash" | "zsh" => Some("shell"),
        "md" | "mdx" => Some("markdown"),
        "json" => Some("json"),
        "yaml" | "yml" => Some("yaml"),
        "toml" => Some("toml"),
        "sql" => Some("sql"),
        "html" | "htm" => Some("html"),
        "css" | "scss" | "sass" => Some("css"),
        _ => None,
    }
}
